/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({events:{'click .qs-tag':'handleTagSelection'},initialize:function(options){this._super('initialize',[options]);this.tagCollection=[];this.selectedTags=this.layout.selectedTags||[];this.collection=this.layout.collection||app.data.createMixedBeanCollection();this.activeIndex=null;this.layout.on('quicksearch:close quicksearch:results:close',function(){this.activeIndex=null;this.$('.active').removeClass('active');this.disposeKeyEvents();this.close();},this);this.collection.on('sync',this.quicksearchHandler,this);this.on('navigate:focus:receive',function(){this.activeIndex=0;this._highlightActive();this.attachKeyEvents();},this);this.on('navigate:focus:lost',function(){this.activeIndex=null;this.$('.active').removeClass('active');this.disposeKeyEvents();},this);},quicksearchHandler:function(collection){var selectedTags=this.selectedTags;if(collection&&collection.tags){this.tagCollection=_.filter(collection.tags,function(tag){return _.isUndefined(_.find(selectedTags,function(selectedTag){return selectedTag.name===tag.name;}));});this.render();if(this.tagCollection.length){this.open();}else{this.close();}}else{this.close();}},_highlightActive:function(){if(_.isNull(this.activeIndex)){return;}
this.$('.active').removeClass('active');this.$('.qs-tag:eq('+this.activeIndex+')').addClass('active').find('a').focus();},handleTagSelection:function(e){if(e.target&&e.target.text){var self=this;var selectedTag=_.find(this.tagCollection,function(tag){return tag.name===e.target.text;});this.layout.trigger('quicksearch:bar:clear:term');this.layout.trigger('quicksearch:tag:add',selectedTag);_.defer(function(){self.layout.trigger('navigate:to:component','quicksearch-bar')});}},isFocusable:function(){return this.tagCollection&&this.tagCollection.length;},open:function(){this.layout.trigger('quicksearch:tag:open');this.$('.quicksearch-tags').show();},close:function(){this.layout.trigger('quicksearch:tag:close');this.$('.quicksearch-tags').hide();},_handleBoundary:function(next){var event='navigate:next:component';if(!next){event='navigate:previous:component';}
if(this.layout.triggerBefore(event)){this.disposeKeyEvents();this.$('.active').removeClass('active');this.layout.trigger(event);}},moveDown:function(){this._handleBoundary(true);},moveRight:function(){var maxIndex=this.tagCollection.length;if(this.activeIndex<--maxIndex){this.activeIndex++;this._highlightActive();}},moveLeft:function(){if(this.activeIndex>0){this.activeIndex--;this._highlightActive();}},moveUp:function(){this._handleBoundary(false);},keydownHandler:function(e){switch(e.keyCode){case 40:this.moveDown();break;case 39:this.moveRight();break;case 38:this.moveUp();break;case 37:this.moveLeft();break;case 13:e.preventDefault();e.stopImmediatePropagation();break;}},keyupHandler:function(e){switch(e.keyCode){case 13:this.handleTagSelection(e);break;}},attachKeyEvents:function(){this.$el.on('keydown',_.bind(this.keydownHandler,this));this.$el.on('keyup',_.bind(this.keyupHandler,this));},disposeKeyEvents:function(){this.$el.off();},unbind:function(){this.disposeKeyEvents();this._super('unbind');}})