/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({id:'searchForm',preTag:'<strong>',postTag:'</strong>',plugins:['Dropdown'],dropdownItemSelector:'[data-action="select-module"]',searchModules:[],events:{'click .typeahead a':'clearSearch','click [data-action=search]':'showResults','click [data-advanced=options]':'persistMenu','click [data-action="select-module"]':'selectModule'},initialize:function(options){app.view.View.prototype.initialize.call(this,options);app.events.on('app:sync:complete',this.populateModules,this);app.shortcuts.register(app.shortcuts.GLOBAL+'Search',['s','ctrl+alt+0'],function(){this.$('input.search-query').focus();},this);},selectModule:function(event){var module=this.$(event.currentTarget).data('module'),searchAll=this.$('input:checkbox[data-module="all"]'),searchAllLabel=searchAll.closest('label'),checkedModules=this.$('input:checkbox:checked[data-module!="all"]');if(module==='all'){searchAll.attr('checked',true);searchAllLabel.addClass('active');checkedModules.removeAttr('checked');checkedModules.closest('label').removeClass('active');}else{var currentTarget=this.$(event.currentTarget),currentTargetLabel=currentTarget.closest('label');currentTarget.attr('checked')?currentTargetLabel.addClass('active'):currentTargetLabel.removeClass('active');if(checkedModules.length){searchAll.removeAttr('checked');searchAllLabel.removeClass('active');}
else{searchAll.attr('checked',true);searchAllLabel.addClass('active');}}
event.stopPropagation();},populateSearchableModules:function(options){var modules=options.modules,moduleNames=options.moduleNames||null,acl=options.acl,searchModules=[];_.each(modules,function(meta,module){var goodToAdd=true;if(moduleNames&&!_.contains(moduleNames,module)){goodToAdd=false;}
if(goodToAdd&&acl.hasAccess.call(acl,'view',module)){if(options.checkGlobalSearchEnabled&&!meta.globalSearchEnabled){goodToAdd=false;}
if(goodToAdd&&options.checkFtsEnabled&&!meta.ftsEnabled){goodToAdd=false;}
if(goodToAdd){searchModules.push(module);}}},this);return searchModules;},_escapeSearchResults:function(html){var highlightedSpanRe=/<strong>.*?<\/strong>/g,higlightSpanTagsRe=/(<strong>)|(<\/strong>)/g,escape=Handlebars.Utils.escapeExpression,result=escape(html),highlightedSpan=html.match(highlightedSpanRe),highlightedContent,self=this;_.each(highlightedSpan,function(part){highlightedContent=part.replace(higlightSpanTagsRe,'');highlightedContent=escape(highlightedContent);result=result.replace(escape(part),self.preTag+highlightedContent+self.postTag);});return new Handlebars.SafeString(result);},_getSearchModuleNames:function(){if(this.$('input:checkbox[data-module="all"]').attr('checked')){return[];}
else{var searchModuleNames=[],checkedModules=this.$('input:checkbox:checked[data-module!="all"]');_.each(checkedModules,function(val,index){searchModuleNames.push(val.getAttribute('data-module'));},this);return searchModuleNames;}},showResults:function(evt){var $searchBox=this.$('[data-provide=typeahead]');if(!$searchBox.is(':visible')){var body=$('body');this.$el.addClass('active');body.on('click.globalsearch.data-api',_.bind(function(event){if(!$.contains(this.el,event.target)){this.$el.removeClass('active');body.off('click.globalsearch.data-api');}},this));app.accessibility.run(body,'click');$searchBox.focus();return;}
var e=jQuery.Event('keyup',{keyCode:$.ui.keyCode.ENTER});$searchBox.focus();$searchBox.trigger(e);},clearSearch:function(){this.$('.search-query').val('');},persistMenu:function(e){e.stopPropagation();},unbind:function(){$('body').off('click.globalsearch.data-api');this._super('unbind');},_renderHtml:function(){if(!app.api.isAuthenticated()||app.config.appStatus=='offline'){return;}
app.view.View.prototype._renderHtml.call(this);var self=this,menuTemplate=app.template.getView(this.name+'.result');this.$('.search-query').searchahead({context:self,request:function(term){self.fireSearchRequest(term);},compiler:menuTemplate,throttleMillis:(app.config.requiredElapsed||500),throttle:function(callback,millis){if(!self.debounceFunction){self.debounceFunction=_.debounce(function(){callback();},millis||500);}
self.debounceFunction();},onEnterFn:function(hrefOrTerm,isHref){if(isHref){window.location=hrefOrTerm;}else{var term=$.trim(self.$('.search-query').attr('value'));if(!_.isEmpty(term)){self.fireSearchRequest(term,this);}}}});this.$('.navbar-search').submit(function(){return false;});},populateModules:function(){if(this.disposed){return;}
var modules=app.metadata.getModules()||{};var moduleNames=app.metadata.getModuleNames({filter:'display_tab'});this.searchModules=this.populateSearchableModules({modules:modules,moduleNames:moduleNames,acl:app.acl,checkFtsEnabled:false,checkGlobalSearchEnabled:true});this.render();},fireSearchRequest:function(term){var self=this,searchModuleNames=this._getSearchModuleNames(),maxNum=app.config&&app.config.maxSearchQueryResult?app.config.maxSearchQueryResult:5,params={q:term,fields:'name, id',module_list:searchModuleNames.join(','),max_num:maxNum};app.api.search(params,{success:function(data){var formattedRecords=[],modList=app.metadata.getModuleNames({filter:'quick_create',action:'create'}),moduleIntersection=_.intersection(modList,self.searchModules);_.each(data.records,function(record){if(!record.id){return;}
var formattedRecord={id:record.id,name:record.name,module:record._module,link:'#'+app.router.buildRoute(record._module,record.id)};if((record._search.highlighted)){_.each(record._search.highlighted,function(val,key){if(key!=='name'){formattedRecord.field_name=app.lang.get(val.label,val.module);formattedRecord.field_value=val.text;}});}
formattedRecords.push(formattedRecord);});self.$('.search-query').searchahead('provide',{module_list:moduleIntersection,next_offset:data.next_offset,records:formattedRecords});},error:function(error){app.error.handleHttpError(error,plugin);app.logger.error('Failed to fetch search results in search ahead. '+error);}});},gotoFullSearchResultsPage:function(evt){var term;evt.preventDefault();evt.stopPropagation();term=encodeURIComponent(this.$('.search-query').val());if(term&&term.length){this.$('.search-query').searchahead('disable',1000);app.router.navigate('#search/'+term,{trigger:true});}}})