/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'GlobalsearchView',_renderHtml:function(){if(!app.api.isAuthenticated()||app.config.appStatus=='offline')return;app.view.View.prototype._renderHtml.call(this);var self=this,menuTemplate=app.template.getView(this.name+'.result');this.$('.search-query').searchahead({context:self,request:function(term){self.fireSearchRequest(term);},compiler:menuTemplate,throttleMillis:(app.config.requiredElapsed||500),throttle:function(callback,millis){if(!self.debounceFunction){self.debounceFunction=_.debounce(function(){callback();},millis||500);}
self.debounceFunction();},onEnterFn:function(hrefOrTerm,isHref){if(isHref){window.location=hrefOrTerm;}else{var term=$.trim(self.$('.search-query').attr('value'));if(!_.isEmpty(term)){self.fireSearchRequest(term,this);}}}});this.$('.navbar-search').submit(function(){return false;});},populateModules:function(){if(this.disposed){return;}
var modules=app.metadata.getModules()||{};var moduleNames=app.metadata.getModuleNames({filter:'display_tab'});this.searchModules=this.populateSearchableModules({modules:modules,moduleNames:moduleNames,acl:app.acl,checkFtsEnabled:false,checkGlobalSearchEnabled:true});this.render();},fireSearchRequest:function(term){var self=this,searchModuleNames=this._getSearchModuleNames(),maxNum=app.config&&app.config.maxSearchQueryResult?app.config.maxSearchQueryResult:5,params={q:term,fields:'name, id',module_list:searchModuleNames.join(","),max_num:maxNum};app.api.search(params,{success:function(data){var formattedRecords=[],modList=app.metadata.getModuleNames({filter:'quick_create',action:'create'}),moduleIntersection=_.intersection(modList,self.searchModules);_.each(data.records,function(record){if(!record.id){return;}
var formattedRecord={id:record.id,name:record.name,module:record._module,link:'#'+app.router.buildRoute(record._module,record.id)};if((record._search.highlighted)){_.each(record._search.highlighted,function(val,key){if(key!=='name'){formattedRecord.field_name=app.lang.get(val.label,val.module);formattedRecord.field_value=val.text;}});}
formattedRecords.push(formattedRecord);});self.$('.search-query').searchahead('provide',{module_list:moduleIntersection,next_offset:data.next_offset,records:formattedRecords});},error:function(error){app.error.handleHttpError(error,plugin);app.logger.error("Failed to fetch search results in search ahead. "+error);}});},gotoFullSearchResultsPage:function(evt){var term;evt.preventDefault();evt.stopPropagation();term=encodeURIComponent(this.$('.search-query').val());if(term&&term.length){this.$('.search-query').searchahead('disable',1000);app.router.navigate('#search/'+term,{trigger:true});}}})