<?php

 /*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Home/Dashlets/InvadersDashlet/InvadersDashlet.tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dashletStrings = array ( 
   'InvadersDashlet' => array (
      'LBL_TITLE' => 'İstilacılar!' ,
      'LBL_DESCRIPTION' => 'Vakit geçirmek için iyi bir yol' ,
      'LBL_DBLCLICK_HELP' => 'Hareket için A ve D, ateş etmek için S yi kullanın' ,
      'LBL_START' => 'Başlamak İçin Tıklayın' ,
      'LBL_GAME_OVER' => 'Oyun bitti (Tekrar oynamak için tıklayınız)'   ));

?>
