/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({className:'row-fluid',dashboardLayouts:{'record':'record-dashboard','records':'list-dashboard'},events:{'click [data-action=create]':'createClicked'},error:{handleNotFoundError:function(error){var currentRoute=Backbone.history.getFragment();if(currentRoute.substr(0,5)==='Home/'){app.router.redirect('#Home');return false;}},handleValidationError:function(error){return false;}},dashboardVisibleState:'open',initialize:function(options){var context=options.context,module=context.parent&&context.parent.get('module')||context.get('module');if(options.meta&&options.meta.method&&options.meta.method==='record'&&!context.get('modelId')){context.set('create',true);}
var model=this._getNewDashboardObject('model',context);if(context.get('modelId')){model.set('id',context.get('modelId'),{silent:true});}
context.set({model:model,collection:this._getNewDashboardObject('collection',context)});this._super('initialize',[options]);this.model.on('setMode',function(mode){if(mode==='edit'||mode==='create'){this.$('.dashboard').addClass('edit');}else{this.$('.dashboard').removeClass('edit');}},this);app.events.on('app:help:show',this.openHelpDashboard,this);app.events.on('app:help:hide',this.closeHelpDashboard,this);var defaultLayout=this.closestComponent('sidebar');if(defaultLayout){this.listenTo(defaultLayout,'sidebar:state:changed',function(state){this.dashboardVisibleState=state;if(state==='open'&&this.isHelpDashboard()){app.events.trigger('app:help:shown');}else{app.events.trigger('app:help:hidden');}},this);try{this.dashboardVisibleState=defaultLayout.isSidePaneVisible()?'open':'close';}catch(error){}}
this.model.on('sync',function(){if(this.dashboardVisibleState==='open'&&this.isHelpDashboard()){app.events.trigger('app:help:shown');if(this.module==='Home'){var list=this.getComponent('list'),headerpane=(!_.isUndefined(list))?list.getComponent('dashboard-headerpane'):undefined;if(headerpane){var help_headerpane_meta=app.metadata.getView(this.module,'help-dashboard-headerpane');help_headerpane_meta.last_state=headerpane.meta.last_state;headerpane.meta=help_headerpane_meta;headerpane.render();}}}},this);if(module==='Home'&&context.has('modelId')){var lastVisitedStateKey=this.getLastStateKey();app.user.lastState.set(lastVisitedStateKey,context.get('modelId'));}
if(module==='Activities'&&!context.has('modelId')&&_.isUndefined(this.model.mode)){this.once('render',function(){this.collection.fetch({silent:true,success:_.bind(this.setDefaultDashboard,this)});},this);}},openHelpDashboard:function(){if(this.dashboardVisibleState==='close'){var defaultLayout=this.closestComponent('sidebar');if(defaultLayout){defaultLayout.toggleSidePane(true);}}
if(!this.isHelpDashboard()){this.collection.fetch({silent:true,success:_.bind(this.showHelpDashboard,this)});}},closeHelpDashboard:function(){if(this.isHelpDashboard()){this.collection.fetch({silent:true,success:_.bind(this.hideHelpDashboard,this)});}},showHelpDashboard:function(collection){var dashboard=_.find(collection.models,function(model){return(model.get('dashboard_type')==='help-dashboard');});this._navigate(dashboard);},hideHelpDashboard:function(collection){var dashboard=_.find(collection.models,function(model){return(model.get('dashboard_type')!='help-dashboard');});app.user.lastState.set(this.getLastStateKey(),'');this._navigate(dashboard);},isHelpDashboard:function(){return(this.model.get('dashboard_type')==='help-dashboard');},loadData:function(options,setFields){if(this.context.parent&&!this.context.parent.isDataFetched()){var parent=this.context.parent.get('modelId')?this.context.parent.get('model'):this.context.parent.get('collection');if(parent){parent.once('sync',function(){this._super('loadData',[options,setFields]);},this);}}else{this._super('loadData',[options,setFields]);}},createClicked:function(evt){if(this.model.dashboardModule==='Home'){var route=app.router.buildRoute(this.module,null,'create');app.router.navigate(route,{trigger:true});}else{this.navigateLayout('create');}},_placeComponent:function(component){var dashboardEl=this.$('[data-dashboard]'),css=this.context.get('create')?' edit':'';if(dashboardEl.length===0){dashboardEl=$('<div></div>').attr({'class':'cols row-fluid'});this.$el.append($('<div></div>').addClass('dashboard'+css).attr({'data-dashboard':'true'}).append(dashboardEl));}else{dashboardEl=dashboardEl.children('.row-fluid');}
dashboardEl.append(component.el);},bindDataChange:function(){var modelId=this.context.get('modelId');if(!(modelId&&this.context.get('create'))&&this.collection){this.collection.on('reset',this.setDefaultDashboard,this);}},setDefaultDashboard:function(){if(this.disposed){return;}
var lastVisitedStateKey=this.getLastStateKey(),lastViewed=app.user.lastState.get(lastVisitedStateKey),hasHelpOnly=(this.collection.models.length==1&&_.first(this.collection.models).get('dashboard_type')==='help-dashboard'),helpLastShown=(hasHelpOnly&&lastViewed===_.first(this.collection.models).get('id'));if(hasHelpOnly&&!helpLastShown){this._renderEmptyTemplate();}else if(this.collection.models.length>0){var currentModule=this.context.get('module'),model;if(currentModule!=='Home'){model=_.first(this.collection.models);}else{model=this.collection.find(function(dash){return dash.get('dashboard_type')==='dashboard';});}
if(lastViewed){var lastVisitedModel=this.collection.get(lastViewed);if(!_.isEmpty(lastVisitedModel)){app.user.lastState.set(lastVisitedStateKey,'');model=lastVisitedModel;}}
if(currentModule=='Home'&&_.isString(lastViewed)&&lastViewed.indexOf('bwc_dashboard')!==-1){app.router.navigate(lastViewed,{trigger:true});}else{this._navigate(model);}}else{var _initDashboard=this._getInitialDashboardMetadata();if(_initDashboard&&!_.isEmpty(_initDashboard.metadata)){_.each(_initDashboard.metadata['components'],function(component,component_key){_.each(component['rows'],function(row,row_key){_initDashboard.metadata['components'][component_key]['rows'][row_key]=_.filter(row,function(cell){var module=(cell.context&&cell.context.module)?cell.context.module:this.module;return(!app.acl.hasAccess('access',module));});},this);_initDashboard.metadata['components'][component_key]['rows']=_.filter(_initDashboard.metadata['components'][component_key]['rows'],function(row){return(row.length>0);});},this);}
_.each(_initDashboard,function(dash){var model=this._getNewDashboardObject('model',this.context);model.set(dash);if(this.context.get('modelId')){model.set('id',this.context.get('modelId'),{silent:true});}
if(!_.isUndefined(model.get('metadata'))){model.save({},this._getDashboardModelSaveParams());}},this);}},_getInitialDashboardMetadata:function(){var layoutName=this.dashboardLayouts[this.context.parent&&this.context.parent.get('layout')||'record'],initDash=app.metadata.getLayout(this.model.dashboardModule,layoutName)||{};if(_.has(initDash,'metadata')){initDash.dashboard_type=initDash.dashboard_type||'dashboard';}
return this.addHelpDashboardMetadata(initDash);},addHelpDashboardMetadata:function(_initDashboard){var _helpDB=app.metadata.getLayout(this.model.dashboardModule,'help-dashboard');if(_.has(_initDashboard,'metadata')){_initDashboard=[_helpDB,_initDashboard];}else{_initDashboard=[_helpDB];}
return _initDashboard;},getLastStateKey:function(){if(this._lastStateKey){return this._lastStateKey;}
var model=this.context.get('model'),view=model.get('view_name'),module=model.dashboardModule,key=module+'.'+view;this._lastStateKey=app.user.lastState.key(key,this);return this._lastStateKey;},_navigate:function(dashboard){if(this.disposed){return;}
var hasParentContext=(this.context&&this.context.parent),hasModelId=(dashboard&&dashboard.has('id')),actualModule=(hasParentContext)?this.context.parent.get('module'):this.module,isHomeModule=(actualModule==='Home');if(hasParentContext&&hasModelId){this._navigateLayout(dashboard.get('id'),dashboard.get('dashboard_type'));}else if(hasParentContext&&!hasModelId){this._navigateLayout('list');}else if(!hasParentContext&&hasModelId&&isHomeModule){app.navigate(this.context,dashboard);}else if(isHomeModule){var route=app.router.buildRoute(this.module);app.router.navigate(route,{trigger:true});}},_navigateLayout:function(dashboard,type){var onConfirm=_.bind(function(){this.navigateLayout(dashboard,type);},this),headerpane=this.getComponent('dashboard-headerpane');if(headerpane&&headerpane.changed){return headerpane.warnUnsavedChanges(onConfirm,undefined,_.bind(function(){this.collection.reset([],{silent:true});},this));}
onConfirm();},navigateLayout:function(id,type){var layout=this.layout,lastVisitedStateKey=this.getLastStateKey(),type=(_.isUndefined(type))?'dashboard':type;this.dispose();if(!_.contains(['dashboard','help-dashboard'],type)){type='dashboard';}
if(!_.contains(['create','list'],id)){app.user.lastState.set(lastVisitedStateKey,id);}
var ctxVars={dashboard_type:'dashboard'};if(id==='create'){ctxVars.create=true;}else if(id!=='list'){ctxVars.modelId=id;}
layout._addComponentsFromDef([{layout:{type:'dashboard',components:(id==='list')?[]:[{view:type+'-headerpane'},{layout:'dashlet-main'}],last_state:{id:'last-visit'}},context:_.extend({module:'Home',forceNew:true},ctxVars)}]);layout.removeComponent(0);layout.loadData({},false);layout.render();},unbindData:function(){var model,collection;if(this.collection){this.collection.off('reset',this.setDefaultDashboard,this);}
if(this.context.parent){model=this.context.parent.get('model');collection=this.context.parent.get('collection');if(model){model.off('sync',null,this);}
if(collection){collection.off('sync',null,this);}}
this._super('unbindData');},_getNewDashboardObject:function(modelOrCollection,context){var obj,ctx=context&&context.parent||context,module=ctx.get('module')||context.get('module'),layoutName=ctx.get('layout')||'',sync=function(method,model,options){options=app.data.parseOptionsForSync(method,model,options);if(options&&options.params){options.params.max_num=-1;}
var callbacks=app.data.getSyncCallbacks(method,model,options),path=(this.dashboardModule==='Home'||model.id)?this.apiModule:this.apiModule+'/'+this.dashboardModule;if(method==='read'){options.params.view_name=layoutName;}
app.api.records(method,path,model.attributes,options.params,callbacks);};if(module==='Home'){layoutName='';}
switch(modelOrCollection){case'model':obj=this._getNewDashboardModel(module,layoutName,sync);break;case'collection':obj=this._getNewDashboardCollection(module,layoutName,sync);break;}
return obj;},_getNewDashboardModel:function(module,layoutName,syncFn,getNew){getNew=(_.isUndefined(getNew))?true:getNew;var Dashboard=app.Bean.extend({sync:syncFn,apiModule:'Dashboards',module:'Home',dashboardModule:module,maxColumns:(module==='Home')?3:1,minColumnSpanSize:(module==='Home')?4:12,defaults:{view_name:layoutName}});return(getNew)?new Dashboard():Dashboard;},_getNewDashboardCollection:function(module,layoutName,syncFn,getNew){getNew=(_.isUndefined(getNew))?true:getNew;var Dashboard=this._getNewDashboardModel(module,layoutName,syncFn,false),DashboardCollection=app.BeanCollection.extend({sync:syncFn,apiModule:'Dashboards',module:'Home',dashboardModule:module,model:Dashboard});return(getNew)?new DashboardCollection():DashboardCollection;},_getDashboardModelSaveParams:function(){var params={silent:true,showAlerts:false};params.error=_.bind(this._renderEmptyTemplate,this);params.success=_.bind(function(model){if(!this.disposed){if(model.get('dashboard_module')!=='Home'){if(model.get('dashboard_type')==='help-dashboard'){this._navigate(model);}}else{if(model.get('dashboard_type')==='dashboard'){this._navigate(model);}}}},this);return params;},_renderEmptyTemplate:function(){var tplName=this.type||this.name,template=app.template.getLayout(tplName+'.dashboard-empty');this.$el.html(template(this));},_dispose:function(){app.events.trigger('app:help:hidden');var defaultLayout=this.closestComponent('sidebar');if(defaultLayout){this.stopListening(defaultLayout);}
this.dashboardLayouts=null;this._super('_dispose');}})