/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({events:{'change input':'filterNameChanged','keyup input':'filterNameChanged','click a.reset_button':'triggerReset','click a.filter-close':'triggerClose','click a.save_button:not(.disabled)':'triggerSave','click a.delete_button:not(.hide)':'triggerDelete'},className:'filter-header',saveState:false,showActions:true,initialize:function(opts){this._super('initialize',[opts]);this.layout.on('filter:create:open',function(model){this.toggle(model);var name=model?model.get('name'):'';this.setFilterName(name);app.shortcuts.register('Filter:Close',['esc','ctrl+alt+l'],function(){this.$('a.filter-close').click();},this,true);app.shortcuts.register('Filter:Save',['ctrl+s','ctrl+alt+a'],function(){this.$('a.save_button:not(.disabled)').click();},this,true);app.shortcuts.register('Filter:Delete','d',function(){this.$('a.delete_button:not(.hide)').click();},this);app.shortcuts.register('Filter:Reset','r',function(){this.$('a.reset_button').click();},this);},this);this.listenTo(this.layout,'filter:toggle:savestate',this.toggleSave);this.listenTo(this.layout,'filter:set:name',this.setFilterName);this.listenTo(this.context,'change:filterOptions',this.render);this.before('render',this.setShowActions,null,this);},setShowActions:function(){var filterOptions=this.context.get('filterOptions')||{};this.showActions=!!filterOptions.show_actions;},getFilterName:function(){return this.$('input').val();},toggle:function(filter){this.$el.toggleClass('hide',!!filter.get('is_template'));},setFilterName:function(name){var input=this.$('input').val(name);if(_.isFunction(input.placeholder)){input.placeholder();}
this.toggleDelete(!_.isEmpty(name));},filterNameChanged:_.debounce(function(event){if(this.disposed||!this.context.editingFilter){return;}
var name=this.getFilterName();this.context.editingFilter.set('name',name);this.layout.trigger('filter:toggle:savestate',true);if(this.layout.getComponent('filter-rows')){this.layout.getComponent('filter-rows').saveFilterEditState();}},200),toggleDelete:function(enable){this.$('.delete_button').toggleClass('hide',!enable);},toggleSave:function(enable){this.saveState=_.isUndefined(enable)?!this.saveState:!!enable;var isEnabled=this.getFilterName()&&this.saveState;this.$('.save_button').toggleClass('disabled',!isEnabled);},triggerClose:function(){var filter=this.context.editingFilter,filterLayout=this.layout.getComponent('filter'),id=filter.get('id'),changedAttributes=filter.changedAttributes(filter.getSyncedAttributes());filter.revertAttributes();filterLayout.clearFilterEditState();if(changedAttributes&&changedAttributes.filter_definition){this.layout.trigger('filter:apply',null,filter.get('filter_definition'));}
if(!id){filterLayout.clearLastFilter(this.layout.currentModule,filterLayout.layoutType);filterLayout.trigger('filter:select:filter',filterLayout.filters.collection.defaultFilterFromMeta);return;}
this.layout.trigger('filter:create:close');},triggerReset:function(){this.layout.getComponent('filter-rows').resetFilterValues();},triggerSave:function(){var filterName=this.getFilterName();this.context.trigger('filter:create:save',filterName);},triggerDelete:function(){this.layout.trigger('filter:create:delete');}})