/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({events:{"click .toggle-actions a.btn":"toggleView"},plugins:['Tooltip'],initialize:function(opts){this.toggleComponents=[];this.componentsList={};this.processToggles();app.view.Layout.prototype.initialize.call(this,opts);},_render:function(){this._super('_render');this.toggleViewLastStateKey=app.user.lastState.key('toggle-view',this);var lastViewed=app.user.lastState.get(this.toggleViewLastStateKey);if(_.isUndefined(lastViewed)||this.isToggleButtonDisabled(lastViewed)){var enabledToggles=_.filter(this.toggles,function(toggle){return!toggle.disabled;});if(enabledToggles.length>0){lastViewed=_.first(enabledToggles).toggle;}}
this.showComponent(lastViewed,true);this.$('[data-view="'+lastViewed+'"]').button('toggle');},isToggleButtonDisabled:function(name){var disabled=false,toggleButton;toggleButton=_.find(this.toggles,function(toggle){return toggle.toggle===name;});if(toggleButton){disabled=toggleButton.disabled;}
return disabled;},processToggles:function(){this.toggles=[];var temp={};_.each(this.options.meta.components,function(component){var toggle;if(component.view){toggle=component.view;}else if(component.layout){toggle=(_.isString(component.layout))?component.layout:component.layout.name;}
var availableToggle=_.find(this.options.meta.availableToggles,function(curr){return curr.name===toggle;},this);if(toggle&&availableToggle){var disabled=!!availableToggle.disabled;temp[toggle]={toggle:toggle,title:availableToggle.label,'class':availableToggle.icon,disabled:disabled};}},this);if(this.options.meta.availableToggles){for(var i=0;i<this.options.meta.availableToggles.length;i++){var curr=this.options.meta.availableToggles[i];if(temp[curr.name]){this.toggles.push(temp[curr.name]);}}}},_placeComponent:function(component,def){if(def&&def.targetEl){if(def.position=='prepend'){this.$(def.targetEl).prepend(component.el);return;}else{this.$(def.targetEl).append(component.el);}}else{var toggleAvailable=_.isObject(_.find(this.options.meta.availableToggles,function(curr){return curr.name===component.name;}));if(toggleAvailable){this.toggleComponents.push(component);this.componentsList[component.name]=component;this._components.splice(this._components.indexOf(component),1);}else{component.render();this.$(".main-content").append(component.el);}}},toggleView:function(e){var $el=this.$(e.currentTarget);if($el.attr('disabled')==='disabled'){e.preventDefault();e.stopPropagation();return;}
if(!$el.hasClass("active")){var data=$el.data();app.user.lastState.set(this.toggleViewLastStateKey,data.view);this.showComponent(data.view);this.reloadData(data.view);}},showComponent:function(name,silent){if(!name)return;if(this.componentsList[name]){this.componentsList[name].render();this._components.push(this.componentsList[name]);this.$(".main-content").append(this.componentsList[name].el);}
_.each(this.toggleComponents,function(comp){if(comp.name==name){comp.show();}else{comp.hide();}},this);this.trigger('filterpanel:change',name,silent);},reloadData:function(name){var layout=this.componentsList[name];if(layout){layout.context.resetLoadFlag(true);layout.loadData();}},_dispose:function(){_.each(this.componentsList,function(component){if(component){component.dispose();}});this.componentsList={};this.toggleComponents=null;app.view.Layout.prototype._dispose.call(this);}})