/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({allow_single_deselect:true,minChars:1,fieldTag:'input.select2',plugins:['QuickSearchFilter','EllipsisInline'],initialize:function(options){this.minChars=options.def.minChars||this.minChars;app.view.Field.prototype.initialize.call(this,options);var populateMetadata=app.metadata.getModule(this.getSearchModule());if(_.isEmpty(populateMetadata)){return;}
_.each(this.def.populate_list,function(target,source){if(_.isUndefined(populateMetadata.fields[source])){app.logger.error('Fail to populate the related attributes: attempt to access undefined key - '+
this.getSearchModule()+'::'+source);}},this);},_createFiltersCollection:function(options){var searchModule=this.getSearchModule();if(app.metadata.getModule('Filters')&&searchModule){this.filters=app.data.createBeanCollection('Filters');this.filters.setModuleName(searchModule);this.filters.setFilterOptions(this.getFilterOptions());this.filters.load(options);}},bindKeyDown:function(callback){var $dropdown=this.$(this.fieldTag);$dropdown.on('keydown.record',{field:this},callback);var plugin=$dropdown.data('select2');if(plugin){plugin.focusser.on('keydown.record',{field:this},callback);plugin.search.on('keydown.record',{field:this},callback);}},unbindKeyDown:function(callback){var $dropdown=this.$(this.fieldTag);$dropdown.off('keydown.record',callback);var plugin=$dropdown.data('select2');if(plugin){plugin.search.off('keydown.record',callback);}},focus:function(){var self=this;if(this.action!=='disabled'){_.defer(function(){self.$(self.fieldTag).select2('open')});}},_render:function(){var searchModule=this.getSearchModule();if(searchModule&&!_.contains(app.metadata.getModuleNames(),searchModule)){return this;}
this._super('_render');switch(this.tplName){case'edit':case'massupdate':this._createFiltersCollection({success:_.bind(function(){if(!this.disposed){this._renderEditableDropdown();}},this)});break;case'disabled':this._renderDisabledDropdown();break;}
return this;},_renderEditableDropdown:function(){var self=this;var $dropdown=this.$(this.fieldTag);var inList=(this.view.name==='recordlist'),cssClasses=(inList?'select2-narrow':'')+(this.type==='parent'?' select2-parent':''),relatedModuleField=this.getRelatedModuleField();$dropdown.select2({width:inList?'off':'100%',dropdownCssClass:cssClasses,containerCssClass:cssClasses,initSelection:function(el,callback){var $el=$(el),id=$el.data('id'),text=$el.val();callback({id:id,text:text});},formatInputTooShort:function(){return'';},formatSearching:function(){return app.lang.get("LBL_LOADING",self.module);},placeholder:this.getPlaceHolder(),allowClear:self.allow_single_deselect,minimumInputLength:self.minChars,query:_.bind(this.search,this)}).on("select2-open",function(){var plugin=$(this).data('select2');if(!plugin.searchmore){var $content=$('<li class="select2-result">').append($('<div/>').addClass('select2-result-label').html(app.lang.get('LBL_SEARCH_FOR_MORE',self.module))).mousedown(function(){plugin.opts.element.trigger($.Event("searchmore"));plugin.close();});plugin.searchmore=$('<ul class="select2-results">').append($content);plugin.dropdown.append(plugin.searchmore);}}).on('searchmore',function(){$(this).select2('close');self.openSelectDrawer();}).on("change",function(e){var id=e.val,plugin=$(this).data('select2'),value=(id)?plugin.selection.find("span").text():$(this).data('id'),collection=plugin.context,attributes={};if(_.isUndefined(id)){return;}
plugin.opts.element.data("id",id);if(collection&&!_.isEmpty(id)){var model=collection.get(id);attributes.id=model.id;attributes.value=model.get('name');_.each(model.attributes,function(value,field){if(app.acl.hasAccessToModel('view',model,field)){attributes[field]=attributes[field]||model.get(field);}});}else if(e.currentTarget.value&&value){attributes.id=value;attributes.value=e.currentTarget.value;}else{attributes.id='';attributes.value='';}
self.setValue(attributes);});var plugin=$dropdown.data('select2');if(plugin&&plugin.focusser){plugin.focusser.on('select2-focus',_.bind(_.debounce(this.handleFocus,0),this));}},_renderDisabledDropdown:function(){var loadingLabel=app.lang.get('LBL_LOADING',this.module);var $dropdown=this.$(this.fieldTag);$dropdown.select2({width:'100%',initSelection:function(el,callback){var $el=$(el),id=$el.data('id'),text=$el.val();callback({id:id,text:text});},formatInputTooShort:function(){return'';},formatSearching:function(){return loadingLabel;},placeholder:this.getPlaceHolder(),allowClear:self.allow_single_deselect,minimumInputLength:self.minChars,query:_.bind(this.search,this)});$dropdown.select2('disable');},buildRoute:function(module,id){var oldModule=module;if(module==='Users'&&this.context.get('module')!=='Users'){module='Employees';}
if(_.isEmpty(module)||(!_.isUndefined(this.def.link)&&!this.def.link)){return;}
var action=(this.def.link&&this.def.route)?this.def.route.action:"view";if(app.acl.hasAccess(action,oldModule)){this.href='#'+app.router.buildRoute(module,id);}},_buildRoute:function(){this.buildRoute(this.getSearchModule(),this._getRelateId());},_getRelateId:function(){return this.model.get(this.def.id_name);},format:function(value){var parentCtx=this.context&&this.context.parent,setFromCtx;setFromCtx=value===null&&parentCtx&&_.isEmpty(this.context.get('model').link)&&this.view instanceof app.view.views.BaseCreateView&&parentCtx.get('module')===this.def.module&&this.module!==this.def.module;if(setFromCtx){var model=parentCtx.get('model');this.def.auto_populate=true;this.setValue(model.toJSON());}
this._buildRoute();return value;},unformat:function(value){return this.model.get(this.def.id_name);},setValue:function(model){if(!model){return;}
var silent=model.silent||false,values={};values[this.def.id_name]=model.id;values[this.def.name]=model[this.getRelatedModuleField()]||model.value;this.model.set(values,{silent:silent});if(this.model.get(this.def.link)){this.model.unset(this.def.link);}else{this.model.trigger("change:"+this.def.link);}
var newData={},self=this;_.each(this.def.populate_list,function(target,source){source=_.isNumber(source)?target:source;if(!_.isUndefined(model[source])&&app.acl.hasAccessToModel('edit',this.model,target)){var before=this.model.get(target),after=model[source];if(before!==after){newData[target]=model[source];}}},this);if(_.isEmpty(newData)){return;}
if(!_.isUndefined(this.def.auto_populate)&&this.def.auto_populate==true){if(!_.isUndefined(newData.currency_id)){this.model.set({currency_id:newData.currency_id});delete newData.currency_id;}
this.model.set(newData);return;}
var messageTplKey=this.def.populate_confirm_label||'TPL_OVERWRITE_POPULATED_DATA_CONFIRM',messageTpl=Handlebars.compile(app.lang.get(messageTplKey,this.getSearchModule())),fieldMessageTpl=app.template.getField(this.type,'overwrite-confirmation',this.model.module),messages=[],relatedModuleSingular=app.lang.getModuleName(this.def.module);_.each(newData,function(value,field){var before=this.model.get(field),after=value;if(before!==after){var def=this.model.fields[field];messages.push(fieldMessageTpl({before:before,after:after,field_label:app.lang.get(def.label||def.vname||field,this.module)}));}},this);app.alert.show('overwrite_confirmation',{level:'confirmation',messages:messageTpl({values:new Handlebars.SafeString(messages.join(', ')),moduleSingularLower:relatedModuleSingular.toLowerCase()}),onConfirm:function(){if(!_.isUndefined(newData.currency_id)){self.model.set({currency_id:newData.currency_id});delete newData.currency_id;}
self.model.set(newData);}});},openSelectDrawer:function(){app.drawer.open({layout:'selection-list',context:{module:this.getSearchModule(),fields:this.getSearchFields(),filterOptions:this.getFilterOptions()}},_.bind(this.setValue,this));},getSearchFields:function(){return _.union(['id',this.getRelatedModuleField()],_.keys(this.def.populate_list||{}));},getRelatedModuleField:function(){return this.def.rname||'name';},bindDomChange:function(){},getSearchModule:function(){if(this.def.module){return this.def.module;}
var link=this.def.link&&this.model.fields&&this.model.fields[this.def.link]||{};if(link.module){return link.module;}
return app.data.getRelatedModule(this.model.module,this.def.link);},getPlaceHolder:function(){var searchModule=this.getSearchModule(),searchModuleLower=searchModule.toLocaleLowerCase(),module=app.lang.getModuleName(searchModule,{defaultValue:searchModuleLower});return app.lang.get('LBL_SEARCH_SELECT_MODULE',this.module,{module:new Handlebars.SafeString(module)});},getFilterOptions:function(force){if(this._filterOptions&&!force){return this._filterOptions;}
this._filterOptions=new app.utils.FilterOptions().config(this.def).setInitialFilter(this.def.initial_filter||'$relate').populateRelate(this.model).format();return this._filterOptions;},buildFilterDefinition:function(searchTerm){if(!app.metadata.getModule('Filters')||!this.filters){return[];}
var filterBeanClass=app.data.getBeanClass('Filters').prototype,filterOptions=this.getFilterOptions()||{},filter=this.filters.collection.get(filterOptions.initial_filter),filterDef,populate,searchTermFilter,searchModule;if(filter){populate=filter.get('is_template')&&filterOptions.filter_populate;filterDef=filterBeanClass.populateFilterDefinition(filter.get('filter_definition')||{},populate);searchModule=filter.moduleName;}
searchTermFilter=filterBeanClass.buildSearchTermFilter(searchModule||this.getSearchModule(),searchTerm);return filterBeanClass.combineFilterDefinitions(filterDef,searchTermFilter);},search:_.debounce(function(query){var term=query.term||'',self=this,searchCollection,searchModule=this.getSearchModule(),params={},limit=self.def.limit||5,relatedModuleField=this.getRelatedModuleField();searchCollection=query.context||app.data.createBeanCollection(searchModule);if(query.context){params.offset=searchCollection.next_offset;}
params.filter=self.buildFilterDefinition(term);searchCollection.fetch({showAlerts:false,update:true,remove:_.isUndefined(params.offset),fields:this.getSearchFields(),context:self,params:params,limit:limit,success:function(data){var fetch={results:[],more:data.next_offset>0,context:searchCollection};if(fetch.more){var fieldEl=self.$(self.fieldTag),plugin=(fieldEl.length>1)?$(fieldEl.get(self.currentIndex)).data("select2"):fieldEl.data("select2"),height=plugin.searchmore.children("li:first").children(":first").outerHeight(),maxHeight=height*(limit-.2);plugin.results.css("max-height",maxHeight);}
_.each(data.models,function(model,index){if(params.offset&&index<params.offset){return;}
fetch.results.push({id:model.id,text:model.get(relatedModuleField)+''});});query.callback(fetch);},error:function(){query.callback({results:[]});app.logger.error("Unable to fetch the bean collection.");}});},app.config.requiredElapsed||500),bindDataChange:function(){if(this.model){this.model.on('change',function(){this.getFilterOptions(true);},this);this.model.on('change:'+this.name,function(){var $dropdown=this.$(this.fieldTag);if(!_.isEmpty($dropdown.data('select2'))){$dropdown.select2('val',this.model.get(this.name));}
if(!this.disposed){this.render();}},this);}},unbindDom:function(){this.$(this.fieldTag).select2('destroy');app.view.Field.prototype.unbindDom.call(this);}})