/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'ActiondropdownField',initialize:function(options){this._super('initialize',[options]);this.events=_.extend({},this.events,{'click [data-check=all]':'checkAll','click [data-check=one]':'check'});this.def.no_default_action=true;this.def.css_class=this.def.css_class+' actionmenu';this.fieldTag='input[type=checkbox]';this.massCollection=this.context.get('mass_collection');this.def.disable_select_all_alert=!!this.def.disable_select_all_alert;if(this.options.viewName==='list-header'){this.isCheckAllCheckbox=true;}
if(this.isCheckAllCheckbox){app.shortcuts.register('SelectAll:Checkbox','ctrl+a',function(){if(!this.isDisabled()){this.$('[data-check=all]:visible').click();}},this);app.shortcuts.register('SelectAll:Dropdown','m',function(){var $dropdown=this.$(this.actionDropDownTag);if($dropdown.is(':visible')&&!$dropdown.hasClass('disabled')){$dropdown.click();}},this);}},check:function(){var $checkbox=this.$(this.fieldTag);var isChecked=$checkbox.is(':checked');this.toggleSelect(isChecked);},toggleSelect:function(checked){var event=!!checked?'mass_collection:add':'mass_collection:remove';this.context.trigger(event,this.model);},checkAll:function(event){var $checkbox=this.$(this.fieldTag);if($(event.target).hasClass('checkall')||event.type==='keydown'){$checkbox.prop('checked',!$checkbox.is(':checked'));}
var isChecked=$checkbox.is(':checked');this.toggleAll(isChecked);},toggleAll:function(checked){var event=checked?'mass_collection:add:all':'mass_collection:remove:all';this.context.trigger(event,this.model);},_bindModelChangeEvents:function(){this.massCollection.on('add',function(model){if(this.model&&model.id===this.model.id){this.$(this.fieldTag).attr('checked',true);}},this);this.massCollection.on('remove',function(model){if(this.model&&model.id===this.model.id){this.$(this.fieldTag).attr('checked',false);}},this);this.massCollection.on('reset',function(){this.$(this.fieldTag).attr('checked',!!this.massCollection.get(this.model.id));},this);},_bindAllModelChangeEvents:function(){this.massCollection.on('all:checked',function(){if(this.collection.length!==0){this.$(this.fieldTag).attr('checked',true);}},this);this.massCollection.on('not:all:checked',function(){this.$(this.fieldTag).attr('checked',false);},this);this.massCollection.on('add',this._onMassCollectionAddAll,this);this.massCollection.on('remove reset',this._onMassCollectionRemoveResetAll,this);},_onMassCollectionAddAll:function(){this.setDropdownDisabled(false);if(!this.def.disable_select_all_alert){this.context.trigger('toggleSelectAllAlert');this.setButtonsDisabled(this.dropdownFields);}},_onMassCollectionRemoveResetAll:function(){var massCollectionIds=_.pluck(this.massCollection.models,'id');var viewCollectionIds=_.pluck(this.collection.models,'id');if(this.massCollection.length===0){this.setDropdownDisabled(true);}else if(_.intersection(massCollectionIds,viewCollectionIds).length!==0){this.setDropdownDisabled(false);this.$(this.fieldTag).attr('checked',true);}
if(!this.def.disable_select_all_alert){this.context.trigger('toggleSelectAllAlert');this.setButtonsDisabled(this.dropdownFields);}},bindDataChange:function(){if(this.isCheckAllCheckbox){this._bindAllModelChangeEvents();this.action_enabled=this.massCollection.length>0;}else{this._bindModelChangeEvents();}
this.massCollection.on('massupdate:estimate',this.onTotalEstimate,this);},setButtonsDisabled:function(fields){_.each(fields,function(field){if(field.def.minSelection||field.def.maxSelection){var min=field.def.minSelection||0,max=field.def.maxSelection||this.massCollection.length;if(this.massCollection.length<min||this.massCollection.length>max){field.setDisabled(true);}else{field.setDisabled(false);}}},this);},_loadTemplate:function(){this._super('_loadTemplate');if(this.view.action==='list'&&this.action==='edit'){this.template=app.template.empty;}},_render:function(){if(!this.isCheckAllCheckbox){if(this.massCollection.get(this.model.id)){this.selected=true;}else{delete this.selected;}}
this._super('_render');if(this.isCheckAllCheckbox&&!this.def.disable_select_all_alert){this.setButtonsDisabled(this.dropdownFields);this.setDropdownDisabled(this.massCollection.length===0);}},_renderFields:$.noop,onTotalEstimate:function(){this.setDropdownDisabled(!this.massCollection.fetched);},setDropdownDisabled:function(disable){this.$(this.actionDropDownTag).toggleClass('disabled',disable);},_getChildFieldsMeta:function(){if(this.model.id){return;}
return this._super('_getChildFieldsMeta');},unbindData:function(){if(this.massCollection){var modelId=this.model.cid,cid=this.view.cid;this.massCollection.off(null,null,this);if(modelId){this.massCollection.off(null,null,modelId);}
if(cid){this.massCollection.off(null,null,cid);}}
this._super('unbindData');}})