/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({moduleLangObj:undefined,configMetadataOK:false,accessUserOK:false,accessModuleOK:false,accessConfigOK:false,initialize:function(options){this._super('initialize',[options]);Object.defineProperty(this,'currentModule',{get:function(){app.logger.warn('ConfigDrawerLayout\'s `currentModule` property is deprecated since 7.7.0 and will be removed in 7.8.0. '+'Please use `module` instead.');return this.module;}});this.moduleLangObj={module:this.module};if(this.checkAccess()){var ctxModel=options.context.get('model'),metadata=app.metadata.getModule(this.module);ctxModel.clear({silent:true});if(_.has(metadata,'config')){ctxModel.set(metadata.config);}
this.loadConfig(options);}},_render:function(){if(this.checkAccess()){this._super('_render');}else{this.blockModule();}},loadConfig:function(options){this._super('loadData');},checkAccess:function(){this.configMetadataOK=this._checkConfigMetadata();this.accessUserOK=this._checkUserAccess();this.accessModuleOK=this._checkModuleAccess();this.accessConfigOK=this._checkModuleConfig();return(this.configMetadataOK&&this.accessUserOK&&this.accessModuleOK&&this.accessConfigOK);},_checkConfigMetadata:function(){return!_.isEmpty(app.metadata.getModule(this.module,'config'));},_checkUserAccess:function(){return!_.has(app.user.getAcls()[this.module],'access');},_checkModuleAccess:function(){return true;},_checkModuleConfig:function(){return true;},blockModule:function(){var title=app.lang.get('LBL_CONFIG_BLOCKED_TITLE',this.module,this.moduleLangObj),msg;if(!this.configMetadataOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_NO_CONFIG_METADATA',this.module,this.moduleLangObj);}else if(!this.accessUserOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_USER_ACCESS',this.module,this.moduleLangObj);}else if(!this.accessModuleOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_MODULE_ACCESS',this.module,this.moduleLangObj);}else if(!this.accessConfigOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_CONFIG_ACCESS',this.module,this.moduleLangObj);}
this.displayNoAccessAlert(title,msg);},displayNoAccessAlert:function(title,msg){var alert=app.alert.show('no_access_to_module_'+this.module,{level:'error',title:title,messages:[msg]});var $close=alert.getCloseSelector();$close.on('click',function(){$close.off();app.router.navigate('#Home',{trigger:true});});app.accessibility.run($close,'click');app.drawer.close(this.context,this.module);},loadData:function(){}})