/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({jsTree:{},reporteesEndpoint:'',currentTreeUrl:'',currentRootId:'',selectedUser:{},initHasSelected:false,previousUserName:undefined,initialize:function(options){app.view.Field.prototype.initialize.call(this,options);this.reporteesEndpoint=app.api.buildURL("Forecasts/reportees")+'/';this.selectedUser=this.context.get('selectedUser')||app.user.toJSON();this.currentTreeUrl=this.reporteesEndpoint+this.selectedUser.id;this.currentRootId=this.selectedUser.id;},_dispose:function(){if(app.user.get('is_manager')&&!_.isEmpty(this.jsTree)){this.jsTree.off();}
app.view.Field.prototype._dispose.call(this);},render:function(){if(app.user.get('is_manager')){app.view.Field.prototype.render.call(this);}},unbindData:function(){app.view.Field.prototype.unbindData.call(this);},bindDataChange:function(){this.context.on("forecasts:user:canceled",function(){this.initHasSelected=false;this.selectJSTreeNode(this.previousUserName);this.initHasSelected=true;},this);},checkRender:function(context,selectedUser){this.selectedUser=selectedUser;if(selectedUser.showOpps){var nodeId=(selectedUser.is_manager?'jstree_node_myopps_':'jstree_node_')+selectedUser.user_name;this.selectJSTreeNode(nodeId)}else if(this.currentRootId!=selectedUser.id){if(selectedUser.is_manager){this.currentRootId=selectedUser.id;this.currentTreeUrl=this.reporteesEndpoint+selectedUser.id;this.rendered=false;if(!this.disposed){this.render();}}else{var nodeId='jstree_node_'+selectedUser.user_name;if(this.jsTree.jstree('get_selected').attr('id')!=nodeId){this.selectJSTreeNode(nodeId)}}}},selectJSTreeNode:function(nodeId){this.jsTree.jstree('deselect_all');this.jsTree.jstree('select_node','#'+nodeId);},_recursiveReplaceHTMLChars:function(data,ctx){_.each(data,function(entry,index){if(entry.data){data[index].data=(function(value){return value.replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#039;/gi,'\'').replace(/&quot;/gi,'"');})(entry.data);if(entry.children){_.each(entry.children,function(childEntry,index2){entry.children[index2]=ctx._recursiveReplaceHTMLChars([childEntry]);if(childEntry.attr.rel=='my_opportunities'&&childEntry.metadata.id==app.user.get('id')){childEntry.data=app.utils.formatString(app.lang.get('LBL_MY_MANAGER_LINE','Forecasts'),[childEntry.data]);}},this);}}},this);return data;},_render:function(ctx,options){app.view.Field.prototype._render.call(this,ctx,options);var options={};options.success=_.bind(function(data){this.createTree(data);},this);app.api.call('read',this.currentTreeUrl,null,options);},createTree:function(data){if(!_.isArray(data)){data=[data];}
var treeData=this._recursiveReplaceHTMLChars(data,this),selectedUser=this.context.get('selectedUser'),nodeId=(selectedUser.is_manager&&selectedUser.showOpps?'jstree_node_myopps_':'jstree_node_')+selectedUser.user_name;treeData.ctx=this.context;this.jsTree=$(".jstree-sugar").jstree({"plugins":["json_data","ui","crrm","types","themes"],"json_data":{"data":treeData},"ui":{"initially_select":[nodeId]},"types":{"types":{"types":{"parent_link":{},"manager":{},"my_opportunities":{},"rep":{},"root":{}}}}}).on("reselect.jstree",_.bind(function(){this.initHasSelected=true;},this)).on("select_node.jstree",_.bind(function(event,data){if(this.initHasSelected){this.previousUserName=(this.selectedUser.is_manager&&this.selectedUser.showOpps?'jstree_node_myopps_':'jstree_node_')+this.selectedUser.user_name;var jsData=data.inst.get_json(),nodeType=jsData[0].attr.rel,userData=jsData[0].metadata,showOpps=false;if(nodeType=="my_opportunities"||nodeType=="rep"){showOpps=true}
var selectedUser={'id':userData.id,'user_name':userData.user_name,'full_name':userData.full_name,'first_name':userData.first_name,'last_name':userData.last_name,'reports_to_id':userData.reports_to_id,'reports_to_name':userData.reports_to_name,'is_manager':(nodeType!='rep'),'is_top_level_manager':(nodeType!='rep'&&_.isEmpty(userData.reports_to_id)),'showOpps':showOpps,'reportees':[]};this.context.trigger('forecasts:user:changed',selectedUser,this.context);}},this));if(treeData){var rootId=-1;if(treeData.length==1){rootId=treeData[0].metadata.id;}else if(treeData.length==2){rootId=treeData[1].metadata.id;}
this.currentRootId=rootId;}
this.$el.find('#people').addClass("jstree-sugar");}})