/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({currentModule:undefined,moduleLangObj:undefined,configMetadataOK:false,accessUserOK:false,accessModuleOK:false,accessConfigOK:false,initialize:function(options){this.currentModule=app.controller.context.get('module');this.moduleLangObj={module:this.currentModule};if(this.checkAccess()){var ctxModel=options.context.get('model'),metadata=app.metadata.getModule(this.currentModule);ctxModel.clear({silent:true});if(_.has(metadata,'config')){ctxModel.set(metadata.config);}
this.loadConfig(options);}else{this.blockModule()}},loadConfig:function(options){this._super('initialize',[options]);this._super('loadData');},checkAccess:function(){this.configMetadataOK=this._checkConfigMetadata();this.accessUserOK=this._checkUserAccess();this.accessModuleOK=this._checkModuleAccess();this.accessConfigOK=this._checkModuleConfig();return(this.configMetadataOK&&this.accessUserOK&&this.accessModuleOK&&this.accessConfigOK);},_checkConfigMetadata:function(){return!_.isEmpty(app.metadata.getModule(this.currentModule,'config'));},_checkUserAccess:function(){return!_.has(app.user.getAcls()[this.currentModule],'access');},_checkModuleAccess:function(){return true;},_checkModuleConfig:function(){return true;},blockModule:function(){var title=app.lang.get('LBL_CONFIG_BLOCKED_TITLE',this.currentModule,this.moduleLangObj),msg;if(!this.configMetadataOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_NO_CONFIG_METADATA',this.currentModule,this.moduleLangObj);}else if(!this.accessUserOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_USER_ACCESS',this.currentModule,this.moduleLangObj);}else if(!this.accessModuleOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_MODULE_ACCESS',this.currentModule,this.moduleLangObj);}else if(!this.accessConfigOK){msg=app.lang.get('LBL_CONFIG_BLOCKED_DESC_CONFIG_ACCESS',this.currentModule,this.moduleLangObj);}
this.displayNoAccessAlert(title,msg);},displayNoAccessAlert:function(title,msg){var alert=app.alert.show('no_access_to_module_'+this.currentModule,{level:'error',title:title,messages:[msg]});var $close=alert.getCloseSelector();$close.on('click',function(){$close.off();app.router.navigate('#Home',{trigger:true});});app.accessibility.run($close,'click');},loadData:function(){}})