/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({plugins:['Dashlet','RelativeTime','ToggleVisibility','Tooltip','Pagination'],events:{'click [data-action=show-more]':'showMore','click [data-action=tab-switcher]':'tabSwitcher'},_defaultSettings:{},initDashlet:function(){this._initSettings();if(this.meta.config){return;}
this.collection=new Backbone.Collection();this.context=this.context.getChildContext({forceNew:true,model:this.context.parent&&this.context.parent.get('model'),collection:this.collection,name:'tabbed-dashlet'});this.context.set('parentModule',this.module);this._initMaxHeightTarget();this._initEvents();this._initTabs();this._initTemplates();},_initMaxHeightTarget:function(){this.maxHeightTarget=this.meta.max_height_target||'div.tab-content';return this;},_initEvents:function(){this.settings.on('change:filter',this.loadData,this);this.on('tabbed-dashlet:unlink-record:fire',this.unlinkRecord,this);this.context.on('tabbed-dashlet:refresh',this.refreshTabsForModule,this);this.context.on('change:collection',this.onCollectionChange,this);return this;},_initTabs:function(){this.tabs=[];_.each(this.dashletConfig.tabs,function(tab,index){if(tab.active){this.settings.set('activeTab',index);}
var collection=this._createCollection(tab);if(_.isNull(collection)){return;}
collection.on('add',this.bindCollectionAdd,this);collection.on('reset',this.bindCollectionReset,this);this.tabs[index]=tab;this.tabs[index].collection=collection;this.tabs[index].relate=_.isObject(collection.link);this.tabs[index].record_date=tab.record_date||'date_entered';this.tabs[index].include_child_items=tab.include_child_items||false;},this);return this;},_initTemplates:function(){this._tabsTpl=app.template.getView(this.name+'.tabs',this.module)||app.template.getView(this.name+'.tabs')||app.template.getView('tabbed-dashlet.tabs',this.module)||app.template.getView('tabbed-dashlet.tabs');this._toolbarTpl=app.template.getView(this.name+'.toolbar',this.module)||app.template.getView(this.name+'.toolbar')||app.template.getView('tabbed-dashlet.toolbar',this.module)||app.template.getView('tabbed-dashlet.toolbar');return this;},_initSettings:function(){var settings=_.extend({},this._defaultSettings,this.settings.attributes);this.settings.set(settings);return this;},bindCollectionAdd:function(model){var tab=this._getTab(model.collection);model.set('record_date',model.get(tab.record_date));},bindCollectionReset:function(collection){_.each(collection.models,this.bindCollectionAdd,this);},onCollectionChange:function(){var prevCollection=this.context.previous('collection');if(prevCollection){prevCollection.off(null,this.updateCollectionCount,this);}
this.collection=this.context.get('collection');this.collection.on('add remove reset',_.debounce(this.updateCollectionCount,100),this);},updateCollectionCount:function(){var tabIndex=this.settings.get('activeTab'),count=this.collection.length;if(this.collection.next_offset>=0){count+='+';}
this.$('[data-action=tab-switcher][data-index='+tabIndex+']').children('[data-action=count]').text(count);},_getRecordsTemplate:function(module){this._recordsTpl=this._recordsTpl||{};if(!this._recordsTpl[module]){this._recordsTpl[module]=app.template.getView(this.name+'.records',module)||app.template.getView(this.name+'.records',this.module)||app.template.getView(this.name+'.records')||app.template.getView('tabbed-dashlet.records',this.module)||app.template.getView('tabbed-dashlet.records');}
return this._recordsTpl[module];},_createCollection:function(tab){if(this.context.parent){var module=this.context.parent.get('module');}else{var module=this.module;}
var meta=app.metadata.getModule(module);if(_.isUndefined(meta)){return null;}
var options={};if(meta.fields[tab.link]&&meta.fields[tab.link].type==='link'){options={link:{name:tab.link,bean:this.model}};}
var collection=app.data.createBeanCollection(tab.module,null,options);return collection;},_getCollectionOptions:function(index){var tab=this.tabs[index],options={limit:this.settings.get('limit'),offset:0,params:{order_by:tab.order_by||null,include_child_items:tab.include_child_items||null},fields:tab.fields||null};if(tab.module!='Meetings'&&tab.module!='Calls'){options.myItems=this.getVisibility()==='user';}
return options;},_getCollectionFilters:function(index){var tab=this.tabs[index],filters=[];_.each(tab.filters,function(condition,field){var filter={};filter[field]=condition;filters.push(filter);});if((tab.module==='Meetings'||tab.module==='Calls')&&this.getVisibility()==='user'){filters.push({"$or":[{"assigned_user_id":app.user.id},{"users.id":app.user.id}]});}
return filters;},_getTab:function(collection){return _.find(this.tabs,function(tab){return tab.collection===collection;},this);},_getFilters:function(index){return[];},loadData:function(options){if(this.disposed||this.meta.config){return;}
this.loadDataForTabs(this.tabs,options);},refreshTabsForModule:function(module){var toRefresh=[];_.each(this.tabs,function(tab){if(tab.module===module){toRefresh.push(tab);}});this.loadDataForTabs(toRefresh,{});},loadDataForTabs:function(tabs,options){options=options||{};var self=this;var loadDataRequests=[];_.each(tabs,function(tab,index){loadDataRequests.push(function(callback){tab.collection.options=self._getCollectionOptions(index);tab.collection.filterDef=_.union(self._getCollectionFilters(index),self._getFilters(index));tab.collection.fetch({relate:tab.relate,complete:function(){tab.collection.dataFetched=true;callback(null);}});});},this);if(!_.isEmpty(loadDataRequests)){async.parallel(loadDataRequests,function(){if(self.disposed){return;}
self.collection=self.tabs[self.settings.get('activeTab')].collection;self.context.set('collection',self.collection);self.render();if(_.isFunction(options.complete)){options.complete.call(self);}});}},_getRemoveModelCompleteCallback:function(){return _.bind(function(model){if(this.disposed){return;}
this.collection.remove(model);this.render();this.context.trigger("tabbed-dashlet:refresh",model.module);},this);},showMore:function(){this.getNextPagination({showAlerts:true,limit:this.settings.get('limit')});},tabSwitcher:function(event){var index=this.$(event.currentTarget).data('index');if(index===this.settings.get('activeTab')){return;}
this.settings.set('activeTab',index);this.collection=this.tabs[index].collection;this.context.set('collection',this.collection);this.render();},unlinkRecord:function(model){var self=this;var name=Handlebars.Utils.escapeExpression(app.utils.getRecordName(model)).trim();var context=app.lang.getModuleName(model.module).toLowerCase()+' '+name;app.alert.show(model.get('id')+':unlink_confirmation',{level:'confirmation',messages:app.utils.formatString(app.lang.get('NTC_UNLINK_CONFIRMATION_FORMATTED'),[context]),onConfirm:function(){model.destroy({showAlerts:true,relate:true,success:self._getRemoveModelCompleteCallback()});}});},_renderHtml:function(){if(this.meta.config){this._super('_renderHtml');return;}
var tab=this.tabs[this.settings.get('activeTab')];var recordsTpl=this._getRecordsTemplate(tab.module);this.toolbarHtml=this._toolbarTpl(this);this.tabsHtml=this._tabsTpl(this);this.recordsHtml=recordsTpl(this);this.row_actions=tab.row_actions;this._super('_renderHtml');},_renderAvatars:function(){this.$('img.avatar').load(function(){$(this).removeClass('hide');}).error(function(){$(this).parent().removeClass('avatar avatar-md').addClass('label label-module label-module-md label-Users');$(this).parent().find('span').removeClass('hide');});this.$('img.avatar').each(function(){var img=$(this);img.attr('src',img.data('src'));});},_dispose:function(){_.each(this.tabs,function(tab){tab.collection.off(null,null,this);});this._super('_dispose');}})