<?php

 /*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Trackers/Dashlets/TrackerDashlet/TrackerDashlet.tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dashletStrings = array ( 
   'TrackerDashlet' => array (
      'LBL_TITLE' => 'Takip Raporları' ,
      'LBL_DESCRIPTION' => 'Takip verileri üstünde sorgular çalıştırmaya yarayan bir dashlet' ,
      'LBL_SAVING' => 'Sorgu Çalıştırılıyor ...' ,
      'LBL_SAVED' => 'Sorgu Tamamlandı' ,
      'LBL_CLEAR' => 'Temizle' ,
      'LBL_CLEAR_TOOLTIP' => 'Tarih alanındaki bilgiyi temizler' ,
      'LBL_CONFIGURE_TITLE' => 'Başlık' ,
      'LBL_CONFIGURE_HEIGHT' => 'Yüksekliği (1-300)' ,
      'LBL_SELECT_QUERY' => 'Sorgu Seç...' ,
      'LBL_FILTER' => 'Filtre' ,
      'LBL_FILTER_TOOLTIP' => 'Tarih alanındaki bilgiye göre filtreler' ,
      'LBL_SINCE' => '-Ten Beri:' ,
      'LBL_CHOOSE_DATE_TOOLTIP' => 'Seçilen raporlar için bir tarih filtresi belirtilebilirsiniz. Girilen tarih bilgisi, raporda varsayılan tarih bilgisinin yerine geçecektir. Örneğin  "Aktivitelerim (Bu hafta)" raporunda, varsayılan tarih aralığı olan bir hafta yerine, belirtilen filtre tarih bilgisinden sonra olan tüm kayıtlar görüntülenir.'   ));

?>
