/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({_moduleFilterList:[],_allModulesId:'All',_selectedModule:null,_currentSearch:'',events:{'keyup .search-name':'throttledSearch','paste .search-name':'throttledSearch','click .add-on.fa-times':'clearInput'},processStatus:[app.lang.get('LBL_STATUS_COMPLETED',this.module),app.lang.get('LBL_STATUS_TERMINATED',this.module),app.lang.get('LBL_STATUS_IN_PROGRESS',this.module),app.lang.get('LBL_STATUS_CANCELLED',this.module),app.lang.get('LBL_STATUS_ERROR',this.module)],_render:function(){app.view.View.prototype._render.call(this);this.buildModuleFilterList();this.buildFilter();},buildModuleFilterList:function(){var allowedModules=this.collection.allowed_modules;this._moduleFilterList=[{id:this._allModulesId,text:app.lang.get('LBL_MODULE_ALL')}];_.each(allowedModules,function(module){this._moduleFilterList.push({id:module,text:module});},this);},buildFilter:function(){var $filter=this.getFilterField();if($filter.length>0){$filter.select2({data:this._moduleFilterList,allowClear:false,multiple:false,minimumResultsForSearch:-1,formatSelection:_.bind(this.formatModuleSelection,this),formatResult:_.bind(this.formatModuleChoice,this),dropdownCss:{width:'auto'},dropdownCssClass:'search-filter-dropdown',initSelection:_.bind(this.initSelection,this),escapeMarkup:function(m){return m;},width:'off'});$filter.off('change');$filter.on('change',_.bind(this.handleModuleSelection,this));this._selectedModule=this._selectedModule||this._allModulesId;$filter.select2('val',this._selectedModule);}},getFilterField:function(){return this.$('input.select2');},getModuleFilter:function(){return this.$('div.choice-filter');},unbind:function(){$filter=this.getFilterField();if($filter.length>0){$filter.off();$filter.select2('destroy');}
this._super("unbind");},throttledSearch:_.debounce(function(evt){var newSearch=this.$(evt.currentTarget).val();if(this._currentSearch!==newSearch&&_.indexOf(this.processStatus,this._selectedModule)==-1){this._currentSearch=newSearch;this.applyFilter();}},400),initSelection:function(el,callback){if(el.is(this.getFilterField())){var module=_.findWhere(this._moduleFilterList,{id:el.val()});callback({id:module.id,text:module.text});}},formatModuleSelection:function(item){this.getModuleFilter().html(item.text);return'<span class="select2-choice-type">'
+app.lang.get('LBL_PMSE_FILTER',this.module)
+'<i class="fa fa-caret-down"></i></span>';},formatModuleChoice:function(option){return'<div><span class="select2-match"></span>'+option.text+'</div>';},handleModuleSelection:function(evt,overrideVal){var module=overrideVal||evt.val||this._selectedModule||this._allModulesId;if(!_.isEmpty(_.findWhere(this._moduleFilterList,{id:module}))){this._selectedModule=module;this.getFilterField().select2('val',this._selectedModule);this.getModuleFilter().css('cursor','pointer');this.applyFilter();}},applyFilter:function(){var searchAllModules=(this._selectedModule===this._allModulesId),module=searchAllModules?[]:[this._selectedModule],isDirty=!_.isEmpty(this._currentSearch);this._toggleClearQuickSearchIcon(isDirty);this.context.trigger('compose:addressbook:search',module,this._currentSearch);},_toggleClearQuickSearchIcon:function(addIt){if(addIt&&!this.$('.add-on.fa-times')[0]){this.$('.filter-view.search').append('<i class="add-on fa fa-times"></i>');}else if(!addIt){this.$('.add-on.fa-times').remove();}},clearInput:function(){var $filter=this.getFilterField();this._currentSearch='';this._selectedModule=this._allModulesId;this.$('.search-name').val(this._currentSearch);if($filter.length>0){$filter.select2('val',this._selectedModule);}
this.applyFilter();}})