nv.models.funnel=function(){var margin={top:0,right:0,bottom:0,left:0},width=960,height=500,r=0.3,y=d3.scale.linear(),id=Math.floor(Math.random()*10000),getX=function(d){return d.x;},getY=function(d){return d.y;},getH=function(d){return d.height;},getV=function(d){return d.value;},forceY=[0],clipEdge=true,yDomain,delay=0,wrapLabels=true,minLabelWidth=75,durationMs=0,fmtValueLabel=function(d){return d.label||d.value||d;},color=function(d,i){return nv.utils.defaultColor()(d,d.series);},fill=color,classes=function(d,i){return'nv-group nv-series-'+d.series;},dispatch=d3.dispatch('chartClick','elementClick','elementDblClick','elementMouseover','elementMouseout','elementMousemove');var calculatedWidth=0,calculatedHeight=0,calculatedCenter=0;function chart(selection){selection.each(function(data){var availableWidth=width-margin.left-margin.right,availableHeight=height-margin.top-margin.bottom,container=d3.select(this),labelGap=5,labelSpace=5,labelOffset=0,funnelTotal=0,funnelOffset=0;data.map(function(series,i){series.values=series.values.map(function(point){point.series=i;if(typeof point.value=='undefined'){point.value=getY(point);}
funnelTotal+=parseFloat(point.value);return point;});return series;});function calcDimensions(){calculatedWidth=calcWidth(funnelOffset);calculatedHeight=calcHeight();calculatedCenter=calcCenter(funnelOffset);}
function calcScales(){var funnelArea=areaTrapezoid(calculatedHeight,calculatedWidth),funnelBase=calculatedWidth-2*r*calculatedHeight,funnelShift=0,funnelMinHeight=24;data.map(function(series,i){series.values=series.values.map(function(point){point.height=0;if(funnelTotal>0){point.height=heightTrapezoid(funnelArea*point.value / funnelTotal,funnelBase);}
if(point.height<funnelMinHeight / 2){funnelShift+=point.height-funnelMinHeight / 2;point.height=funnelMinHeight / 2;}else if(funnelShift<0&&point.height+funnelShift>funnelMinHeight / 2){point.height+=funnelShift;funnelShift=0;}
funnelBase+=2*r*point.height;return point;});return series;});data=d3.layout.stack().offset('zero').values(function(d){return d.values;}).y(getH)(data);var seriesData=(yDomain)?[]:d3.extent(d3.merge(data.map(function(d){return d.values.map(function(d,i){return getH(d,i)+d.y0;});})).concat(forceY));y.domain(yDomain||seriesData).range([calculatedHeight,0]);}
calcDimensions();calcScales();var wrap=container.selectAll('g.nv-wrap.nv-funnel').data([data]);var wrapEnter=wrap.enter().append('g').attr('class','nvd3 nv-wrap nv-funnel');var defsEnter=wrapEnter.append('defs');var gEnter=wrapEnter.append('g');var g=wrap.select('g');chart.gradient=function(d,i,p){return nv.utils.colorLinearGradient(d,id+'-'+i,p,color(d,i),wrap.select('defs'));};gEnter.append('g').attr('class','nv-groups');wrap.attr('transform','translate('+margin.left+','+margin.top+')');defsEnter.append('clipPath').attr('id','nv-edge-clip-'+id).append('rect');wrap.select('#nv-edge-clip-'+id+' rect').attr('width',availableWidth+1).attr('height',availableHeight+1);g.attr('clip-path',clipEdge?'url(#nv-edge-clip-'+id+')':'');var groups=wrap.select('.nv-groups').selectAll('.nv-group').data(function(d){return d;},function(d){return d.key;});groups.enter().append('g').style('stroke-opacity',1e-6).style('fill-opacity',1e-6);groups.attr('class',classes).attr('fill',fill).classed('hover',function(d){return d.hover;}).classed('nv-active',function(d){return d.active==='active';}).classed('nv-inactive',function(d){return d.active==='inactive';}).style({'stroke':'#FFFFFF','stroke-width':2});groups.transition().duration(durationMs).style('stroke-opacity',1).style('fill-opacity',1);groups.exit().transition().duration(durationMs).selectAll('polygon.nv-bar').delay(function(d,i){return i*delay / data[0].values.length;}).attr('points',function(d){return pointsTrapezoid(d,0,calculatedWidth);}).style('stroke-opacity',1e-6).style('fill-opacity',1e-6).remove();groups.exit().transition().duration(durationMs).selectAll('g.nv-label-value').delay(function(d,i){return i*delay / data[0].values.length;}).attr('y',0).attr('transform','translate('+calculatedCenter+',0)').style('stroke-opacity',1e-6).style('fill-opacity',1e-6).remove();var funs=groups.selectAll('polygon.nv-bar').data(function(d){return d.values;});funs.exit().remove();funs.enter().append('polygon').attr('class','nv-bar').attr('points',function(d){return pointsTrapezoid(d,0,calculatedWidth);}).on('mouseover',function(d,i){d3.select(this).classed('hover',true);var eo=buildEventObject(d3.event,d,i);dispatch.elementMouseover(eo);}).on('mousemove',function(d,i){dispatch.elementMousemove(d3.event);}).on('mouseout',function(d,i){d3.select(this).classed('hover',false);dispatch.elementMouseout();}).on('click',function(d,i){d3.event.stopPropagation();var eo=buildEventObject(d3.event,d,i);dispatch.elementClick(eo);}).on('dblclick',function(d,i){d3.event.stopPropagation();var eo=buildEventObject(d3.event,d,i);dispatch.elementDblClick(eo);});function buildEventObject(e,d,i){return{value:getV(d,i),point:d,id:id,series:data[d.series],pointIndex:i,seriesIndex:d.series,e:e};}
var labels=groups.selectAll('.nv-label-value').data(function(d){return d.values;});labels.enter().append('g').attr('class','nv-label-value').attr('transform','translate('+calculatedCenter+',0)');var sideLabels=labels.filter('.nv-label-side');function renderFunnelLabels(){labels.selectAll('text').remove();labels.append('text').text(fmtKey).call(fmtLabel,'nv-label',0.85,'11px','middle',fmtFill);labels.select('.nv-label').call(handleLabel,(wrapLabels?wrapLabel:ellipsifyLabel),calcFunnelWidthAtSliceMidpoint,function(txt,dy){fmtLabel(txt,'nv-label',dy,'11px','middle',fmtFill);});labels.append('text').text(fmtValueLabel).call(fmtLabel,'nv-value',0.85,'15px','middle',fmtFill);labels.select('.nv-value').append('tspan').text(fmtCount);labels.call(positionValue);labels.call(calcFunnelLabelDimensions);labels.classed('nv-label-side',function(d){return d.tooTall||d.tooWide;});}
function renderSideLabels(){sideLabels=labels.filter('.nv-label-side');labels.selectAll('polyline').remove();sideLabels.selectAll('.nv-label').remove();sideLabels.append('text').text(fmtKey).call(fmtLabel,'nv-label',0.85,'11px','start','#555');sideLabels.select('.nv-label').call(handleLabel,(wrapLabels?wrapLabel:ellipsifyLabel),(wrapLabels?calcSideWidth:maxSideLabelWidth),function(txt,dy){fmtLabel(txt,'nv-label',dy,'11px','start','#555');});sideLabels.call(positionValue);sideLabels.select('.nv-value').style({'font-size':'15px','text-anchor':'start','fill':'#555'});sideLabels.call(calcSideLabelDimensions);var d0=0;sideLabels.reverse().each(function(d,i){if(!d0){d.labelBottom=d.labelTop+d.labelHeight+labelSpace;d0=d.labelBottom;return;}
d.labelTop=Math.max(d0,d.labelTop);d.labelBottom=d.labelTop+d.labelHeight+labelSpace;d0=d.labelBottom;});sideLabels.reverse();if(d0&&d0-labelSpace>d3.max(y.range())){d0=0;sideLabels.each(function(d,i){if(!d0){d.labelBottom=d3.max(y.range())-1;d.labelTop=d.labelBottom-d.labelHeight;d0=d.labelTop;return;}
d.labelBottom=Math.min(d0,d.labelBottom);d.labelTop=d.labelBottom-d.labelHeight-labelSpace;d0=d.labelTop;});if(d0<0){sideLabels.each(function(d,i){d.labelTop-=d0;d.labelBottom-=d0;});}}
d0=0;sideLabels.call(calcOffsets);}
function renderLabels(){renderFunnelLabels();renderSideLabels();}
renderLabels();calcDimensions();calcScales();renderLabels();calcDimensions();calcScales();renderLabels();calcDimensions();funs.attr('points',function(d){var scalar=d.active&&d.active==='active'?1.05:1;return pointsTrapezoid(d,1,calculatedWidth*scalar);});labels.attr('transform',function(d){var xTrans=d.tooTall?0:calculatedCenter,yTrans=d.tooTall?0:d.labelTop;return'translate('+xTrans+','+yTrans+')';});sideLabels.attr('transform',function(d){return'translate('+labelOffset+','+d.labelTop+')';});sideLabels.append('polyline').attr('class','nv-label-leader').style({'fill-opacity':0,'stroke':'#999','stroke-width':1,'stroke-opacity':0.5});sideLabels.reverse();sideLabels.selectAll('polyline').call(pointsLeader);sideLabels.reverse();function wrapLabel(d,lbl,fnWidth,fmtLabel){var text=lbl.text(),dy=parseFloat(lbl.attr('dy')),word,words=text.split(/\s+/).reverse(),line=[],lineNumber=0,maxWidth=fnWidth(d,0),parent=d3.select(lbl.node().parentNode);lbl.text(null);while(word=words.pop()){line.push(word);lbl.text(line.join(' '));if(lbl.node().getComputedTextLength()>maxWidth&&line.length>1){line.pop();lbl.text(line.join(' '));line=[word];lbl=parent.append('text');lbl.text(word).call(fmtLabel,++lineNumber*1.1+dy);}}}
function handleLabel(lbls,fnFormat,fnWidth,fmtLabel){lbls.each(function(d){var lbl=d3.select(this);fnFormat(d,lbl,fnWidth,fmtLabel);});}
function ellipsifyLabel(d,lbl,fnWidth,fmtLabel){var text=lbl.text(),dy=parseFloat(lbl.attr('dy')),maxWidth=fnWidth(d);lbl.text(nv.utils.stringEllipsify(text,container,maxWidth)).call(fmtLabel,dy);}
function maxSideLabelWidth(d){var twenty=Math.max(availableWidth-availableHeight / 1.1,minLabelWidth),sliceBottom=y(d.y0),base=sliceBottom*r,maxWidth=twenty+base,leaderHeight=Math.abs(d.labelBottom-sliceBottom),leaderWidth=leaderHeight*r,leaderTotal=labelGap+leaderWidth+labelGap+labelGap,iOffset=maxWidth-leaderTotal;return Math.max(iOffset,minLabelWidth);}
function pointsTrapezoid(d,h,w){var y0=y(d.y0),y1=y(d.y0+d.y),w0=w / 2-r*y0,w1=w / 2-r*y1,c=calculatedCenter;return((c-w0)+','+(y0*h)+' '+
(c-w1)+','+(y1*h)+' '+
(c+w1)+','+(y1*h)+' '+
(c+w0)+','+(y0*h));}
function heightTrapezoid(a,b){var x=b / r / 2;return Math.abs(Math.sqrt(a / r+x*x))-x;}
function areaTrapezoid(h,w){return h*(w-h*r);}
function calcWidth(offset){return Math.round(Math.max(Math.min(availableHeight / 1.1,availableWidth-offset),40));}
function calcHeight(){return Math.min(calculatedWidth*1.1,(calculatedWidth-calculatedWidth*r)/(2*r));}
function calcCenter(offset){return calculatedWidth / 2+offset;}
function calcFunnelWidthAtSliceMidpoint(d){var b=calculatedWidth,v=y(d.y0+d.y1 / 2);return b-v*r*2;}
function calcSideWidth(d,offset){var b=Math.max((availableWidth-calculatedWidth)/ 2,offset),v=y(d.y0+d.y1);return b+v*r;}
function calcLabelBBox(lbl){return d3.select(lbl).node().getBoundingClientRect();}
function calcFunnelLabelDimensions(lbls){lbls.each(function(d){var bbox=calcLabelBBox(this);d.labelHeight=bbox.height;d.labelWidth=bbox.width;d.labelTop=y(d.y0+d.y / 2)-d.labelHeight / 2;d.labelBottom=d.labelTop+d.labelHeight+labelSpace;d.y1=d.y-d.labelHeight;d.tooWide=d.labelWidth>calcFunnelWidthAtSliceMidpoint(d);d.tooTall=d.labelHeight>d.height-4;});}
function calcSideLabelDimensions(lbls){lbls.each(function(d){var bbox=calcLabelBBox(this);d.labelHeight=bbox.height;d.labelWidth=bbox.width;d.labelTop=y(d.y0+d.y);d.labelBottom=d.labelTop+d.labelHeight+labelSpace;});}
function pointsLeader(polylines,i){var c=polylines.length;polylines.each(function(d,i,j){d.y1=0;var
p=j?d3.select(polylines[j-1][i]).data()[0]:null,n=j<c-1?d3.select(polylines[j+1][i]).data()[0]:null,h=Math.round(d.labelHeight)+0.5,t=Math.round(y(d.y0)-d.labelTop)-0.5,wp=p?p.labelWidth-(d.labelBottom-p.labelBottom)*r:0,wc=d.labelWidth,wn=n&&h<t?n.labelWidth:0,w=Math.round(Math.max(wp,wc,wn))+labelGap,f=Math.round(calcSideWidth(d,funnelOffset))-labelOffset-labelGap,p=0+','+h+' '+
w+','+h+' '+
(w+Math.abs(h-t)*r)+','+t+' '+
f+','+t;d.labelWidth=w;d3.select(this).attr('points',p);});}
function calcOffsets(lbls){var sideWidth=(availableWidth-calculatedWidth)/ 2,offset=0;lbls.each(function(d){var
sliceBottom=y(d.y0),scalar=d.labelBottom>=sliceBottom?1:0,leaderSlope=Math.abs(d.labelBottom+labelGap-sliceBottom)*r,base=sliceBottom*r,iOffset=d.labelWidth+leaderSlope+labelGap*3-base;if(iOffset>=offset){offset=iOffset;}});offset=Math.round(offset*10)/ 10;if(offset<=0){labelOffset=sideWidth;funnelOffset=sideWidth;}else if(offset>0&&offset<sideWidth){labelOffset=sideWidth-offset;funnelOffset=sideWidth;}else{labelOffset=0;funnelOffset=offset;}}
function fmtFill(d,i,j){var backColor=d3.select(this.parentNode).style('fill'),textColor=nv.utils.getTextContrast(backColor,i);return textColor;}
function fmtKey(d){return data[d.series].key;}
function fmtCount(d){var i=data[d.series].count;return i?' ('+i+')':'';}
function fmtDirection(d){var m=nv.utils.isRTLChar(d.slice(-1)),dir=m?'rtl':'ltr';return'ltr';}
function fmtLabel(txt,classes,dy,fontSize,anchor,fill){txt.attr('x',0).attr('y',0).attr('dy',dy+'em').attr('class',classes).attr('direction',function(){return fmtDirection(txt.text());}).style('pointer-events','none').style('text-anchor',anchor).style('font-size',fontSize).style('fill',fill);}
function positionValue(lbls){lbls.each(function(d){var lbl=d3.select(this),cnt=lbl.selectAll('.nv-label')[0].length+1,dy=.85*cnt+'em';lbl.select('.nv-value').attr('dy',dy);});}});return chart;}
chart.dispatch=dispatch;chart.color=function(_){if(!arguments.length)return color;color=_;return chart;};chart.fill=function(_){if(!arguments.length)return fill;fill=_;return chart;};chart.classes=function(_){if(!arguments.length)return classes;classes=_;return chart;};chart.gradient=function(_){if(!arguments.length)return gradient;gradient=_;return chart;};chart.x=function(_){if(!arguments.length)return getX;getX=_;return chart;};chart.y=function(_){if(!arguments.length)return getY;getY=_;return chart;};chart.margin=function(_){if(!arguments.length)return margin;margin=_;return chart;};chart.width=function(_){if(!arguments.length)return width;width=_;return chart;};chart.height=function(_){if(!arguments.length)return height;height=_;return chart;};chart.xScale=function(_){if(!arguments.length)return x;x=_;return chart;};chart.yScale=function(_){if(!arguments.length)return y;y=_;return chart;};chart.yDomain=function(_){if(!arguments.length)return yDomain;yDomain=_;return chart;};chart.forceY=function(_){if(!arguments.length)return forceY;forceY=_;return chart;};chart.id=function(_){if(!arguments.length)return id;id=_;return chart;};chart.delay=function(_){if(!arguments.length)return delay;delay=_;return chart;};chart.clipEdge=function(_){if(!arguments.length)return clipEdge;clipEdge=_;return chart;};chart.fmtValueLabel=function(_){if(!arguments.length)return fmtValueLabel;fmtValueLabel=d3.functor(_);return chart;};chart.wrapLabels=function(_){if(!arguments.length)return wrapLabels;wrapLabels=_;return chart;};chart.minLabelWidth=function(_){if(!arguments.length)return minLabelWidth;minLabelWidth=_;return chart;};return chart;}