nv.models.multiBarChart=function(){var vertical=true,margin={top:10,right:10,bottom:10,left:10},width=null,height=null,showTitle=false,showControls=false,showLegend=true,direction='ltr',tooltip=null,tooltips=true,scrollEnabled=true,overflowHandler=function(d){return;},x,y,state={},strings={legend:{close:'Hide legend',open:'Show legend'},controls:{close:'Hide controls',open:'Show controls'},noData:'No Data Available.'},hideEmptyGroups=true,dispatch=d3.dispatch('chartClick','elementClick','tooltipShow','tooltipHide','tooltipMove','stateChange','changeState');var useScroll=false,scrollOffset=0;var multibar=nv.models.multiBar().stacked(false),xAxis=nv.models.axis().tickSize(0).tickPadding(4).highlightZero(false).showMaxMin(false).tickFormat(function(d){return d;}),yAxis=nv.models.axis().tickPadding(4).tickFormat(function(d){var si=d3.formatPrefix(d,1);return d3.round(si.scale(d),1)+si.symbol;}),legend=nv.models.legend(),controls=nv.models.legend().color(['#444']),scroll=nv.models.scroll();var tooltipContent=function(key,x,y,e,graph){return'<h3>'+key+'</h3>'+'<p>'+y+' on '+x+'</p>';};var showTooltip=function(eo,offsetElement,groupTotals){var key=eo.series.key,x=(groupTotals)?(eo.point.y*100 / groupTotals[eo.pointIndex].t).toFixed(1):xAxis.tickFormat()(multibar.x()(eo.point,eo.pointIndex)),y=yAxis.tickFormat()(multibar.y()(eo.point,eo.pointIndex)),content=tooltipContent(key,x,y,eo,chart),gravity=eo.value<0?vertical?'n':'e':vertical?'s':'w';tooltip=nv.tooltip.show(eo.e,content,gravity,null,offsetElement);};var seriesClick=function(data,e,chart){return;};function chart(selection){selection.each(function(chartData){var that=this,container=d3.select(this),className=vertical?'multibarChart':'multiBarHorizontalChart';var properties=chartData?chartData.properties:{},data=chartData?chartData.data:null;var dataBars=[],groupLabels=[],groupTotals=[],totalAmount=0,seriesCount=0,groupCount=0;chart.container=this;chart.update=function(){container.transition().call(chart);};function displayNoData(d){if(d&&d.length&&d.filter(function(d){return d.values.length;}).length){container.selectAll('.nv-noData').remove();return false;}
container.select('.nvd3.nv-wrap').remove();var w=width||parseInt(container.style('width'),10)||960,h=height||parseInt(container.style('height'),10)||400,noDataText=container.selectAll('.nv-noData').data([chart.strings().noData]);noDataText.enter().append('text').attr('class','nvd3 nv-noData').attr('dy','-.7em').style('text-anchor','middle');noDataText.attr('x',margin.left+w / 2).attr('y',margin.top+h / 2).text(function(d){return d;});return true;}
if(displayNoData(data)){return chart;}
chart.dataSeriesActivate=function(eo){var series=eo.series;series.active=(!series.active||series.active==='inactive')?'active':'inactive';series.values.map(function(d){d.active=series.active;});if(series.active==='active'){data.filter(function(d){return d.active!=='active';}).map(function(d){d.active='inactive';d.values.map(function(d){d.active='inactive';});return d;});}
if(!data.filter(function(d){return d.active==='active';}).length){data.map(function(d){d.active='';d.values.map(function(d){d.active='';});container.selectAll('.nv-series').classed('nv-inactive',false);return d;});}
container.call(chart);};showTitle=showTitle&&properties.title;var controlsData=[{key:'Grouped',disabled:state.stacked},{key:'Stacked',disabled:!state.stacked}];if(hideEmptyGroups){data.map(function(d){if(!d._values){d._values=d.values;}
return d;});}
data.map(function(d,i){d.series=i;d.total=d3.sum(d.values,function(d){return d.y;});if(!d.total){d.disabled=true;}});groupTotals=properties.values.map(function(d,i){d.t=d3.sum(data.map(function(m,j){if(m.disabled){return 0;}
return(hideEmptyGroups?m._values:m.values).filter(function(v,k){return multibar.x()(v,k)===d.group;}).map(function(v,k){return multibar.y()(v,k);});}));return d;});totalAmount=d3.sum(groupTotals,function(d){return d.t;});groupLabels=properties.labels.filter(function(d,i){return hideEmptyGroups?groupTotals[i].t!==0:true;}).map(function(d){return d.l;});dataBars=data.filter(function(d,i){return!d.disabled&&(!d.type||d.type==='bar');});if(hideEmptyGroups){dataBars.map(function(d,i){d.values=d._values.filter(function(d,i){return groupTotals[i].t!==0;}).map(function(m,j){return{'series':d.series,'x':(j+1),'y':m.y,'y0':m.y0,'active':typeof d.active!=='undefined'?d.active:''};});return d;});}
if(!totalAmount){displayNoData();return chart;}
if(!dataBars.length){dataBars=[{values:[]}];}
state.disabled=data.map(function(d){return!!d.disabled;});state.stacked=multibar.stacked();groupCount=groupLabels.length;seriesCount=dataBars.length;x=multibar.xScale();y=multibar.yScale();xAxis.scale(x).tickFormat(function(d,i){return groupLabels[i]||'undefined';});yAxis.scale(y);chart.render=function(){var renderWidth=width||parseInt(container.style('width'),10)||960,renderHeight=height||parseInt(container.style('height'),10)||400,availableWidth=renderWidth-margin.left-margin.right,availableHeight=renderHeight-margin.top-margin.bottom,innerWidth=innerWidth||availableWidth,innerHeight=innerHeight||availableHeight,innerMargin={top:0,right:0,bottom:0,left:0};var maxControlsWidth=0,maxLegendWidth=0,widthRatio=0,headerHeight=0,titleBBox={width:0,height:0},controlsHeight=0,legendHeight=0,trans='';var baseDimension=multibar.stacked()?vertical?60:30:20,boundsWidth=state.stacked?baseDimension:baseDimension*seriesCount+baseDimension,gap=baseDimension*(state.stacked?0.25:1),minDimension=groupCount*boundsWidth+gap;var wrap=container.selectAll('.nvd3.nv-wrap').data([data]),gEnter=wrap.enter().append('g').attr('class','nvd3 nv-wrap').append('g'),g=wrap.select('g').attr('class','nv-chartWrap');wrap.attr('class','nvd3 nv-wrap nv-'+className);gEnter.append('defs');gEnter.append('g').attr('class','nv-scroll-background');gEnter.append('g').attr('class','nv-titleWrap');var titleWrap=g.select('.nv-titleWrap');gEnter.append('g').attr('class','nv-y nv-axis');var yAxisWrap=g.select('.nv-y.nv-axis');gEnter.append('g').attr('class','nv-scroll-wrap');var scrollWrap=g.select('.nv-scroll-wrap');gEnter.select('.nv-scroll-wrap').append('g').attr('class','nv-x nv-axis');var xAxisWrap=g.select('.nv-x.nv-axis');gEnter.select('.nv-scroll-wrap').append('g').attr('class','nv-barsWrap');var barsWrap=g.select('.nv-barsWrap');gEnter.append('g').attr('class','nv-controlsWrap');var controlsWrap=g.select('.nv-controlsWrap');gEnter.append('g').attr('class','nv-legendWrap');var legendWrap=g.select('.nv-legendWrap');wrap.attr('transform','translate('+margin.left+','+margin.top+')');titleWrap.select('.nv-title').remove();if(showTitle){titleWrap.append('text').attr('class','nv-title').attr('x',direction==='rtl'?availableWidth:0).attr('y',0).attr('dy','.75em').attr('text-anchor','start').text(properties.title).attr('stroke','none').attr('fill','black');titleBBox=nv.utils.getTextBBox(g.select('.nv-title'));headerHeight+=titleBBox.height;}
if(showControls){controls.id('controls_'+chart.id()).strings(chart.strings().controls).align('left').height(availableHeight-headerHeight);controlsWrap.datum(controlsData).call(controls);maxControlsWidth=controls.calculateWidth();}
if(showLegend){if(multibar.barColor()){data.forEach(function(series,i){series.color=d3.rgb('#ccc').darker(i*1.5).toString();});}
legend.id('legend_'+chart.id()).strings(chart.strings().legend).align('right').height(availableHeight-headerHeight);legendWrap.datum(data).call(legend);maxLegendWidth=legend.calculateWidth();}
widthRatio=availableWidth /(maxControlsWidth+maxLegendWidth);maxControlsWidth=Math.floor(maxControlsWidth*widthRatio);maxLegendWidth=Math.floor(maxLegendWidth*widthRatio);if(showControls){controls.arrange(maxControlsWidth);maxLegendWidth=availableWidth-controls.width();}
if(showLegend){legend.arrange(maxLegendWidth);maxControlsWidth=availableWidth-legend.width();}
if(showControls){var xpos=direction==='rtl'?availableWidth-controls.width():0,ypos=showTitle?titleBBox.height:-legend.margin().top;controlsWrap.attr('transform','translate('+xpos+','+ypos+')');controlsHeight=controls.height();}
if(showLegend){var legendLinkBBox=nv.utils.getTextBBox(legendWrap.select('.nv-legend-link')),legendSpace=availableWidth-titleBBox.width-6,legendTop=showTitle&&!showControls&&legend.collapsed()&&legendSpace>legendLinkBBox.width?true:false,xpos=direction==='rtl'?0:availableWidth-legend.width(),ypos=titleBBox.height;if(legendTop){ypos=titleBBox.height-legend.height()/ 2-legendLinkBBox.height / 2;}else if(!showTitle){ypos=-legend.margin().top;}
legendWrap.attr('transform','translate('+xpos+','+ypos+')');legendHeight=legendTop?12:legend.height();}
headerHeight+=Math.max(controlsHeight,legendHeight);innerHeight=availableHeight-headerHeight-innerMargin.top-innerMargin.bottom;function getDimension(d){if(d==='width'){return vertical&&scrollEnabled?Math.max(innerWidth,minDimension):innerWidth;}else if(d==='height'){return!vertical&&scrollEnabled?Math.max(innerHeight,minDimension):innerHeight;}else{return 0;}}
multibar.vertical(vertical).baseDimension(baseDimension).disabled(data.map(function(series){return series.disabled;})).width(getDimension('width')).height(getDimension('height')).clipEdge(false);barsWrap.data([dataBars]).call(multibar);var yAxisMargin={top:0,right:0,bottom:0,left:0},xAxisMargin={top:0,right:0,bottom:0,left:0};function setInnerMargins(){innerMargin.left=Math.max(xAxisMargin.left,yAxisMargin.left);innerMargin.right=Math.max(xAxisMargin.right,yAxisMargin.right);innerMargin.top=Math.max(xAxisMargin.top,yAxisMargin.top);innerMargin.bottom=Math.max(xAxisMargin.bottom,yAxisMargin.bottom);}
function setInnerDimensions(){innerWidth=availableWidth-innerMargin.left-innerMargin.right;innerHeight=availableHeight-headerHeight-innerMargin.top-innerMargin.bottom;multibar.resetDimensions(getDimension('width'),getDimension('height'));}
yAxis.orient(vertical?'left':'bottom').ticks(innerHeight / 48).margin(innerMargin);yAxisWrap.call(yAxis);yAxisMargin=yAxis.margin();setInnerMargins();setInnerDimensions();xAxis.orient(vertical?'bottom':'left').margin(innerMargin).tickFormat(function(d,i,noEllipsis){var label=groupLabels[i]||'undefined';if(!noEllipsis){label=nv.utils.stringEllipsify(label,container,Math.max(vertical?baseDimension*2:availableWidth*0.2,75));}
return label;});xAxisWrap.call(xAxis);xAxisMargin=xAxis.margin();setInnerMargins();setInnerDimensions();xAxis.tickSize(0).margin(innerMargin);xAxisWrap.call(xAxis);yAxis.tickSize(vertical?-innerWidth:-innerHeight,0).margin(innerMargin);yAxisWrap.call(yAxis);barsWrap.transition().call(multibar);useScroll=minDimension>(vertical?innerWidth:innerHeight);innerMargin.top+=headerHeight;trans=(vertical||xAxis.orient()==='left'?0:innerWidth)+',';trans+=(vertical&&xAxis.orient()==='bottom'?innerHeight:0);xAxisWrap.attr('transform','translate('+trans+')');trans=innerMargin.left+(vertical||yAxis.orient()==='bottom'?0:innerWidth)+',';trans+=innerMargin.top+(vertical||yAxis.orient()==='left'?0:innerHeight);yAxisWrap.attr('transform','translate('+trans+')');scrollWrap.attr('transform','translate('+innerMargin.left+','+innerMargin.top+')');xAxisWrap.select('.nv-axislabel').attr('x',(vertical?innerWidth:-innerHeight)/ 2);if(scrollEnabled){var diff=(vertical?innerWidth:innerHeight)-minDimension,panMultibar=function(){dispatch.tooltipHide(d3.event);scrollOffset=scroll.pan(diff);xAxisWrap.select('.nv-axislabel').attr('x',(vertical?innerWidth-scrollOffset*2:scrollOffset*2-innerHeight)/ 2);};scroll.id(chart.id()).enable(useScroll).vertical(vertical).width(innerWidth).height(innerHeight).margin(innerMargin).minDimension(minDimension).panHandler(panMultibar);scroll(g,gEnter,scrollWrap,xAxis);scroll.init(scrollOffset,overflowHandler);scroll.panHandler()();}};chart.render();legend.dispatch.on('legendClick',function(d,i){d.disabled=!d.disabled;if(hideEmptyGroups){data.map(function(m,j){m._values.map(function(v,k){v.disabled=(k===i?d.disabled:v.disabled?true:false);return v;});return m;});}
if(!data.filter(function(d){return!d.disabled;}).length){data.map(function(d){d.disabled=false;container.selectAll('.nv-series').classed('disabled',false);return d;});}
state.disabled=data.map(function(d){return!!d.disabled;});dispatch.stateChange(state);container.transition().call(chart);});controls.dispatch.on('legendClick',function(d,i){if(!d.disabled){return;}
controlsData=controlsData.map(function(s){s.disabled=true;return s;});d.disabled=false;switch(d.key){case'Grouped':multibar.stacked(false);break;case'Stacked':multibar.stacked(true);break;}
state.stacked=multibar.stacked();dispatch.stateChange(state);container.transition().call(chart);});dispatch.on('tooltipShow',function(eo){if(tooltips){showTooltip(eo,that.parentNode,groupTotals);}});dispatch.on('tooltipMove',function(e){if(tooltip){nv.tooltip.position(that.parentNode,tooltip,e,vertical?'s':'w');}});dispatch.on('tooltipHide',function(){if(tooltips){nv.tooltip.cleanup();}});dispatch.on('changeState',function(eo){if(typeof eo.disabled!=='undefined'){data.forEach(function(series,i){series.disabled=eo.disabled[i];});state.disabled=eo.disabled;}
if(typeof eo.stacked!=='undefined'){multibar.stacked(eo.stacked);state.stacked=eo.stacked;}
container.transition().call(chart);});dispatch.on('chartClick',function(){if(controls.enabled()){controls.dispatch.closeMenu();}
if(legend.enabled()){legend.dispatch.closeMenu();}});multibar.dispatch.on('elementClick',function(eo){dispatch.chartClick();seriesClick(data,eo,chart);});});return chart;}
multibar.dispatch.on('elementMouseover.tooltip',function(eo){dispatch.tooltipShow(eo);});multibar.dispatch.on('elementMousemove.tooltip',function(e){dispatch.tooltipMove(e);});multibar.dispatch.on('elementMouseout.tooltip',function(){dispatch.tooltipHide();});chart.dispatch=dispatch;chart.multibar=multibar;chart.legend=legend;chart.controls=controls;chart.xAxis=xAxis;chart.yAxis=yAxis;d3.rebind(chart,multibar,'id','x','y','xScale','yScale','xDomain','yDomain','forceX','forceY','clipEdge','delay','color','fill','classes','gradient');d3.rebind(chart,multibar,'stacked','showValues','valueFormat','nice');d3.rebind(chart,xAxis,'rotateTicks','reduceXTicks','staggerTicks','wrapTicks');chart.colorData=function(_){var type=arguments[0],params=arguments[1]||{};var color=function(d,i){return nv.utils.defaultColor()(d,d.series);};var classes=function(d,i){return'nv-group nv-series-'+d.series;};switch(type){case'graduated':color=function(d,i){return d3.interpolateHsl(d3.rgb(params.c1),d3.rgb(params.c2))(d.series / params.l);};break;case'class':color=function(){return'inherit';};classes=function(d,i){var iClass=(d.series*(params.step||1))%14;iClass=(iClass>9?'':'0')+iClass;return'nv-group nv-series-'+d.series+' nv-fill'+iClass;};break;case'data':color=function(d,i){return d.classes?'inherit':d.color||nv.utils.defaultColor()(d,d.series);};classes=function(d,i){return'nv-group nv-series-'+d.series+(d.classes?' '+d.classes:'');};break;}
var fill=(!params.gradient)?color:function(d,i){var p={orientation:params.orientation||(vertical?'vertical':'horizontal'),position:params.position||'middle'};return multibar.gradient(d,d.series,p);};multibar.color(color);multibar.fill(fill);multibar.classes(classes);legend.color(color);legend.classes(classes);return chart;};chart.margin=function(_){if(!arguments.length){return margin;}
for(var prop in _){if(_.hasOwnProperty(prop)){margin[prop]=_[prop];}}
return chart;};chart.vertical=function(_){if(!arguments.length){return vertical;}
vertical=_;return chart;};chart.width=function(_){if(!arguments.length){return width;}
width=_;return chart;};chart.height=function(_){if(!arguments.length){return height;}
height=_;return chart;};chart.showTitle=function(_){if(!arguments.length){return showTitle;}
showTitle=_;return chart;};chart.showControls=function(_){if(!arguments.length){return showControls;}
showControls=_;return chart;};chart.showLegend=function(_){if(!arguments.length){return showLegend;}
showLegend=_;return chart;};chart.tooltip=function(_){if(!arguments.length){return tooltip;}
tooltip=_;return chart;};chart.tooltips=function(_){if(!arguments.length){return tooltips;}
tooltips=_;return chart;};chart.tooltipContent=function(_){if(!arguments.length){return tooltipContent;}
tooltipContent=_;return chart;};chart.state=function(_){if(!arguments.length){return state;}
state=_;return chart;};chart.strings=function(_){if(!arguments.length){return strings;}
for(var prop in _){if(_.hasOwnProperty(prop)){strings[prop]=_[prop];}}
return chart;};chart.allowScroll=function(_){if(!arguments.length){return scrollEnabled;}
scrollEnabled=_;return chart;};chart.overflowHandler=function(_){if(!arguments.length){return overflowHandler;}
overflowHandler=d3.functor(_);return chart;};chart.seriesClick=function(_){if(!arguments.length){return seriesClick;}
seriesClick=_;return chart;};chart.hideEmptyGroups=function(_){if(!arguments.length){return hideEmptyGroups;}
hideEmptyGroups=_;return chart;};chart.direction=function(_){if(!arguments.length){return direction;}
direction=_;multibar.direction(_);xAxis.direction(_);yAxis.direction(_);legend.direction(_);controls.direction(_);return chart;};return chart;};