/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({fieldTag:'input.select2',plugins:['QuickSearchFilter','EllipsisInline'],initialize:function(options){this._allow_single_deselect=true;this._minChars=options.def.minChars||1;this._separator='|';this._maxSelectedRecords=20;this._super('initialize',[options]);this._select2formatSelectionTemplate=app.template.getField('relate','pill',this.module);var populateMetadata=app.metadata.getModule(this.getSearchModule());if(_.isEmpty(populateMetadata)){return;}
_.each(this.def.populate_list,function(target,source){if(_.isUndefined(populateMetadata.fields[source])){app.logger.error('Fail to populate the related attributes: attempt to access undefined key - '+
this.getSearchModule()+'::'+source);}},this);this._createSearchCollection();},_createFiltersCollection:function(options){var searchModule=this.getSearchModule();if(!app.acl.hasAccess('list',searchModule)){app.logger.debug('No "list" access to '+searchModule+' so skipping the creation of filter.');return;}
if(app.metadata.getModule('Filters')&&searchModule){this.filters=app.data.createBeanCollection('Filters');this.filters.setModuleName(searchModule);this.filters.setFilterOptions(this.getFilterOptions());this.filters.load(options);}},_createSearchCollection:function(){var searchModule=this.getSearchModule();if(searchModule&&app.metadata.getModule(searchModule)){this.searchCollection=app.data.createBeanCollection(searchModule);}else{this.searchCollection=null;}},bindKeyDown:function(callback){var $dropdown=this.$(this.fieldTag);$dropdown.on('keydown.record',{field:this},callback);var plugin=$dropdown.data('select2');if(plugin){plugin.focusser.on('keydown.record',{field:this},callback);plugin.search.on('keydown.record',{field:this},callback);}},unbindKeyDown:function(callback){var $dropdown=this.$(this.fieldTag);$dropdown.off('keydown.record',callback);var plugin=$dropdown.data('select2');if(plugin){plugin.search.off('keydown.record',callback);}},focus:function(){if(this.action!=='disabled'){_.defer(_.bind(function(){this.$(this.fieldTag).first().select2('open');},this));}},_buildCssClasses:function(){var cssClasses=[];if(this.view.name==='recordlist'){cssClasses.push('select2-narrow');}
if(this.type==='parent'){cssClasses.push('select2-parent');}
if(this.def.isMultiSelect){cssClasses.push('select2-choices-pills-close same-size-pills');}
return cssClasses.join(' ');},_render:function(){var searchModule=this.getSearchModule();this._super('_render');switch(this.tplName){case'edit':case'massupdate':if(!_.isUndefined(searchModule)){if(!app.acl.hasAccess('list',searchModule)||!_.contains(app.metadata.getModuleNames(),searchModule)){this._renderDisabledDropdown();break;}}
if(_.isUndefined(this.filters)){this._createFiltersCollection({success:_.bind(function(){if(!this.disposed){this._renderEditableDropdown();}},this)});}else{this._renderEditableDropdown();}
break;case'disabled':this._renderDisabledDropdown();break;}
return this;},_renderEditableDropdown:function(){var self=this;var $dropdown=this.$(this.fieldTag);var loadingLabel=app.lang.get('LBL_LOADING',this.module);var inList=this.view.name==='recordlist';$dropdown.select2({width:inList?'off':'100%',dropdownCssClass:_.bind(this._buildCssClasses,this),multiple:!!this.def.isMultiSelect,containerCssClass:_.bind(this._buildCssClasses,this),separator:this._separator,initSelection:_.bind(this._onInitSelect,this),formatInputTooShort:function(){return'';},formatSelection:_.bind(this._onFormatSelection,this),formatSearching:loadingLabel,placeholder:this.getPlaceHolder(),allowClear:self._allow_single_deselect,minimumInputLength:self._minChars,maximumSelectionSize:20,query:_.bind(this.search,this)}).on('select2-open',_.bind(this._onSelect2Open,this)).on('searchmore',function(){$(this).select2('close');self.openSelectDrawer();}).on('change',function(e){var plugin=$(this).data('select2'),id=e.val;if(_.isUndefined(id)){return;}
if(self.def.isMultiSelect){var dataRname=plugin.opts.element.data('rname');dataRname=dataRname?dataRname.split(self._separator):[];var ids=$(this).select2('val');if(e.added){dataRname.push(e.added.text);}else if(e.removed){dataRname=_.without(dataRname,e.removed.text);}else{return;}
var models=_.map(ids,function(id,index){return{id:id,value:dataRname[index]};});self.setValue(models);return;}
var value=(id)?plugin.selection.find('span').text():$(this).data('rname'),collection=plugin.context,attributes={};if(collection&&!_.isEmpty(id)){var model=collection.get(id);attributes.id=model.id;attributes.value=model.get('name');_.each(model.attributes,function(value,field){if(app.acl.hasAccessToModel('view',model,field)){attributes[field]=attributes[field]||model.get(field);}});}else if(e.currentTarget.value&&value){attributes.id=value;attributes.value=e.currentTarget.value;}else{attributes.id='';attributes.value='';}
self.setValue(attributes);});var plugin=$dropdown.data('select2');if(plugin&&plugin.focusser){plugin.focusser.on('select2-focus',_.bind(_.debounce(this.handleFocus,0),this));}},_renderDisabledDropdown:function(){var loadingLabel=app.lang.get('LBL_LOADING',this.module);var $dropdown=this.$(this.fieldTag);$dropdown.select2({width:'100%',initSelection:function(el,callback){var $el=$(el),id=$el.val(),text=$el.data('rname');callback({id:id,text:text});},formatInputTooShort:function(){return'';},formatSearching:function(){return loadingLabel;},placeholder:this.getPlaceHolder(),allowClear:self._allow_single_deselect,minimumInputLength:self._minChars,query:_.bind(this.search,this)});$dropdown.select2('disable');},_onInitSelect:function(el,callback){var $el=$(el),id=$el.val(),text=$el.data('rname');if(!this.def.isMultiSelect){return callback({id:id,text:text});}
var ids=id.split(this._separator);text=text.split(this._separator);callback(_.map(ids,function(value,index){return{id:value,text:text[index]};}));},_onFormatSelection:function(obj){var ctx={};ctx.text=obj.text||obj.id;return this._select2formatSelectionTemplate(ctx);},_onSelect2Open:function(e){var plugin=this.$(e.currentTarget).data('select2');if(plugin.searchmore){return;}
var label=app.lang.get('LBL_SEARCH_AND_SELECT_ELLIPSIS',this.module);var $tpl=$('<div/>').addClass('select2-result-label').html(label);var onMouseDown=function(){plugin.opts.element.trigger($.Event('searchmore'));plugin.close();};var $content=$('<li class="select2-result">').append($tpl).mousedown(onMouseDown);plugin.searchmore=$('<ul class="select2-results">').append($content);plugin.dropdown.append(plugin.searchmore);},buildRoute:function(module,id){var oldModule=module;if(module==='Users'&&this.context.get('module')!=='Users'){module='Employees';}
if(_.isEmpty(module)||(!_.isUndefined(this.def.link)&&!this.def.link)){return;}
var action=(this.def.link&&this.def.route)?this.def.route.action:"view";if(!_.isEmpty(id)&&app.acl.hasAccess(action,oldModule)){this.href='#'+app.router.buildRoute(module,id);}else{this.href=undefined;}},_buildRoute:function(){this.buildRoute(this.getSearchModule(),this._getRelateId());},_getRelateId:function(){return this.model.get(this.def.id_name);},format:function(value){var parentCtx=this.context&&this.context.parent,setFromCtx;if(value){this._valueSetOnce=true;}
setFromCtx=value===null&&!this._valueSetOnce&&parentCtx&&_.isEmpty(this.context.get('model').link)&&this.view instanceof app.view.views.BaseCreateView&&parentCtx.get('module')===this.def.module&&this.module!==this.def.module;if(setFromCtx){this._valueSetOnce=true;var model=parentCtx.get('model');this.def.auto_populate=true;this.setValue(model.toJSON());}
if(!this.def.isMultiSelect){this._buildRoute();}
var idList=this.model.get(this.def.id_name);if(_.isArray(value)){this.formattedRname=value.join(this._separator);this.formattedIds=idList.join(this._separator);}else{this.formattedRname=value;this.formattedIds=idList;}
return value;},setValue:function(models){if(!models){return;}
var updateRelatedFields=true,values={};if(_.isArray(models)){updateRelatedFields=false;}else{models=[models];}
values[this.def.id_name]=[];values[this.def.name]=[];_.each(models,_.bind(function(model){values[this.def.id_name].push(model.id);values[this.def.name].push(model[this.getRelatedModuleField()]||model.value);},this));if(!this.def.isMultiSelect){values[this.def.id_name]=values[this.def.id_name][0];values[this.def.name]=values[this.def.name][0];}
this.model.set(values);if(updateRelatedFields){if(this.model.get(this.def.link)){this.model.unset(this.def.link);}else{this.model.trigger('change:'+this.def.link);}
this.updateRelatedFields(models[0]);}},updateRelatedFields:function(model){var newData={},self=this;_.each(this.def.populate_list,function(target,source){source=_.isNumber(source)?target:source;if(!_.isUndefined(model[source])&&app.acl.hasAccessToModel('edit',this.model,target)){var before=this.model.get(target),after=model[source];if(before!==after){newData[target]=model[source];}}},this);if(_.isEmpty(newData)){return;}
if(!_.isUndefined(this.def.auto_populate)&&this.def.auto_populate==true){if(!_.isUndefined(newData.currency_id)){this.model.set({currency_id:newData.currency_id});delete newData.currency_id;}
this.model.set(newData);return;}
var messageTplKey=this.def.populate_confirm_label||'TPL_OVERWRITE_POPULATED_DATA_CONFIRM',messageTpl=Handlebars.compile(app.lang.get(messageTplKey,this.getSearchModule())),fieldMessageTpl=app.template.getField(this.type,'overwrite-confirmation',this.model.module),messages=[],relatedModuleSingular=app.lang.getModuleName(this.def.module);_.each(newData,function(value,field){var before=this.model.get(field),after=value;if(before!==after){var def=this.model.fields[field];messages.push(fieldMessageTpl({before:before,after:after,field_label:app.lang.get(def.label||def.vname||field,this.module)}));}},this);app.alert.show('overwrite_confirmation',{level:'confirmation',messages:messageTpl({values:new Handlebars.SafeString(messages.join(', ')),moduleSingularLower:relatedModuleSingular.toLowerCase()}),onConfirm:function(){if(!_.isUndefined(newData.currency_id)){self.model.set({currency_id:newData.currency_id});delete newData.currency_id;}
self.model.set(newData);}});},openSelectDrawer:function(){var layout='selection-list';var context={module:this.getSearchModule(),fields:this.getSearchFields(),filterOptions:this.getFilterOptions()};if(!!this.def.isMultiSelect){layout='multi-selection-list';_.extend(context,{preselectedModelIds:_.clone(this.model.get(this.def.id_name)),maxSelectedRecords:this._maxSelectedRecords,isMultiSelect:true});}
app.drawer.open({layout:layout,context:context},_.bind(this.setValue,this));},getSearchFields:function(){return _.union(['id',this.getRelatedModuleField()],_.keys(this.def.populate_list||{}));},getRelatedModuleField:function(){return this.def.rname||'name';},bindDomChange:function(){},getSearchModule:function(){if(this.def.module){return this.def.module;}
var link=this.def.link&&this.model.fields&&this.model.fields[this.def.link]||{};if(link.module){return link.module;}
return app.data.getRelatedModule(this.model.module,this.def.link);},getPlaceHolder:function(){var searchModule=this.getSearchModule(),searchModuleLower=searchModule.toLocaleLowerCase(),module=app.lang.getModuleName(searchModule,{defaultValue:searchModuleLower});return app.lang.get('LBL_SEARCH_SELECT_MODULE',this.module,{module:new Handlebars.SafeString(module)});},getFilterOptions:function(force){if(this._filterOptions&&!force){return this._filterOptions;}
this._filterOptions=new app.utils.FilterOptions().config(this.def).setInitialFilter(this.def.initial_filter||'$relate').populateRelate(this.model).format();return this._filterOptions;},buildFilterDefinition:function(searchTerm){if(!app.metadata.getModule('Filters')||!this.filters){return[];}
var filterBeanClass=app.data.getBeanClass('Filters').prototype,filterOptions=this.getFilterOptions()||{},filter=this.filters.collection.get(filterOptions.initial_filter),filterDef,populate,searchTermFilter,searchModule;if(filter){populate=filter.get('is_template')&&filterOptions.filter_populate;filterDef=filterBeanClass.populateFilterDefinition(filter.get('filter_definition')||{},populate);searchModule=filter.moduleName;}
searchTermFilter=filterBeanClass.buildSearchTermFilter(searchModule||this.getSearchModule(),searchTerm);return filterBeanClass.combineFilterDefinitions(filterDef,searchTermFilter);},search:_.debounce(function(query){var term=query.term||'',self=this,searchModule=this.getSearchModule(),params={},limit=self.def.limit||5,relatedModuleField=this.getRelatedModuleField();if(query.context){params.offset=this.searchCollection.next_offset;}
params.filter=this.buildFilterDefinition(term);this.searchCollection.fetch({showAlerts:false,update:true,remove:_.isUndefined(params.offset),fields:this.getSearchFields(),context:self,params:params,limit:limit,success:function(data){var fetch={results:[],more:data.next_offset>0,context:data};if(fetch.more){var fieldEl=self.$(self.fieldTag),plugin=(fieldEl.length>1)?$(fieldEl.get(self.currentIndex)).data("select2"):fieldEl.data("select2"),height=plugin.searchmore.children("li:first").children(":first").outerHeight(),maxHeight=height*(limit-.2);plugin.results.css("max-height",maxHeight);}
_.each(data.models,function(model,index){if(params.offset&&index<params.offset){return;}
fetch.results.push({id:model.id,text:model.get(relatedModuleField)+''});});if(query.callback&&_.isFunction(query.callback)){query.callback(fetch);}},error:function(){if(query.callback&&_.isFunction(query.callback)){query.callback({results:[]});}
app.logger.error("Unable to fetch the bean collection.");}});},app.config.requiredElapsed||500),bindDataChange:function(){if(this.model){this.model.on('change',function(){this.getFilterOptions(true);},this);this.model.on('change:'+this.name,function(){if(this.disposed){return;}
var $dropdown=this.$(this.fieldTag);if(!_.isEmpty($dropdown.data('select2'))){var value=this.model.get(this.def.name);value=_.isArray(value)?value.join(this._separator):value;value=value?value.trim():value;$dropdown.data('rname',value);var id=this.model.get(this.def.id_name);if(_.isEqual($dropdown.select2('val'),id)){return;}
$dropdown.select2('val',id);}else{this.render();}},this);}},unbindDom:function(){this.$(this.fieldTag).select2('destroy');app.view.Field.prototype.unbindDom.call(this);}})