/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({className:'table-cell quicksearch-bar-wrapper',minChars:1,searchModules:[],events:{'focus input[data-action=search_bar]':'requestFocus','click input[data-action=search_bar]':'searchBarClickHandler'},initialize:function(options){this._super('initialize',[options]);this.collection=this.layout.collection||app.data.createMixedBeanCollection();this.selectedTags=this.layout.selectedTags||[];this.limit=5;if(this.meta&&this.meta.limit){this.limit=this.meta.limit;}
this.isFocusable=true;this._searchTerm='';this._oldSearchTerm='';this._currentQueryTerm='';app.events.on('app:sync:complete',this.populateModules,this);this.on('navigate:focus:receive',function(){var inputBox=this.$input[0];if(inputBox!==$(document.activeElement)[0]){inputBox.focus();}else{this.attachKeyEvents();}},this);this.on('navigate:focus:lost',function(){this.disposeKeyEvents();},this);this.layout.on('quicksearch:close',function(){this._searchTerm='';this._currentQueryTerm='';this._oldSearchTerm='';this.collection.abortFetchRequest();this.$input.blur();},this);this.layout.on('quicksearch:bar:clear',this.clearSearch,this);this.layout.on('quicksearch:bar:clear:term',this.clearSearchTerm,this);this.layout.on('quicksearch:bar:search',this.goToSearchPage,this);this.layout.on('route:search',this.populateSearchTerm,this);this.layout.on('quicksearch:fire:search',function(){this.collection.abortFetchRequest();this._oldSearchTerm=null;this._currentQueryTerm=null;this._validateAndSearch();},this);},_renderHtml:function(){this._super('_renderHtml');this.$input=this.$('input[data-action=search_bar]');},populateSearchTerm:function(){var inputBar=this.$input;var searchTerm=this.context.get('searchTerm');if(inputBar.val()!==searchTerm){inputBar.val(searchTerm);}},requestFocus:function(){this.layout.trigger('navigate:to:component',this.name);},attachKeyEvents:function(){var searchBarEl=this.$input;searchBarEl.on('keydown',_.bind(this.keydownHandler,this));searchBarEl.on('keyup',_.bind(this.keyupHandler,this));},disposeKeyEvents:function(){this.$input.off('keydown keyup');},keydownHandler:function(e){switch(e.keyCode){case 40:this.moveForward();e.preventDefault();e.stopPropagation();break;case 38:e.preventDefault();e.stopPropagation();break;case 37:case 8:var term=this.$input.val();if(term===''){this.moveBackward();e.stopPropagation();e.preventDefault();}
break;}},keyupHandler:function(e){switch(e.keyCode){case 40:break;case 38:break;case 9:break;case 16:break;case 13:this.goToSearchPage();break;case 27:this.layout.trigger('quicksearch:close');break;default:this._validateAndSearch();}},goToSearchPage:function(){var term=this.$input.val();var route='';this._searchTerm===this._currentQueryTerm;this._currentQueryTerm=term;if(this.layout.v2){route=app.utils.GlobalSearch.buildSearchRoute(term,{modules:this.collection.selectedModules,tags:_.pluck(this.selectedTags,'name')});}else{var moduleString=this.collection.selectedModules.join(',');route='bwc/index.php?module=Home&append_wildcard=true&action=spot&full=true'+'&q='+term+'&m='+moduleString;}
this.collection.abortFetchRequest();app.router.navigate(route,{trigger:true});},searchBarClickHandler:function(){this.requestFocus();_.defer(_.bind(this.layout.expand,this.layout));},moveForward:function(){if(this.layout.triggerBefore('navigate:next:component')){this.disposeKeyEvents();this.layout.trigger('navigate:next:component');}},moveBackward:function(){if(this.layout.triggerBefore('navigate:previous:component')){this.disposeKeyEvents();this.layout.trigger('navigate:previous:component');}},_debounceSearch:_.debounce(function(){if((!this._searchTerm&&this.selectedTags.length===0)||this._searchTerm===this._currentQueryTerm){return;}
this._currentQueryTerm=this._searchTerm;this.fireSearchRequest();},500),_validateAndSearch:function(){var term=this.$input.val();this._searchTerm=term;if(term.length<this.minChars&&this.selectedTags.length===0){this._searchTerm='';this._currentQueryTerm='';this._oldSearchTerm='';this.collection.abortFetchRequest();this.layout.trigger('quicksearch:results:close');this.collection.abortFetchRequest();return;}
var hasInputChanged=(this._searchTerm!==this._oldSearchTerm);if(hasInputChanged){this.collection.dataFetched=false;this.layout.trigger('quicksearch:search:underway');this.layout.expand();this._oldSearchTerm=term;this._debounceSearch();}},fireSearchRequest:function(){var term=this._searchTerm;var limit=this.layout.v2?this.limit:5;limit=app.config&&app.config.maxSearchQueryResult||limit;var options={query:term,module_list:this.collection.selectedModules,limit:limit,params:{tags:true},apiOptions:{useNewApi:true}};if(this.selectedTags.length>0){_.extend(options.apiOptions,{data:{tag_filters:_.pluck(this.selectedTags,'id')},fetchWithPost:true});}
if(!this.layout.v2){options.fields=['name','id'];}
this.collection.query=term;this.collection.fetch(options);},clearSearch:function(){this.$input.val('');this._searchTerm='';this._oldSearchTerm='';this._currentQueryTerm='';this.layout.trigger('quicksearch:tags:remove');this.disposeKeyEvents();},clearSearchTerm:function(){this.$input.val('');this._searchTerm='';this._oldSearchTerm='';this._currentQueryTerm='';},unbind:function(){this.disposeKeyEvents();this._super('unbind');}})