/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
var Style=function(options){this.cssProperties=null;this.cssClasses=null;this.belongsTo=null;Style.prototype.initObject.call(this,options);};Style.prototype.type="Style";Style.MAX_ZINDEX=100;Style.prototype.initObject=function(options){var defaults={cssClasses:[],cssProperties:{},belongsTo:null};$.extend(true,defaults,options);this.cssClasses=defaults.cssClasses;this.cssProperties=defaults.cssProperties;this.belongsTo=defaults.belongsTo;};Style.prototype.applyStyle=function(){if(!this.belongsTo.html){throw new Error("applyStyle(): can't apply style to an"+" object with no html");}
var i,class_i;$(this.belongsTo.html).css(this.cssProperties);for(i=0;i<this.cssClasses.length;i+=1){class_i=this.cssClasses[i];if(!$(this.belongsTo.html).hasClass(class_i)){$(this.belongsTo.html).addClass(class_i);}}
return this;};Style.prototype.addProperties=function(properties){$.extend(true,this.cssProperties,properties);$(this.belongsTo.html).css(properties);return this;};Style.prototype.getProperty=function(property){return this.cssProperties[property]||$(this.belongsTo.html).css(property)||window.getComputedStyle(this.belongsTo.html,null).getPropertyValue(property);};Style.prototype.removeProperties=function(properties){var property,i;for(i=0;i<properties.length;i+=1){property=properties[i];if(this.cssProperties.hasOwnProperty(property)){$(this.belongsTo.html).css(property,"");delete this.cssProperties[property];}}
return this;};Style.prototype.addClasses=function(cssClasses){var i,cssClass;if(cssClasses&&cssClasses instanceof Array){for(i=0;i<cssClasses.length;i+=1){cssClass=cssClasses[i];if(typeof cssClass==="string"){if(this.cssClasses.indexOf(cssClass)===-1){this.cssClasses.push(cssClass);$(this.belongsTo.html).addClass(cssClass);}}else{throw new Error("addClasses(): array element is not of type string");}}}else{throw new Error("addClasses(): parameter must be of type Array");}
return this;};Style.prototype.removeClasses=function(cssClasses){var i,index,cssClass;if(cssClasses&&cssClasses instanceof Array){for(i=0;i<cssClasses.length;i+=1){cssClass=cssClasses[i];if(typeof cssClass==="string"){index=this.cssClasses.indexOf(cssClass);if(index!==-1){$(this.belongsTo.html).removeClass(this.cssClasses[index]);this.cssClasses.splice(index,1);}}else{throw new Error("removeClasses(): array element is not of "+"type string");}}}else{throw new Error("removeClasses(): parameter must be of type Array");}
return this;};Style.prototype.removeAllClasses=function(){this.cssClasses=[];$(this.belongsTo.html).removeClass();return this;};Style.prototype.containsClass=function(cssClass){return this.cssClasses.indexOf(cssClass)!==-1;};Style.prototype.getClasses=function(){return this.cssClasses;};Style.prototype.stringify=function(){return{cssClasses:this.cssClasses};};