/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
(function(app){var _useRequiredLabels={"bool":true,"radioenum":'edit'};app.events.on("app:init",function(){var _fieldProto=_.clone(app.view.Field.prototype);_.extend(app.view.Field.prototype,{hideHelp:false,exclamationMarkTemplate:Handlebars.compile('<span class="error-tooltip add-on" data-container="body" rel="tooltip" title="{{arrayJoin this ", "}}"><i class="fa fa-exclamation-circle"></i></span>'),handleValidationError:function(errors){this.clearErrorDecoration();_.defer(function(field){field._errors=errors;if(field.parent&&field.parent.action==='edit'){field.parent.render();}else if(field.action==='edit'){field.render();}
if(!field._shouldRenderRequiredPlaceholder()){field.decorateRequired();}
if(field.view&&field.view.trigger){field.view.trigger('field:error',field,true);}},this);this.$el.off("keydown.record");$(document).off("mousedown.record"+this.name);},removeValidationErrors:function(){this._errors={};},_removeViewClass:function(action){this.$el.removeClass(action);},_addViewClass:function(action){this.$el.addClass(action);},showNoData:function(){return this.def.readonly&&app.acl.hasAccessToModel('readonly',this.model,this.name)&&this.name&&!this.model.has(this.name);},_checkAccessToAction:function(action){if(_.contains(this.fallbackActions,action)&&_.isUndefined(this.viewFallbackMap[action])){return true;}
if(_.result(this,'showNoData')===true){return action==='nodata';}
return app.acl.hasAccessToModel(action,this.model,this.name);},viewFallbackMap:{'preview':'detail','list':'detail','edit':'detail','detail':'noaccess','noaccess':'nodata'},fallbackActions:['noaccess','nodata'],_getFallbackTemplate:function(viewName){if(_.contains(this.fallbackActions,viewName)){return viewName;}
return(this.isDisabled()&&viewName==='disabled')?'edit':(this.view.fallbackFieldTemplate||'detail');},_render:function(){this.clearErrorDecoration();this._processHelp();_fieldProto._render.call(this);if(this._previousAction){this._addViewClass(this._previousAction);}
this._addViewClass(this.action);if(!_.isEmpty(this._errors)){if(this.action==='edit'){this.decorateError(this._errors);}}
if(this.def.required){this.clearRequiredLabel();if((this.action==='edit'||-1!==_.indexOf(['edit','list-edit'],this.tplName))&&this._shouldRenderRequiredPlaceholder()){this.decorateRequired();}}
if(this.def.help){this.clearHelper();if(this.action==='edit'||-1!==_.indexOf(['edit','list-edit'],this.tplName)){this.decorateHelper();}}
if($.fn.placeholder){var $input=this.$('input');_.each($input,function(element){var $element=$(element);$element.attr('placeholder')&&$element.placeholder();});}},_processHelp:function(){if(this.meta&&!_.isUndefined(this.meta['hide_help'])){this.hideHelp=!!this.meta['hide_help'];return;}
if(this.view.action==='list'&&this.action==='edit'){this.hideHelp=true;}},clearHelper:function(){this.$el.closest('.record-cell').attr({'rel':''});},decorateHelper:function(){this.$el.closest('.record-cell').attr({'rel':'tooltip','data-title':this.def['help'],'data-placement':'bottom'});},_shouldRenderRequiredPlaceholder:function(){return!this.def.no_required_placeholder;},decorateRequired:function(){var useLabels=_useRequiredLabels[this.type];useLabels=_.isString(useLabels)?(useLabels===this.tplName):useLabels;if(useLabels){this.setRequiredLabel();}else{this.setRequiredPlaceholder();}},setRequiredPlaceholder:function(el){var label=app.lang.get('LBL_REQUIRED_FIELD',this.module),placeholder;el=el||this.$(this.fieldTag).first();placeholder=el.attr('placeholder');placeholder=(placeholder)?'('+label+') '+placeholder:label;el.attr('placeholder',placeholder.trim()).addClass('required');},setRequiredLabel:function(element){var ele=element||this.$el;var $label=ele.closest('.record-cell').find(".record-label");$label.append(' <span data-required="required">('+app.lang.get("LBL_REQUIRED_FIELD",this.module)+')</span>');},clearRequiredLabel:function(element){var ele=element||this.$el;var $label=ele.closest('.record-cell').find('span[data-required]');$label.remove();},setMode:function(name){var oldAction=this._previousAction||this.action;this._removeViewClass(oldAction);_fieldProto.setMode.call(this,name);},setDisabled:function(disable){if(!this._checkAccessToAction('disabled')){return;}
disable=_.isUndefined(disable)?true:disable;if(disable===false&&this.isDisabled()){this._removeViewClass(this.action);}
_fieldProto.setDisabled.call(this,disable);},decorateError:function(errors){var ftag=this.fieldTag||'',$ftag=this.$(ftag),errorMessages=[],$tooltip;this.$el.closest('.record-cell').addClass('error');this.$el.addClass('error');if(_.isString(errors)){errorMessages.push(errors);}else{_.each(errors,function(errorContext,errorName){errorMessages.push(app.error.getErrorString(errorName,errorContext));});}
var isWrapped=$ftag.parent().hasClass('input-append');if(!isWrapped){$ftag.wrap('<div class="input-append '+ftag+'">');}
$ftag.parent().addClass('error');$tooltip=$(this.exclamationMarkTemplate(errorMessages));$ftag.after($tooltip);this.createErrorTooltips($tooltip);},createErrorTooltips:function($element){this._errorTooltips=this._errorTooltips||[];this._errorTooltips.push(app.utils.tooltip.initialize($element));},destroyAllErrorTooltips:function(){if(!this._errorTooltips){return;}
app.utils.tooltip.destroy($(this._errorTooltips));this._errorTooltips=null;},_dispose:function(){this.destroyAllErrorTooltips();_fieldProto._dispose.call(this);},clearErrorDecoration:function(){var ftag=this.fieldTag||'',$ftag=this.$(ftag);this.destroyAllErrorTooltips();this.$('.add-on.error-tooltip').remove();var isWrappedError=$ftag.parent().hasClass('input-append')&&$ftag.parent().hasClass('error');var isDateField=$ftag.parent().hasClass('date'),isCurrencyField=$ftag.parent().hasClass('currency');if(isDateField||isCurrencyField){$ftag.parent().removeClass('error');}else if(isWrappedError){$ftag.unwrap();}
this.$el.removeClass(ftag);this.$el.removeClass("error");this.$el.closest('.record-cell').removeClass("error");if(this.view&&this.view.trigger){this.view.trigger('field:error',this,false);}},delegateEvents:function(events){events=events||this.events||(this.def?this.def.events:null);if(!events){return;}
events['click a[href="javascript:void(0)"]']='_handleBadLinkHref';events['click a[href="javascript:void(0);"]']='_handleBadLinkHref';_fieldProto.delegateEvents.call(this,events);},bindDomChange:function(){this.$(this.fieldTag).on('focus',_.bind(_.debounce(this.handleFocus,40),this));_fieldProto.bindDomChange.call(this);},handleFocus:function(){if(this.disposed){return;}
var $flexList=this.$el.closest('.flex-list-view-content');if(!_.isUndefined($flexList)){var previousScrollLeftValue=$flexList.data('previousScrollLeftValue');if(!_.isUndefined(previousScrollLeftValue)&&$flexList.scrollLeft()!==previousScrollLeftValue){$flexList.scrollLeft(previousScrollLeftValue);$flexList.removeData('previousScrollLeftValue');}}
var left=this.$el.position().left;var right=this.$el.outerWidth()+left;var top=this.$el.offset().top;var bottom=this.$el.outerHeight()+top;var fieldPadding=parseInt(this.$el.parent().css('padding-left'),10);this.view.trigger('field:focus:location',{left:left,right:right,top:top,bottom:bottom,fieldPadding:fieldPadding});},_handleBadLinkHref:function(evt){evt.preventDefault();}});});})(SUGAR.App);