/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
(function(app){app.events.on("app:init",function(){var tooltipTemplate=Handlebars.compile('<div class="tooltip">'+'<div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>');var $tooltipTemplate=$(tooltipTemplate());app.utils=_.extend(app.utils,{tooltip:{initialize:function($elements,options,direction){options=options||{};_.each($elements,function(element){var $element=$(element);if(!$element.data('bs.tooltip')){var data=$element.data();if(direction){options.template=$tooltipTemplate.attr('dir',direction);}
$element.tooltip(_.extend({container:'body',trigger:'hover'},data,options));}});return $elements;},destroy:function($tooltips){$tooltips.tooltip('destroy');},show:function(element){var plugin;if(this.has(element)){plugin=this.get(element);plugin.enter(plugin);}},hide:function(element){var plugin;if(this.has(element)){plugin=this.get(element);plugin.leave(plugin);}},has:function(element){return!_.isUndefined(this.get(element));},get:function(element){return $(element).data('bs.tooltip');}},hideForecastCommitStageField:function(panels){var config=app.metadata.getModule('Forecasts','config'),isSetup=(config&&config.is_setup);if(!isSetup){_.each(panels,function(panel){_.every(panel.fields,function(field,index){if(field.name=='commit_stage'){panel.fields[index]={'name':'spacer','label':field.label,'span':6,'readonly':true};return false;}
return true;},this);},this);}},createHistoryLog:function(oldestModel,newestModel,isRepWorksheet){var labels=[];if(_.isEmpty(oldestModel)){oldestModel=new Backbone.Model({best_case:0,likely_case:0,worst_case:0,date_entered:''});labels.push('LBL_COMMITTED_HISTORY_SETUP_FORECAST');}else{labels.push('LBL_COMMITTED_HISTORY_UPDATED_FORECAST');}
var fields=['worst','likely','best'],final=[],num_shown=0,config=app.metadata.getModule('Forecasts','config'),aclModule=(isRepWorksheet)?config.forecast_by:newestModel.module;_.each(fields,function(field){var fieldName=field+'_case';if(config['show_worksheet_'+field]&&app.acl.hasAccess('view',aclModule,null,fieldName)){var diff=this.getDifference(oldestModel,newestModel,fieldName);num_shown++;if(diff!=0){var direction=this.getDirection(diff);final.push(this.gatherLangArgsByParams(direction,this.getArrowDirectionSpan(direction),diff,newestModel,fieldName));labels.push('LBL_COMMITTED_HISTORY_'+field.toUpperCase()+'_CHANGED');}else{final.push([]);labels.push('LBL_COMMITTED_HISTORY_'+field.toUpperCase()+'_SAME');}}},this);var lang_string_key='LBL_COMMITTED_HISTORY_'+num_shown+'_SHOWN',hb=Handlebars.compile('{{{str key module args}}}');final=this.parseArgsAndLabels(final,labels);var text=hb({'key':lang_string_key,'module':'Forecasts','args':final});return{'text':new Handlebars.SafeString(text),'text2':app.date(newestModel.get('date_modified')).formatUser(false,app.user)};},gatherLangArgsByParams:function(dir,arrow,diff,model,attrStr){return{'direction':new Handlebars.SafeString(app.lang.get(dir,'Forecasts')+arrow),'from':app.currency.formatAmountLocale(Math.abs(diff)),'to':app.currency.formatAmountLocale(model.get(attrStr))};},getArrowDirectionSpan:function(directionClass){return directionClass=='LBL_UP'?'&nbsp;<i class="fa fa-arrow-up font-green"></i>':directionClass=='LBL_DOWN'?'&nbsp;<i class="fa fa-arrow-down font-red"></i>':'';},getForecastType:function(isManager,showOpps){return(!showOpps&&isManager)?'Rollup':'Direct';},parseArgsAndLabels:function(argsArray,labels){var retArgs={},argsKeys=['first','second','third'],hb=Handlebars.compile('{{{str key module args}}}');if((argsArray.length+1)!=labels.length){var msg='ForecastsUtils.parseArgsAndLabels() :: '+'argsArray and labels params are not the same length';app.logger.error(msg);return null;}
retArgs.intro=hb({'key':_.first(labels),'module':'Forecasts','args':[]});labels=_.last(labels,labels.length-1);_.each(labels,function(label,index){retArgs[argsKeys[index]]=hb({'key':label,'module':'Forecasts','args':argsArray[index]});});return retArgs;},getDifference:function(oldModel,newModel,attr){return(app.math.isDifferentWithPrecision(newModel.get(attr),oldModel.get(attr)))?app.math.getDifference(newModel.get(attr),oldModel.get(attr)):0;},getDirection:function(difference){return difference>0?'LBL_UP':(difference<0?'LBL_DOWN':'');},getSubpanelList:function(module){var list={},subpanels=app.metadata.getModule(module),comps;if(subpanels&&subpanels.layouts){subpanels=subpanels.layouts.subpanels;if(subpanels&&subpanels.meta){if(subpanels.meta.dynamic){comps=this.getDynamicSubpanelList(module);if(comps&&comps.meta){comps=comps.meta.components||[];}}else{comps=subpanels.meta.components||[];}}}
if(comps){_.each(comps,function(comp){if(comp.context&&comp.context.link){list[comp.label]=comp.context.link;}else{app.logger.warning("Subpanel's subpanels.meta.components "
+"has component with no context or context.link");}});}
return list;},getDynamicSubpanelList:function(module){var dSubpanels=this.getDynamicSubpanelMetadata(module);return{meta:dSubpanels};},getDynamicSubpanelMetadata:function(module){var rels=app.metadata.get().relationships,fields=app.metadata.getModule(module).fields,modules=app.metadata.getModules(),comps=[],self=this;_.each(fields,function(fDefs,fName){var relModule,relDefName,spLabel;if(fDefs.type&&fDefs.type==='link'&&fDefs.relationship){relDefName=fDefs.relationship;if(self.hasDynamicSubpanelDef(rels,relDefName,module)){relModule=rels[relDefName].lhs_module;if(modules[relModule]){var layoutName='subpanel';if(modules[relModule].additionalProperties&&modules[relModule].additionalProperties.dynamic_subpanel_name){layoutName=modules[relModule].additionalProperties.dynamic_subpanel_name;}
comps.push({context:{link:fDefs.name},label:self.getDynamicSubpanelLabel(module,relModule),layout:layoutName});}}}});return{components:comps};},getDynamicSubpanelLabel:function(module,relModule){var lIndex='LBL_'+relModule.toUpperCase()+'_SUBPANEL_TITLE';var stackDef=[{key:'LBL_DEFAULT_SUBPANEL_TITLE',mod:relModule},{key:lIndex,mod:module},{key:lIndex,mod:relModule},{key:'LBL_MODULE_NAME',mod:relModule}];var label;for(var i in stackDef){if(label=app.lang.getModString(stackDef[i].key,stackDef[i].mod)){return label;}}
return relModule;},hasDynamicSubpanelDef:function(rels,relDefName,module){return rels[relDefName]&&rels[relDefName].dynamic_subpanel&&rels[relDefName].lhs_module&&rels[relDefName].rhs_module&&rels[relDefName].rhs_module===module;},isRequiredLink:function(module,link){var relatedFields=app.data.getRelateFields(module,link),requiredField=_.some(relatedFields,function(field){return field.required===true;},this);return requiredField;},_tableColumnsConfigKeyMapManager:{'likely_case':'show_worksheet_likely','likely_case_adjusted':'show_worksheet_likely','best_case':'show_worksheet_best','best_case_adjusted':'show_worksheet_best','worst_case':'show_worksheet_worst','worst_case_adjusted':'show_worksheet_worst'},_tableColumnsConfigKeyMapRep:{'likely_case':'show_worksheet_likely','best_case':'show_worksheet_best','worst_case':'show_worksheet_worst'},getColumnVisFromKeyMap:function(key,viewName){var moduleMap={'forecastsWorksheet':'rep','forecastsWorksheetTotals':'rep','forecastsWorksheetManager':'mgr','forecastsWorksheetManagerTotals':'mgr'},whichKeyMap,keyMap,returnValue;whichKeyMap=moduleMap[viewName];keyMap=(whichKeyMap==='rep')?this._tableColumnsConfigKeyMapRep:this._tableColumnsConfigKeyMapManager;returnValue=app.metadata.getModule('Forecasts','config')[keyMap[key]];if(!_.isUndefined(returnValue)){returnValue=returnValue==1}else{returnValue=true;}
return returnValue;},getSelectedUsersReportees:function(selectedUser,context){if(selectedUser.is_manager){if(_.isUndefined(selectedUser.reportees)){selectedUser.reportees=[];}
var url=app.api.buildURL('Users','filter'),post_args={"filter":[{'reports_to_id':selectedUser.id,'status':'Active'}],'fields':'full_name','max_num':1000},options={};options.success=_.bind(function(resp,status,xhr){_.each(resp.records,function(user){selectedUser.reportees.push({id:user.id,name:user.full_name});});this.set("selectedUser",selectedUser)},context);app.api.call("create",url,post_args,options);}else{context.set("selectedUser",selectedUser);}},checkForecastConfig:function(){var forecastConfigOK=true,cfg=app.metadata.getModule('Forecasts','config')||{},salesWonVals=cfg.sales_stage_won,salesLostVals=cfg.sales_stage_lost,salesWonLostVals=cfg.sales_stage_won.concat(cfg.sales_stage_lost),domVals=app.lang.getAppListStrings('sales_stage_dom');if(salesWonVals.length==0||salesLostVals.length==0||_.isEmpty(domVals)){forecastConfigOK=false;}else{forecastConfigOK=_.every(salesWonLostVals,function(val){return(val!=''&&_.has(domVals,val));},this);}
return forecastConfigOK;},isTouchDevice:function(){return Modernizr.touch;},customBuildRoute:function(moduleOrContext,id,action,inBwc){var module,moduleMeta;if(_.isEmpty(moduleOrContext)){return'';}
if(_.isString(moduleOrContext)){module=moduleOrContext;}else{module=moduleOrContext.get('module');}
if(_.isEmpty(module)||!app.bwc){return'';}
moduleMeta=app.metadata.getModule(module)||{};if(inBwc===false||(_.isUndefined(inBwc)&&!moduleMeta.isBwcEnabled)){return'';}
return app.bwc.buildRoute(module,id,app.bwc.getAction(action));},addIframeMark:function(url){var parts=url.split('?');if(parts[1]&&parts[1].indexOf('bwcFrame=1')!=-1)return url;return parts[0]+'?'+(parts[1]?parts[1]+'&bwcFrame=1':'bwcFrame=1');},rmIframeMark:function(url){var parts=url.split('?');if(!parts[1]){return url;}
return parts[0]+'?'+_.reduce(parts[1].split('&'),function(acc,item){if(item=='bwcFrame=1'){return acc;}else{return acc?acc+'&'+item:item;}},'');},getSubpanelCollection:function(ctx,module){var retCollection=undefined,mdl=_.find(ctx.children,function(child){return(child.get('module')==module);});if(mdl&&_.has(mdl.attributes,'collection')){retCollection=mdl.get('collection');}
return retCollection;},getRecordName:function(model){if(model.module==='Documents'&&model.has('document_name')){return model.get('document_name');}else if(model.has('full_name')){return model.get('full_name');}else if(model.has('first_name')&&model.has('last_name')){return model.get('first_name')+' '+model.get('last_name');}else if(model.has('last_name')){return model.get('last_name');}else{return model.get('name')||'';}},resolve409Conflict:function(error,model,callback){app.drawer.open({layout:'resolve-conflicts',context:{dataInDb:error.payload.record,modelToSave:model}},callback);},getForecastNotSetUpMessage:function(isAdmin){var langKey=(isAdmin)?'LBL_DASHLET_FORECAST_NOT_SETUP_ADMIN':'LBL_DASHLET_FORECAST_NOT_SETUP',msg=app.lang.get(langKey,'Forecasts');if(isAdmin){var linkText=app.lang.get('LBL_DASHLET_FORECAST_CONFIG_LINK_TEXT','Forecasts');msg+='  <a href="#Forecasts/config">'+linkText+'</a>';}
return msg;},getWindowLocationParameterByName:function(name,queryString){name=name.replace(/[\[]/,'\\[').replace(/[\]]/,'\\]');var regex=new RegExp('[\\?&]'+name+'=([^&#]*)','g'),matchResults=queryString.match(regex);if(matchResults&&matchResults.length>0){var results=regex.exec(matchResults[matchResults.length-1]);}
return(results===undefined||results===null)?'':decodeURIComponent(results[1].replace(/\+/g,' '));},isTruthy:function(value){if(_.isString(value)){value=value.toLowerCase();}
return value===true||value==='true'||value===1||value==='1'||value==='on'||value==='yes';}});});})(SUGAR.App);