/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
(function(app){app.events.on("app:init",function(){app.plugins.register('CteTabbing',['view'],{currentIndex:-1,currentCTEList:[],onAttach:function(component,plugin){this.once('init',function(){this.context.on('field:editable:click',this.handleClickIndex,this);$(window).on('keydown.'+this.cid,_.bind(function(e){if(this.layout.isVisible()){this.handleKeyDown(e);}},this));this.on('render',this.resetCTEList,this);},this);},onDetach:function(component,plugin){this.context.off('field:editable:click');$(window).off('keydown.'+this.cid);},handleKeyDown:function(e){if(e.which==9){e.preventDefault();if(!e.shiftKey){if(this.currentIndex+1<this.currentCTEList.length){this.currentIndex++;}else{this.currentIndex=0;}}else{if(this.currentIndex-1>=0){this.currentIndex--;}else{this.currentIndex=this.currentCTEList.length-1;}}
$(this.currentCTEList[this.currentIndex]).find("div.clickToEdit").click();}},resetCTEList:function(){var oldLength=this.currentCTEList.length
this.currentCTEList=this.$el.find('.isEditable');if(oldLength>this.currentCTEList.length){this.currentIndex--;}},handleClickIndex:function(field){_.find(this.currentCTEList,function(el,idx,list){var $el=$(el);if(_.isEqual($el.find("div.clickToEdit").data('cid'),field.cid)){this.currentIndex=idx;return true;}},this);}});app.plugins.register('ClickToEdit',['field'],{events:{'mouseenter div.clickToEdit':'showClickToEdit','mouseleave div.clickToEdit':'hideClickToEdit','click div.clickToEdit':'handleFieldClick'},isIe9Or10:$.browser.msie&&($.browser.version==='9.0'||($.browser.version==='10.0'&&!!navigator.userAgent.match(/Trident\/6\./))),_canEdit:false,_isInEdit:false,errorMessage:'',isErrorState:false,onAttach:function(component,plugin){this.once('init',_.bind(function(){if(this.checkIfCanEdit()){this.bindPluginEvents();}},this));},onDetach:function(){$(document).off('mousedown.record'+this.cid);app.utils.tooltip.destroy(this.$('[rel=tooltip]'));},bindPluginEvents:function(){this.context.on('field:editable:open',function(cid){if(this.isErrorState){this.context.trigger('field:editable:error',this.cid);}else if(this._isInEdit==true&&this.cid!==cid){if(this.type=='enum'){this.$("select").select2("close");}
if(this.type!='date'){this.setMode('list');}}},this);this.context.on('field:editable:error',function(cid){if(!_.isEqual(cid,this.cid)&&this.options.viewName=='edit'){this.setMode('list');}},this);this.on('render',function(){var cteClass='clickToEdit';if(this.action==='edit'){cteClass+=' active';this.$el.addClass('active');}else{this.$el.removeClass('active');}
if(!this.$el.hasClass('disabled')){this.$el.addClass('isEditable');this.$el.wrapInner('<div class="'+cteClass+'" data-cid="'+this.cid+'" />');}},this);if(this.context.parent){this.context.parent.on('change:selectedUser',function(){if(this.isErrorState){this.clearErrorDecoration();}},this);}},checkIfCanEdit:function(){var isEnforce=(!_.isUndefined(this.def.enforced)&&this.def.enforced===true),isClickToEdit=(!_.isUndefined(this.def.click_to_edit)&&this.def.click_to_edit===true);if(!isEnforce&&isClickToEdit){var ctx=this.context.parent||this.context;var selectedUser=ctx.get('selectedUser')||app.user.toJSON();this._canEdit=_.isEqual(app.user.get('id'),selectedUser.id);this._canEdit=(this._canEdit&&app.acl.hasAccess('write',this.module,app.user.get('id'),this.name));if(this._canEdit&&this.model.has('sales_stage')){var salesStage=this.model.get('sales_stage'),disableIfSalesStageIs=_.union(app.metadata.getModule('Forecasts','config').sales_stage_won,app.metadata.getModule('Forecasts','config').sales_stage_lost);if(salesStage&&_.indexOf(disableIfSalesStageIs,salesStage)!=-1){this._canEdit=false;}}}
return this._canEdit;},bindDomChange:function(){if(this.type==='date')return;if(!(this.model instanceof Backbone.Model))return;var self=this;var el=this.$el.find(this.fieldTag);el.on("change",function(){var value=self.validateField(self,el.val());if(value!==false){if(self.isErrorState){self.clearErrorDecoration();}
self.model.set(self.name,self.unformat(value));}else{var hb=Handlebars.compile("{{str key module context}}"),args={field_name:app.lang.get(self.def.label,self.module)};self.errorMessage=hb({'key':'LBL_EDITABLE_INVALID','module':self.module,'context':args});self.showErrors();el.select();}});if(this.isIe9Or10&&el.is("input")){_.defer(function(el){el.on("input",function(){el.focus();});},el);}},showErrors:function(){var $errorTooltips;if(this.isErrorState===false){this.isErrorState=true;var ctx=this.context.parent||this.context;ctx.trigger('field:error',this,true);this.$el.addClass('error');this.$('.error-tooltip').addClass('add-on local').removeClass('hide').css('display','inline-block');this.$('input').addClass('local-error');$errorTooltips=this.$('[rel=tooltip]');app.utils.tooltip.initialize($errorTooltips,{title:this.errorMessage,trigger:'manual'});$errorTooltips.each(function(){app.utils.tooltip.show(this);});$errorTooltips.hide();}},clearErrorDecoration:function(){app.utils.tooltip.destroy(this.$('[rel=tooltip]'));this.isErrorState=false;var ctx=this.context.parent||this.context;ctx.trigger('field:error',this,false);this.errorMessage='';},showClickToEdit:function(event){if(this._canEdit&&!this._isInEdit){var target=$(event.currentTarget);var icon='<span class="edit-icon"><i class="fa fa-pencil fa-sm"></i></span>';if(target.has('label.original').length==1){target=target.find('label.original').next();}
if(target.has('div.ellipsis_inline').length==1){target=target.find('div.ellipsis_inline');}
target.prepend(icon);}},hideClickToEdit:function(event){if(this._canEdit&&!this._isInEdit){$(event.currentTarget).find('span.edit-icon').remove();}},handleFieldClick:function(event){if(this._canEdit&&!this._isInEdit){this.context.trigger("field:editable:click",this);this.setMode('edit');if(_.isFunction(this.focus)){this.focus();}else{var $el=this.$(this.fieldTag+":first");$el.focus().val($el.val()).select();}
if(this.type!=='image'){if(_.isFunction(this.bindKeyDown)){this.bindKeyDown(_.bind(this.keyDowned,this));}else{this.$(this.fieldTag).on("keydown.record"+this.cid,{field:this},_.bind(this.keyDowned,this));}
$(document).on("mousedown.record"+this.cid,{field:this},_.bind(this.mouseClicked,this));}
if(this.type==="enum"){this.model.once('change:'+this.name,function(){_.defer(_.bind(function(){this.setMode('list');},this));},this);}
if(this.type==="date"){this.$el.closest('td').addClass('td-inline-edit');}}},keyDowned:function(evt){this.handleKeyDown.call(this,evt,evt.data.field);},mouseClicked:_.debounce(function(evt){this.fieldClose.call(this,evt,evt.data.field);},0),fieldClose:function(evt,field){var currFieldParent=field.$el,targetPlaceHolder=this.$(evt.target).parents("span[sfuuid='"+field.sfId+"']"),preventPlaceholder=this.$(evt.target).closest('.prevent-mousedown');if(preventPlaceholder.length>0||targetPlaceHolder.length>0||currFieldParent.find(":focus").length>0||!_.isEmpty(app.drawer._components)){return;}
if(this.isErrorState){this.$el.find(this.fieldTag).focus().select();return;}
this.setMode('list');},handleKeyDown:function(e,field){if(field.disposed){return;}
if(e.which==27){this.setMode('list');}else if(e.which==13){if(this.fieldValueChanged(field)){this.model.once('change:'+field.name,function(){this.setMode('list');},this);}else{this.setMode('list');}}},fieldValueChanged:function(field){var elVal=field.$el.find(field.fieldTag).val();if(field.type=='currency'||field.type=='int'){elVal=this._parsePercentage(elVal,(field.type=='currency')?undefined:0);}
if(field.type=='currency'){var diff=Math.abs(this.unformat(elVal)-this.unformat(field.value));return((Math.round(diff*100))!=0)}else if(field.type=='date'){if(_.isUndefined(elVal)){elVal=field.$el.find('div').html();}
return!_.isEqual(this.unformat(elVal),this.unformat(field.value));}else{return!_.isEqual(this.unformat(elVal),this.unformat(field.value));}},setMode:function(name){if(name==="list"){this.$(this.fieldTag).off("keydown.record"+this.cid);$(document).off("mousedown.record"+this.cid);}
if(this.isErrorState){this.clearErrorDecoration();}
app.view.Field.prototype.setMode.call(this,name);this._isInEdit=(this.action==='edit');if(this._isInEdit){this.context.trigger('field:editable:open',this.cid);}else{this.$el.removeClass('error');}
if(this.action!=='edit'&&this.type=='date'){this.$el.closest('td').removeClass('td-inline-edit');}},validateField:function(field,newValue){if(_.isUndefined(newValue)||_.isEmpty(newValue)){newValue=this.$el.find(this.fieldTag).val();}
if(field.type==='int'){newValue=this._parsePercentage(newValue,0);if(this._verifyIntValue(newValue)){return newValue;}}else if(field.type==='currency'){newValue=this._parsePercentage(newValue);if(this._verifyCurrencyValue(newValue)){return newValue;}}else if(field.type==='date'){if(this._verifyDateString(newValue)){return newValue;}}else{return newValue;}
return false;},_verifyCurrencyValue:function(value){value=value.toString().trim();var config=app.metadata.getConfig(),d_separator=app.user.getPreference('decimal_separator')||config.defaultDecimalSeparator||'.',ug_separator=app.user.getPreference('number_grouping_separator'),g_separator=!_.isUndefined(ug_separator)?ug_separator:config.defaultNumberGroupingSeparator||',',currency=app.user.getPreference('currency_id')||app.currency.getBaseCurrencyId(),currency_symbol=app.currency.getCurrencySymbol(currency),regex=new RegExp("^("+this._escapeRegexCharacter(currency_symbol)+")?(([\\d]{1,3}(?:"+this._escapeRegexCharacter(g_separator)+"?[\\d]{3})*)?((?:"+this._escapeRegexCharacter(d_separator)+"[\\d]+)))"),parts=value.match(regex);if(value.length==0||_.isNull(parts)||_.isEmpty(parts[0])||parts[0]!=value){return false;}
return true;},_escapeRegexCharacter:function(character){var needs_escape=['.','\\','+','*','?','[','^',']','$','(',')','{','}','=','!','<','>','|',':','-'];if(_.indexOf(needs_escape,character)!=-1){character='\\'+character;}
return character;},_verifyIntValue:function(value){var regex=new RegExp("^\\d+$"),match=value.toString().match(regex);if(_.isNull(match)){return false;}
if(!_.isUndefined(this.def.validation)&&this.def.validation.type=='range'){if(!_.isUndefined(this.def.validation.min)&&!_.isUndefined(this.def.validation.max)){if(value<this.def.validation.min||value>this.def.validation.max){return false}}}
return true;},_verifyDateString:function(value){return _.isUndefined(app.validation.validators.datetime(this,value))},_parsePercentage:function(value,decimals){var orig=this.model.get(this.name),config=app.metadata.getConfig(),d_separator=app.user.getPreference('decimal_separator')||config.defaultDecimalSeparator||'.',ug_separator=app.user.getPreference('number_grouping_separator'),g_separator=(!_.isUndefined(ug_separator))?ug_separator:config.defaultNumberGroupingSeparator||',',regex=new RegExp("^([+-])(([\\d]{1,3}(?:"+this._escapeRegexCharacter(g_separator)+"[\\d]{3})*|(?:[\\d]))*((?:"+this._escapeRegexCharacter(d_separator)+"[\\d]+))?)(\\%)?"),parts=value.toString().match(regex),is_percent=(parts&&parts[5]=="%"),do_addition=(parts&&parts[1]=="+"),do_subtraction=(parts&&parts[1]=="-");if(parts&&parts[0]==value&&parts[2]!="0"){var amount=this.unformat(parts[2]);if(is_percent){value=app.math.mul(app.math.div(amount,100),orig);}else{value=amount;}
if(do_addition){value=app.math.add(orig,value);}else if(do_subtraction){value=app.math.sub(orig,value);}
value=app.math.round(value,decimals);}
return this.format(value.toString());},handleHideDatePicker:function(){var $field=this.$(this.fieldTag),value=$field.val();if(_.isEmpty(value)){$field.val(this.format());return;}
value=this.unformat(value);if(!_.isEmpty(value)){this.model.set(this.name,value);this.setMode('list');return;}}});});})(SUGAR.App);