/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({plugins:['LinkedModel','Dashlet','Timeago','Pagination'],events:{'click [data-event=create_button]':'createRelatedNote','click [data-event=select_button]':'openSelectDrawer'},_defaultOptions:{limit:5,timer:0},initDashlet:function(viewName){this._initOptions();if(!this.meta.config&&this.context.get('collection')){this.context.set('skipFetch',false);this.context.set('limit',this.limit);}
if(!this.meta.config&&!this.meta.preview){this.context.on('attachment:view:fire',this.previewRecord,this);this.on('attachment:unlinkrow:fire',this.unlinkClicked,this);if(this.timer>0){this._disableAutoRefresh();this._enableAutoRefresh(this.timer);}}},_initOptions:function(){this.tbodyTag='ul[data-action="pagination-body"]';var options=_.extend(this._defaultOptions,this.settings.attributes||{});this.timer=parseInt(options['auto_refresh'],10)*60*1000;this.limit=options.limit;return this;},_disableAutoRefresh:function(){if(this.timerId){clearInterval(this.timerId);this.timerId=null;}
return this;},_enableAutoRefresh:function(msec){if(msec<=0){app.logger.error('Invalid interval timer: '+msec);return this;}
if(!_.isEmpty(this.timerId)){app.logger.error('Trying to enable an already enabled auto-refresh dashlet.');return this;}
this.timerId=setInterval(_.bind(function(){this.context.resetLoadFlag();this.layout.loadData();},this),msec);return this;},applySvgIcon:function(){var self=this,svgIconTemplate=app.template.get('attachments.svg-icon',this.module)||app.template.get('attachments.svg-icon');this.$('[data-mime]').each(function(){var mimeType=$(this).data('mime'),filetype=self.dashletConfig.supportedImageExtensions[mimeType]||self._getFileType(mimeType);$(this).attr('data-filetype',filetype).html(svgIconTemplate());});},_getFileType:function(mimeType){var filetype=mimeType.substr(mimeType.lastIndexOf('/')+1).toUpperCase();return filetype?filetype:this.dashletConfig.defaultType.toUpperCase();},bindDataChange:function(){if(this.collection){this.collection.on('reset',this.render,this);}
this.on('render',this.applySvgIcon,this);},openSelectDrawer:function(){var parentModel=this.context.get('parentModel'),linkModule=this.context.get('module'),link=this.context.get('link'),self=this;app.drawer.open({layout:'selection-list',context:{module:linkModule}},function(model){if(!model){return;}
var relatedModel=app.data.createRelatedBean(parentModel,model.id,link),options={showAlerts:true,relate:true,success:function(model){self.context.resetLoadFlag();self.context.set('skipFetch',false);self.context.loadData();},error:function(error){app.alert.show('server-error',{level:'error',messages:'ERR_GENERIC_SERVER_ERROR'});}};relatedModel.save(null,options);});},createRelatedNote:function(){var link=this.context.get('link'),parentModel=this.context.get('parentModel');this.createRelatedRecord(app.data.getRelatedModule(parentModel.module,link),link);},unlinkClicked:function(model){var self=this;var name=Handlebars.Utils.escapeExpression(app.utils.getRecordName(model)).trim();var context=app.lang.getModuleName(model.module).toLowerCase()+' '+name;app.alert.show(model.get('id')+':unlink_confirmation',{level:'confirmation',messages:app.utils.formatString(app.lang.get('NTC_UNLINK_CONFIRMATION_FORMATTED'),[context]),onConfirm:function(){model.destroy({showAlerts:true,relate:true,success:function(){if(self.disposed){return;}
self.collection.remove(model);self.render();}});}});},_dispose:function(){this._disableAutoRefresh();app.view.View.prototype._dispose.call(this);}})