/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({className:'search',initialize:function(options){this._super('initialize',[options]);this.collection=app.data.createMixedBeanCollection();this.selectedTags=[];this.v2=this.meta.v2||false;this.compOnFocusIndex=0;this.maxResponsiveWidth=540;this.isResponsiveMode=false;this.expanded=false;app.shortcuts.register(app.shortcuts.GLOBAL+'Search',['s','ctrl+alt+0'],function(){this.trigger('navigate:to:component','quicksearch-bar');},this);this.before('navigate:next:component',function(){var i=this.compOnFocusIndex,comp;while(comp=this._components[++i]){if(_.result(comp,'isFocusable')){this.compOnFocusIndex=i;return true;}}
return false;},this);this.before('navigate:previous:component',function(){var i=this.compOnFocusIndex,comp;while(comp=this._components[--i]){if(_.result(comp,'isFocusable')){this.compOnFocusIndex=i;return true;}}
return false;},this);this.on('navigate:next:component',function(){this._components[this.compOnFocusIndex].trigger('navigate:focus:receive',true);},this);this.on('navigate:previous:component',function(){this._components[this.compOnFocusIndex].trigger('navigate:focus:receive',false);},this);this.on('navigate:to:component',function(componentName){var newIndex=this.compOnFocusIndex;_.each(this._components,function(component,index){if(componentName===component.name){newIndex=index;return;}});this._components[this.compOnFocusIndex].trigger('navigate:focus:lost');this.compOnFocusIndex=newIndex;this._components[this.compOnFocusIndex].trigger('navigate:focus:receive');},this);this.on('quicksearch:close',function(keepExpanded){this.removeFocus();if(!this.expanded){return;}
this.collection.abortFetchRequest();if(keepExpanded){return;}
this.collapse();},this);this.on('quicksearch:expand',this.expand);app.events.on('app:view:change',function(){if(this.context.get('search')){_.defer(_.bind(this.expand,this));}else{_.bind(this.collapse,this);}},this);this.$el.focusin(_.bind(function(){this.$el.off('focusout');this.$el.focusout(_.bind(function(){this.$el.off('focusout');_.defer(_.bind(function(){if(this.$el.has(':focus').length===0){this.trigger('quicksearch:close',this.context.get('search'));}},this));},this));},this));this.on('quicksearch:tag:open',function(){this.$el.addClass('quicksearch-tags-open');},this);this.on('quicksearch:tag:close',function(){this.$el.removeClass('quicksearch-tags-open');},this);$(window).off('resize.quicksearch').on('resize.quicksearch',_.debounce(_.bind(this.resizeHandler,this),10));},_placeComponent:function(component){if(component.name==='quicksearch-modulelist'||component.name==='quicksearch-taglist'||component.name==='quicksearch-bar'){this.$('[data-component=searchbar]').append(component.el);}else{this._super('_placeComponent',[component]);}},removeFocus:function(){this._components[this.compOnFocusIndex].trigger('navigate:focus:lost');this.compOnFocusIndex=0;},expand:function(update){if(this.expanded&&!update){return;}
this.expanded=true;this.$el.addClass('expanded');app.router.off('route',this.routerHandler).on('route',this.routerHandler,this);this.trigger('quicksearch:expanded');this.trigger('quicksearch:button:toggle',false);if(this.isResponsiveMode){this.trigger('navigate:to:component','quicksearch-bar');return;}
var newWidth=this._calculateExpansion();if(_.isUndefined(newWidth)){return;}
var headerLayout=this.closestComponent('header');if(_.isUndefined(headerLayout)){return;}
headerLayout.trigger('view:resize',headerLayout.getModuleListMinWidth());if(update){this.$('[data-component=searchbar]').width(newWidth);}else{this.$('[data-component=searchbar]').animate({width:newWidth},{duration:100});}
headerLayout.setModuleListResize(false);},resizeHandler:function(){this._toggleResponsiveMode();if(this.expanded&&!this.isResponsiveMode){_.defer(_.bind(this.expand,this,true));}},_render:function(){this._super('_render');this._toggleResponsiveMode();},_toggleResponsiveMode:function(){this.isResponsiveMode=$(window).width()<this.maxResponsiveWidth;},routerHandler:function(){this.trigger('quicksearch:close',this.context.get('search'));},_calculateExpansion:function(){var headerLayout=this.closestComponent('header');if(_.isUndefined(headerLayout)){return;}
var searchbarStartingWidth=this.$('[data-component=searchbar]').outerWidth();var totalModuleWidth=headerLayout.getModuleListWidth();var minimumModuleWidth=headerLayout.getModuleListMinWidth();return searchbarStartingWidth+
totalModuleWidth-
minimumModuleWidth;},collapse:function(){this.expanded=false;this.$el.removeClass('expanded');this.trigger('quicksearch:collapse');app.router.off('route',this.routerHandler);this.trigger('quicksearch:button:toggle',true);if(this.isResponsiveMode){return;}
var headerLayout=this.closestComponent('header');if(_.isUndefined(headerLayout)){return;}
headerLayout.setModuleListResize(true);this.$('[data-component=searchbar]').width('');headerLayout.resize();},unbind:function(){app.router.off('route',null,this);this.$el.off();$(window).off('resize.quicksearch');this._super('unbind');}})