/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
(function(app){app.events.on("app:init",function(){app.plugins.register('EmailClientLaunch',['view','field'],{events:{'click a[data-action="email"]':'launchEmailClient'},launchEmailClient:function(event){var $link=$(event.currentTarget);if(this.useSugarEmailClient()){this.launchSugarEmailClient(this._retrieveEmailOptions($link));}},launchSugarEmailClient:function(options){_.each(['to_addresses','cc_addresses','bcc_addresses'],function(recipientType){if(options[recipientType]){options[recipientType]=this._retrieveValidRecipients(options[recipientType]);}},this);app.drawer.open({layout:'compose',context:{create:'true',module:'Emails',prepopulate:options}},_.bind(function(model){if(model){this.trigger('emailclient:close');}},this));},_retrieveValidRecipients:function(recipients){var validRecipients=[],email;recipients=_.isArray(recipients)?recipients:[recipients];_.each(recipients,function(recipient){if(recipient.bean&&_.isUndefined(recipient.email)){email=this._retrieveEmailAddressFromModel(recipient.bean);if(email){validRecipients.push(_.extend({email:email},recipient));}}else{validRecipients.push(recipient);}},this);return validRecipients;},useSugarEmailClient:function(){var emailClientPreference=app.user.getPreference('email_client_preference');return(emailClientPreference&&emailClientPreference.type==='sugar'&&app.acl.hasAccess('edit','Emails'));},addEmailOptions:function(options){this.emailOptions=this.emailOptions||{};options=options||{};if(options.related){options.related=this._cloneRelatedModel(options.related);}
this.emailOptions=_.extend({},this.emailOptions,options);},_cloneRelatedModel:function(model){var relatedModel;if(model&&model.module){relatedModel=app.data.createBean(model.module);relatedModel.set(app.utils.deepCopy(model.attributes));}
return relatedModel;},_getEmailHref:function(options){if(this.useSugarEmailClient()){return'javascript:void(0)';}else{return this._buildMailToURL(options);}},_buildMailToURL:function(options){var mailToUrl='mailto:',formattedOptions={},queryParams=[];if(options.to_addresses){mailToUrl+=this._formatRecipientsToString(options.to_addresses);}
formattedOptions.cc=this._formatRecipientsToString(options.cc_addresses);formattedOptions.bcc=this._formatRecipientsToString(options.bcc_addresses);formattedOptions.subject=options.subject;formattedOptions.body=options.text_body;_.each(['cc','bcc','subject','body'],function(option){var param;if(!_.isEmpty(formattedOptions[option])){param=option+'='+encodeURIComponent(formattedOptions[option]);queryParams.push(param);}});if(!_.isEmpty(queryParams)){mailToUrl=mailToUrl+'?'+queryParams.join('&');}
return mailToUrl;},_formatRecipientsToString:function(recipients){var emailDelim=',',emails=[],email;if(_.isArray(recipients)){_.each(recipients,function(recipient){if(_.isString(recipient)){emails.push(recipient);}else if(recipient.email){emails.push(recipient.email);}else if(recipient.bean){email=this._retrieveEmailAddressFromModel(recipient.bean);if(email){emails.push(email);}}},this);}else{emails.push(recipients);}
return emails.join(emailDelim);},_retrieveEmailAddressFromModel:function(model){var emails=model.get('email');if(_.isUndefined(emails)){return model.get('email1');}
var email,isValidEmail=function(email){return(!_.isUndefined(email)&&!_.isEmpty(email.email_address)&&email.opt_out!==true&&email.invalid_email!==true);},isValidPrimaryEmail=function(email){return isValidEmail(email)&&email.primary_address;};email=_.find(emails,isValidPrimaryEmail)||_.find(emails,isValidEmail)||{};return email.email_address;},_retrieveEmailOptions:function($link){var optionsFromLink=$link.data()||{},optionsFromController=this.emailOptions||{};if(_.isFunction(this._retrieveEmailOptionsFromLink)){optionsFromLink=this._retrieveEmailOptionsFromLink($link);}
return _.extend({},optionsFromController,optionsFromLink);},onAttach:function(){this.on('render',function(){var self=this,$emailLinks=this.$('a[data-action="email"]');$emailLinks.each(function(){var options=self._retrieveEmailOptions($(this)),href=self._getEmailHref(options);$(this).attr('href',href);});},this);}});});})(SUGAR.App);