/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
(function(app){app.events.on('app:init',function(){app.plugins.register('LinkedModel',['view','field'],{createLinkModel:function(parentModel,link){if(this.context&&this.context.parent&&this.context.parent.isCreate())
{return app.data.createBean(app.data.getRelatedModule(parentModel.module,link));}
var model=app.data.createRelatedBean(parentModel,null,link),relatedFields=app.data.getRelateFields(parentModel.module,link),parentModule=app.metadata.getModule(parentModel.module);if(parentModule&&parentModule.fields[link]&&parentModule.fields[link].populate_list){model.relatedAttributes=model.relatedAttributes||{};this._parsePopulateList(parentModule.fields[link].populate_list,parentModel,model);}
if(!_.isEmpty(relatedFields)){model.relatedAttributes=model.relatedAttributes||{};_.each(relatedFields,function(field){var parentValue=parentModel.get(field.rname);if(!parentValue&&parentModel.fields[field.rname]&&parentModel.fields[field.rname].type=='fullname'){parentValue=parentModel.get('full_name');}
model.set(field.name,parentValue);model.set(field.id_name,parentModel.get('id'));model.relatedAttributes[field.name]=parentModel.get(field.rname);model.relatedAttributes[field.id_name]=parentModel.get('id');if(field.populate_list){this._parsePopulateList(field.populate_list,parentModel,model);}},this);}
this.populateParentFields(model,parentModel);return model;},_parsePopulateList:function(populate_list,parentModel,model){_.each(populate_list,function(target,source){source=_.isNumber(source)?target:source;if(!_.isUndefined(parentModel.get(source))&&app.acl.hasAccessToModel('edit',model,target)){model.set(target,parentModel.get(source));model.relatedAttributes[target]=parentModel.get(source);}},this);},createRelatedRecord:function(module,link,id){var bwcExceptions=['Emails'],moduleMeta=app.metadata.getModule(module);if(moduleMeta&&moduleMeta.isBwcEnabled&&!_.contains(bwcExceptions,module)){this.routeToBwcCreate(module,id);}else{this.openCreateDrawer(module,link);}},routeToBwcCreate:function(module,id){var proto=Object.getPrototypeOf(this);if(_.isFunction(proto.routeToBwcCreate)){return proto.routeToBwcCreate.call(this,module);}
var parentModel=this.context.parent.get('model'),link=this.context.get('link');app.bwc.createRelatedRecord(module,parentModel,link,id);},openCreateDrawer:function(module,link){var proto=Object.getPrototypeOf(this);if(_.isFunction(proto.openCreateDrawer)){return proto.openCreateDrawer.call(this,module,link);}
link=link||this.context.get('link');var context=(this.context.get('name')==='tabbed-dashlet')?this.context:(this.context.parent||this.context);var parentModel=context.get('model')||context.parent.get('model'),model=this.createLinkModel(parentModel,link),self=this;app.drawer.open({layout:'create-actions',context:{create:true,module:model.module,model:model}},function(context,model){if(!model){return;}
self.context.resetLoadFlag();self.context.set('skipFetch',false);if(_.isFunction(self.loadData)){self.loadData();}});},populateParentFields:function(model,parentModel){var parentModule=parentModel.module||parentModel.get("module")||parentModel.get("_module");_.each(model.fields,function(def,name){if(def.type&&def.type=="parent"){if(app.lang.getAppListStrings(def.options)[parentModule]){model.set(def.type_name,parentModule);if(parentModel.get("id")){model.set(def.id_name,parentModel.get("id"));model.set(def.name,parentModel.get("full_name")||parentModel.get("document_name")||parentModel.get("name")||"");}}}});if(parentModule=="Contacts"&&parentModel.get("account_id")&&model.get("contact_id")){model.set({parent_type:"Accounts",parent_id:parentModel.get("account_id"),parent_name:parentModel.get("account_name")});}}});});})(SUGAR.App);