/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'ConfigPanelView',events:{'click #btnAddCustomRange a':'addCustomRange','click #btnAddCustomRangeWithoutProbability a':'addCustomRange','click .addCustomRange':'addCustomRange','click .removeCustomRange':'removeCustomRange','keyup input[type=text]':'updateCustomRangeLabel','change :radio':'selectionHandler'},fieldsMeta:{},forecastRangesField:{},bucketsDomField:{},categoryRangesField:{},includedCommitStages:[],disableRanges:false,selectedRange:'',fieldRanges:{},initialize:function(options){this._super('initialize',[options]);_.each(_.first(this.meta.panels).fields,function(field){this.fieldsMeta[field.name]=field;if(field.name==='category_ranges'){delete this.fieldsMeta.category_ranges.name;}},this);this.forecastRangesField=this.fieldsMeta.forecast_ranges;this.bucketsDomField=this.fieldsMeta.buckets_dom;this.categoryRangesField=this.fieldsMeta.category_ranges;this.includedCommitStages=this.model.get('commit_stages_included');this.forecastRangesField.value=this.model.get('forecast_ranges');this.bucketsDomField.value=this.model.get('buckets_dom');this.disableRanges=this.model.get('has_commits');this.selectedRange=this.model.get('forecast_ranges');},_updateTitleValues:function(){var forecastRanges=this.model.get('forecast_ranges'),rangeObjs=this.model.get(forecastRanges+'_ranges'),tmpArr=[],str='',aSort=function(a,b){if(a.min<b.min){return-1;}else if(a.min>b.min){return 1;}}
_.each(rangeObjs,function(value,key){if(key.indexOf('without_probability')===-1){tmpArr.push({min:value.min,max:value.max});}});tmpArr.sort(aSort);_.each(tmpArr,function(val){str+=val.min+'% - '+val.max+'%, ';});this.titleSelectedValues=str.slice(0,str.length-2);this.titleSelectedRange=app.lang.getAppListStrings('forecasts_config_ranges_options_dom')[forecastRanges];},_updateTitleTemplateVars:function(){this.titleTemplateVars={title:this.titleViewNameTitle,message:this.titleSelectedRange,selectedValues:this.titleSelectedValues,viewName:this.name};},bindDataChange:function(){this.model.on('change:show_binary_ranges change:show_buckets_ranges change:show_custom_buckets_ranges',function(){this.updateTitle();},this);this.model.on('change:forecast_ranges',function(model){this.updateTitle();if(model.get('forecast_ranges')==='show_custom_buckets'){this.updateCustomRangesCheckboxes();}},this);},_render:function(){this._super('_render');this.$(':radio:checked').trigger('change');if(this.model.get('forecast_ranges')==='show_custom_buckets'){this.updateCustomRangesCheckboxes();}},selectionHandler:function(event){var newValue=$(event.target).val(),oldValue=this.selectedRange,bucket_dom=this.bucketsDomField.options[newValue],elToHide=this.$('#'+oldValue+'_ranges'),elToShow=this.$('#'+newValue+'_ranges');this.selectedRange=newValue;if(elToShow.children().length===0){if(newValue==='show_custom_buckets'){this._customSelectionHandler(newValue,elToShow);}else{this._selectionHandler(newValue,elToShow);}
this.connectSliders.call(this,newValue,this.fieldRanges);}
if(elToHide){elToHide.toggleClass('hide',true);}
if(elToShow){elToShow.toggleClass('hide',false);}
this.model.set({forecast_ranges:newValue,buckets_dom:bucket_dom});},_selectionHandler:function(elementVal,showElement){var bucketDomStrings=app.lang.getAppListStrings(this.bucketsDomField.options[elementVal]);this.fieldRanges[elementVal]={};showElement.append('<p>'+app.lang.get('LBL_FORECASTS_CONFIG_'+elementVal.toUpperCase()+'_RANGES_DESCRIPTION','Forecasts',this)+'</p>');_.each(bucketDomStrings,function(label,key){if(key!='exclude'){var rangeField,model=new Backbone.Model(),fieldSettings;model.set(key,this.model.get(elementVal+'_ranges')[key]);fieldSettings={view:this,def:this.fieldsMeta.category_ranges[key],viewName:'edit',context:this.context,module:this.module,model:model,meta:app.metadata.getField('range')};rangeField=app.view.createField(fieldSettings);showElement.append('<b>'+label+':</b>').append(rangeField.el);rangeField.render();this.fieldRanges[elementVal][key]=rangeField;rangeField.sliderDoneDelegate=function(category,key,view){return function(value){this.view.updateRangeSettings(category,key,value);};}(elementVal,key,this);}},this);showElement.append($('<p>'+app.lang.get('LBL_FORECASTS_CONFIG_RANGES_EXCLUDE_INFO','Forecasts')+'</p>'));},_customSelectionHandler:function(elementVal,showElement){var bucketDomOptions={},elValRanges=elementVal+'_ranges',bucketDomStrings=app.lang.getAppListStrings(this.bucketsDomField.options[elementVal]),rangeField,_ranges=_.clone(this.model.get(elValRanges));this.fieldRanges[elementVal]={};showElement.append('<p>'+app.lang.get('LBL_FORECASTS_CONFIG_'+elementVal.toUpperCase()+'_RANGES_DESCRIPTION','Forecasts',this)+'</p>');if(!this.model.has(elValRanges)){this.model.set(elValRanges,{});}
_.each(bucketDomStrings,function(label,key){if(_.isUndefined(_ranges[key])){_ranges[key]={min:0,max:100,in_included_total:false};}else{_ranges[key].in_included_total=(_.contains(this.includedCommitStages,key));}
bucketDomOptions[key]=label;},this);this.model.set(elValRanges,_ranges);this.model.set(elementVal+'_options',bucketDomOptions);this.model.on('change:'+elementVal+'_options',function(event){this.validateCustomRangeLabels(elementVal);},this);this._renderCustomRangesLayout(showElement,elementVal);_.each(bucketDomStrings,function(label,key){rangeField=this._renderCustomRange(key,label,showElement,elementVal);this.fieldRanges[elementVal][key]=rangeField;},this);if(this._getLastCustomRangeIndex(elementVal,'custom')){this.$('#btnAddCustomRange').hide();}
if(this._getLastCustomRangeIndex(elementVal,'custom_without_probability')){this.$('#btnAddCustomRangeWithoutProbability').hide();}},_renderCustomRangesLayout:function(showElement,category){var template=app.template.getView('config-ranges.customRangesDefault','Forecasts'),mdl={category:category};showElement.append(template(mdl));},_renderCustomRange:function(key,label,showElement,category){var customType=key,customIndex=0,isExclude=false,currentPlaceholder=showElement,rangeField,model=new Backbone.Model(),fieldSettings,lastCustomRange;if(key.substring(0,26)=='custom_without_probability'){customType='custom_without_probability';customIndex=key.substring(27);currentPlaceholder=this.$('#plhCustomWithoutProbability');}else if(key.substring(0,6)=='custom'){customType='custom';customIndex=key.substring(7);currentPlaceholder=this.$('#plhCustom');}else if(key.substring(0,7)=='exclude'){customType='custom_default';currentPlaceholder=this.$('#plhExclude');isExclude=true;}else{customType='custom_default';currentPlaceholder=this.$('#plhCustomDefault');}
model.set(key,this.model.get(category+'_ranges')[key]);var fieldDef=this.fieldsMeta.category_ranges[key]||this.fieldsMeta.category_ranges[customType];fieldSettings={view:this,def:_.clone(fieldDef),viewName:'forecastsCustomRange',context:this.context,module:this.module,model:model,meta:app.metadata.getField('range')};fieldSettings.def.name=key;fieldSettings.def.view='forecastsCustomRange';fieldSettings.def.enabled=true;rangeField=app.view.createField(fieldSettings);currentPlaceholder.append(rangeField.el);rangeField.label=label;rangeField.customType=customType;rangeField.customIndex=+customIndex;rangeField.isExclude=isExclude;rangeField.in_included_total=(_.contains(this.includedCommitStages,key));rangeField.category=category;if(key=='include'){rangeField.isReadonly=true;}
rangeField.render();rangeField.$(rangeField.fieldTag).noUiSlider('enable');lastCustomRange=this._getLastCustomRange(category,rangeField.customType);if(lastCustomRange){lastCustomRange.$('.addCustomRange').parent().hide();}
if(_.isEmpty(rangeField.label)){rangeField.$('.control-group').addClass('error');}else{rangeField.$('.control-group').removeClass('error');}
rangeField.sliderDoneDelegate=function(category,key,view){return function(value){this.view.updateRangeSettings(category,key,value);};}(category,key,this);return rangeField;},_getLastCustomRangeIndex:function(category,customType){var lastCustomRangeIndex=0;if(this.fieldRanges[category]){_.each(this.fieldRanges[category],function(range){if(range.customType==customType&&range.customIndex>lastCustomRangeIndex){lastCustomRangeIndex=range.customIndex;}},this);}
return lastCustomRangeIndex;},_getLastCustomRange:function(category,customType){if(!_.isEmpty(this.fieldRanges[category])){var lastCustomRange=undefined;_.each(this.fieldRanges[category],function(range){if(range.customType==customType&&(_.isUndefined(lastCustomRange)||range.customIndex>lastCustomRange.customIndex)){lastCustomRange=range;}},this);if(_.isUndefined(lastCustomRange)){if(customType=='custom'){lastCustomRange=this.fieldRanges[category].upside||this.fieldRanges[category].include;}else{lastCustomRange=this.fieldRanges[category].exclude;}}}
return lastCustomRange;},addCustomRange:function(event){var self=this,category=$(event.currentTarget).data('category'),customType=$(event.currentTarget).data('type'),categoryRange=category+'_ranges',categoryOptions=category+'_options',ranges=_.clone(this.model.get(categoryRange)),bucketDomOptions=_.clone(this.model.get(categoryOptions));if(_.isUndefined(category)||_.isUndefined(customType)||_.isUndefined(ranges)||_.isUndefined(bucketDomOptions)){return false;}
var showElement=(customType=='custom')?this.$('#plhCustom'):this.$('#plhCustomWithoutProbability'),label=app.lang.get('LBL_FORECASTS_CUSTOM_RANGES_DEFAULT_NAME','Forecasts'),rangeField,lastCustomRange=this._getLastCustomRange(category,customType),lastCustomRangeIndex=this._getLastCustomRangeIndex(category,customType);lastCustomRangeIndex++;var key=customType+'_'+lastCustomRangeIndex;if(customType!='custom'){ranges[key]={min:0,max:0,in_included_total:false};}else if(ranges.exclude.max-ranges.exclude.min>3){ranges[key]={min:parseInt(ranges.exclude.max,10)-1,max:parseInt(ranges.exclude.max,10),in_included_total:false};ranges.exclude.max=parseInt(ranges.exclude.max,10)-2;if(this.fieldRanges[category].exclude.$el){this.fieldRanges[category].exclude.$(this.fieldRanges[category].exclude.fieldTag).noUiSlider('move',{handle:'upper',to:ranges.exclude.max});}}else if(ranges[lastCustomRange.name].max-ranges[lastCustomRange.name].min>3){ranges[key]={min:parseInt(ranges[lastCustomRange.name].min,10),max:parseInt(ranges[lastCustomRange.name].min,10)+1,in_included_total:false};ranges[lastCustomRange.name].min=parseInt(ranges[lastCustomRange.name].min,10)+2;if(lastCustomRange.$el){lastCustomRange.$(lastCustomRange.fieldTag).noUiSlider('move',{handle:'lower',to:ranges[lastCustomRange.name].min});}}else{ranges[key]={min:parseInt(ranges[lastCustomRange.name].min,10)-2,max:parseInt(ranges[lastCustomRange.name].min,10)-1,in_included_total:false};}
this.model.set(categoryRange,ranges);rangeField=this._renderCustomRange(key,label,showElement,category);if(rangeField){this.fieldRanges[category][key]=rangeField;}
bucketDomOptions[key]=label;this.model.set(categoryOptions,bucketDomOptions);rangeField.$(':checkbox').each(function(){var $el=$(this);$el.on('click',_.bind(self.updateCustomRangeIncludeInTotal,self));app.accessibility.run($el,'click');});if(customType=='custom'){this.$('#btnAddCustomRange').hide();this.connectSliders.call(this,category,this.fieldRanges);}else{this.$('#btnAddCustomRangeWithoutProbability').hide();_.each(this.fieldRanges[category],function(item){if(item.customType==customType&&item.customIndex<lastCustomRangeIndex&&item.$el){item.$('.addCustomRange').parent().hide();}},this);}
this.updateCustomRangesCheckboxes();},removeCustomRange:function(event){var category=$(event.currentTarget).data('category'),fieldKey=$(event.currentTarget).data('key'),categoryRanges=category+'_ranges',categoryOptions=category+'_options',ranges=_.clone(this.model.get(categoryRanges)),bucketDomOptions=_.clone(this.model.get(categoryOptions));if(_.isUndefined(category)||_.isUndefined(fieldKey)||_.isUndefined(this.fieldRanges[category])||_.isUndefined(this.fieldRanges[category][fieldKey])||_.isUndefined(ranges)||_.isUndefined(bucketDomOptions))
{return false;}
var range,previousCustomRange,lastCustomRangeIndex,lastCustomRange;range=this.fieldRanges[category][fieldKey];if(_.indexOf(['include','upside','exclude'],range.name)!=-1){return false;}
if(range.customType=='custom'){_.each(this.fieldRanges[category],function(item){if(item.customType=='custom'&&item.customIndex<range.customIndex){previousCustomRange=item;}},this);if(_.isUndefined(previousCustomRange)){previousCustomRange=(this.fieldRanges[category].upside)?this.fieldRanges[category].upside:this.fieldRanges[category].include;}
ranges[previousCustomRange.name].min=+ranges[range.name].min;if(previousCustomRange.$el){previousCustomRange.$(previousCustomRange.fieldTag).noUiSlider('move',{handle:'lower',to:ranges[previousCustomRange.name].min});}}
this.includedCommitStages=_.without(this.includedCommitStages,range.name)
range.$(':checkbox').off('click');this.fieldRanges[category][range.name].remove();delete ranges[range.name];delete this.fieldRanges[category][range.name];delete bucketDomOptions[range.name];this.model.set(categoryOptions,bucketDomOptions);this.model.set(categoryRanges,ranges);lastCustomRangeIndex=this._getLastCustomRangeIndex(category,range.customType);if(range.customType=='custom'){if(lastCustomRangeIndex==0){this.$('#btnAddCustomRange').show();}
this.connectSliders.call(this,category,this.fieldRanges);}else{if(lastCustomRangeIndex==0){this.$('#btnAddCustomRangeWithoutProbability').show();}}
lastCustomRange=this._getLastCustomRange(category,range.customType);if(lastCustomRange.$el){lastCustomRange.$('.addCustomRange').parent().show();}
this.updateCustomRangesCheckboxes();},updateCustomRangeLabel:function(event){var category=$(event.target).data('category'),fieldKey=$(event.target).data('key'),categoryOptions=category+'_options',bucketDomOptions=_.clone(this.model.get(categoryOptions));if(category&&fieldKey&&bucketDomOptions){bucketDomOptions[fieldKey]=$(event.target).val();this.model.set(categoryOptions,bucketDomOptions);}},validateCustomRangeLabels:function(category){var opts=this.model.get(category+'_options'),hasErrors=false,range;_.each(opts,function(label,key){range=this.fieldRanges[category][key];if(_.isEmpty(label.trim())){range.$('.control-group').addClass('error');hasErrors=true;}else{range.$('.control-group').removeClass('error');}},this);var saveBtn=this.layout.layout.$('[name=save_button]');if(saveBtn){if(hasErrors){saveBtn.addClass('disabled');}else if(!hasErrors&&saveBtn.hasClass('disabled')){saveBtn.removeClass('disabled');}}},updateCustomRangeIncludeInTotal:function(event){var category=$(event.target).data('category'),fieldKey=$(event.target).data('key'),categoryRanges=category+'_ranges',ranges;if(category&&fieldKey){ranges=_.clone(this.model.get(categoryRanges));if(ranges&&ranges[fieldKey]){if(fieldKey!=='exclude'&&fieldKey.indexOf('custom_without_probability')==-1){var isChecked=$(event.target).is(':checked');ranges[fieldKey].in_included_total=isChecked;if(isChecked){this.includedCommitStages.push(fieldKey);}else{this.includedCommitStages=_.without(this.includedCommitStages,fieldKey)}
this.model.set('commit_stages_included',this.includedCommitStages);}else{ranges[fieldKey].in_included_total=false;}
this.model.set(categoryRanges,ranges);this.updateCustomRangesCheckboxes();}}},updateCustomRangesCheckboxes:function(){var els=this.$('#plhCustomDefault :checkbox, #plhCustom :checkbox'),len=els.length,$el,fieldKey,i;for(i=0;i<len;i++){$el=$(els[i]);fieldKey=$el.data('key');$el.attr('disabled',true);$el.off('click');if(fieldKey!=='include'&&(i==this.includedCommitStages.length-1||i==this.includedCommitStages.length)){$el.attr('disabled',false);$el.on('click',_.bind(this.updateCustomRangeIncludeInTotal,this));app.accessibility.run($el,'click');}}},updateRangeSettings:function(category,range,value){var catRange=category+'_ranges',setting=_.clone(this.model.get(catRange));if(category=='show_custom_buckets'){value.in_included_total=setting[range].in_included_total||false;}
setting[range]=value;this.model.set(catRange,setting);},connectSliders:function(ranges,sliders){var rangeSliders=sliders[ranges];if(ranges=='show_binary'){rangeSliders.include.sliderChangeDelegate=function(value){rangeSliders.include.$(rangeSliders.include.fieldTag).noUiSlider('move',{handle:'upper',to:rangeSliders.include.def.maxRange});this.view.setExcludeValueForLastSlider(value,ranges,rangeSliders.include);};}else if(ranges=='show_buckets'){rangeSliders.include.sliderChangeDelegate=function(value){rangeSliders.include.$(rangeSliders.include.fieldTag).noUiSlider('move',{handle:'upper',to:rangeSliders.include.def.maxRange});rangeSliders.upside.$(rangeSliders.upside.fieldTag).noUiSlider('move',{handle:'upper',to:value.min-1});if(value.min<=rangeSliders.upside.$(rangeSliders.upside.fieldTag).noUiSlider('value')[0]+1){rangeSliders.upside.$(rangeSliders.upside.fieldTag).noUiSlider('move',{handle:'lower',to:value.min-2});}};rangeSliders.upside.sliderChangeDelegate=function(value){rangeSliders.include.$(rangeSliders.include.fieldTag).noUiSlider('move',{handle:'lower',to:value.max+1});this.view.setExcludeValueForLastSlider(value,ranges,rangeSliders.upside);};}else if(ranges=='show_custom_buckets'){var i,max,customSliders=_.sortBy(_.filter(rangeSliders,function(item){return item.customType=='custom';}),function(item){return parseInt(item.customIndex,10);}),probabilitySliders=_.union(rangeSliders.include,rangeSliders.upside,customSliders,rangeSliders.exclude);if(probabilitySliders.length){for(i=0,max=probabilitySliders.length;i<max;i++){probabilitySliders[i].connectedSlider=(probabilitySliders[i+1])?probabilitySliders[i+1]:null;probabilitySliders[i].connectedToSlider=(probabilitySliders[i-1])?probabilitySliders[i-1]:null;probabilitySliders[i].sliderChangeDelegate=function(value,populateEvent){if(this.name=='include'){this.$(this.fieldTag).noUiSlider('move',{handle:'upper',to:this.def.maxRange});}else if(this.name=='exclude'){this.$(this.fieldTag).noUiSlider('move',{handle:'lower',to:this.def.minRange});}
if(this.connectedSlider){this.connectedSlider.$(this.connectedSlider.fieldTag).noUiSlider('move',{handle:'upper',to:value.min-1});if(value.min<=this.connectedSlider.$(this.connectedSlider.fieldTag).noUiSlider('value')[0]+1){this.connectedSlider.$(this.connectedSlider.fieldTag).noUiSlider('move',{handle:'lower',to:value.min-2});}
if(_.isUndefined(populateEvent)||populateEvent=='down'){this.connectedSlider.sliderChangeDelegate.call(this.connectedSlider,{min:this.connectedSlider.$(this.connectedSlider.fieldTag).noUiSlider('value')[0],max:this.connectedSlider.$(this.connectedSlider.fieldTag).noUiSlider('value')[1]},'down');}}
if(this.connectedToSlider){this.connectedToSlider.$(this.connectedToSlider.fieldTag).noUiSlider('move',{handle:'lower',to:value.max+1});if(value.max>=this.connectedToSlider.$(this.connectedToSlider.fieldTag).noUiSlider('value')[1]-1){this.connectedToSlider.$(this.connectedToSlider.fieldTag).noUiSlider('move',{handle:'upper',to:value.max+2});}
if(_.isUndefined(populateEvent)||populateEvent=='up'){this.connectedToSlider.sliderChangeDelegate.call(this.connectedToSlider,{min:this.connectedToSlider.$(this.connectedToSlider.fieldTag).noUiSlider('value')[0],max:this.connectedToSlider.$(this.connectedToSlider.fieldTag).noUiSlider('value')[1]},'up');}}};}}}},setExcludeValueForLastSlider:function(value,ranges,slider){var excludeRange={min:0,max:100},settingName=ranges+'_ranges',setting=_.clone(this.model.get(settingName));excludeRange.max=value.min-1;excludeRange.min=slider.def.minRange;setting.exclude=excludeRange;this.model.set(settingName,setting);}})