/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({previous_type:'',arrow:'',initial_total:'',total:0,hasAccess:true,hasDataAccess:true,noDataAccessTemplate:undefined,total_field:'',initialize:function(options){this._super('initialize',[options]);this.total_field=this.total_field||this.name;this.hasAccess=app.utils.getColumnVisFromKeyMap(this.name,'forecastsWorksheet');this.hasDataAccess=app.acl.hasAccess('read','ForecastWorksheets',app.user.get('id'),this.name);if(this.hasDataAccess===false){this.noDataAccessTemplate=app.template.getField('base','noaccess')(this);}
this.before('render',function(){if(!this.hasAccess){return false;}
this.arrow=this._getArrowIconColorClass(this.total,this.initial_total);this.checkIfNeedsCommit();return true;},this);$(window).on('resize.datapoints',_.bind(this.resize,this));this.on('render',function(){if(!this.hasAccess){return false;}
this.resize();return true;},this);},checkIfNeedsCommit:function(){if(!_.isEqual(this.initial_total,'')&&app.math.isDifferentWithPrecision(this.total,this.initial_total)){this.context.trigger('forecasts:worksheet:needs_commit',null);}},_dispose:function(){$(window).off('resize.datapoints');clearInterval(this.resizeDetectTimer);this._super('_dispose');},getPlaceholder:function(){if(this.hasAccess){return this._super('getPlaceholder');}
return'';},adjustDatapointLayout:function(){if(this.hasAccess){var parentMarginLeft=this.view.$('.topline .datapoints').css('margin-left'),parentMarginRight=this.view.$('.topline .datapoints').css('margin-right'),timePeriodWidth=this.view.$('.topline .span4').outerWidth(true),toplineWidth=this.view.$('.topline ').width(),collection=this.view.$('.topline div.pull-right').children('span'),collectionWidth=parseInt(parentMarginLeft)+parseInt(parentMarginRight);collection.each(function(index){collectionWidth+=$(this).children('div.datapoint').outerWidth(true);});if((collectionWidth+timePeriodWidth)>toplineWidth){this.view.$('.topline div.hr').show();this.view.$('.info .last-commit').find('div.hr').show();this.view.$('.topline .datapoints').removeClass('span8').addClass('span12');this.view.$('.info .last-commit .datapoints').removeClass('span8').addClass('span12');this.view.$('.info .last-commit .commit-date').removeClass('span4').addClass('span12');}else{this.view.$('.topline div.hr').hide();this.view.$('.info .last-commit').find('div.hr').hide();this.view.$('.topline .datapoints').removeClass('span12').addClass('span8');this.view.$('.info .last-commit .datapoints').removeClass('span12').addClass('span8');this.view.$('.info .last-commit .commit-date').removeClass('span12').addClass('span4');var lastCommitHeight=this.view.$('.info .last-commit .commit-date').height();this.view.$('.info .last-commit .datapoints div.datapoint').height(lastCommitHeight);}
var index=this.$el.index(),width=this.$('div.datapoint').outerWidth(),datapointLength=this.view.$('.info .last-commit .datapoints div.datapoint').length,sel=this.view.$('.last-commit .datapoints div.datapoint:nth-child('+index+')');if(datapointLength>2&&index<=2||datapointLength==2&&index==1){var widthMod=(app.lang.direction==='rtl')?7:8;$(sel).width(width-widthMod);}else{$(sel).width(width);}}},resize:function(){if(this.resizeDetectTimer){clearTimeout(this.resizeDetectTimer);}
this.resizeDetectTimer=setTimeout(_.bind(function(){this.adjustDatapointLayout();},this),250);},bindDataChange:function(){if(!this.hasAccess){return;}
this.context.on('change:selectedUser change:selectedTimePeriod',function(){this.initial_total='';this.total=0;this.arrow='';},this);this.collection.on('reset',this._onCommitCollectionReset,this);this.context.on('forecasts:worksheet:totals',this._onWorksheetTotals,this);this.context.on('forecasts:worksheet:committed',this._onWorksheetCommit,this);},_onCommitCollectionReset:function(collection){var model=_.first(collection.models);if(!_.isUndefined(model)){this.initial_total=model.get(this.total_field);if(!this.disposed){this.render();}}},_onWorksheetTotals:function(totals,type){var field=this.total_field;if(type=='manager'){field=field.split('_')[0]+'_adjusted';}
this.total=totals[field];this.previous_type=type;if(!this.disposed){this.render();}},_onWorksheetCommit:function(type,forecast){var field=this.total_field;if(type=='manager'){field=field.split('_')[0]+'_adjusted';}
this.total=forecast[field];this.initial_total=forecast[field];this.arrow='';if(!this.disposed){this.render();}},_getArrowIconColorClass:function(newValue,oldValue){var cls='';if(app.math.isDifferentWithPrecision(newValue,oldValue)){cls=(newValue>oldValue)?' fa-arrow-up font-green':' fa-arrow-down font-red';}
return cls;}})