/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'RecordView',plugins:['ToggleMoreLess','Editable','ErrorDecoration'],fallbackFieldTemplate:'detail',switching:false,hiddenPanelExists:false,initialize:function(options){app.view.View.prototype.initialize.call(this,options);this.action='detail';this._delegateEvents();this.delegateButtonEvents();this.collection=app.data.createBeanCollection(this.module);this._viewAlerts=[];this.alerts={showInvalidModel:function(){if(!this instanceof app.view.View){app.logger.error('This method should be invoked by Function.prototype.call(), passing in as argument'+'an instance of this view.');return;}
var name='invalid-data';this._viewAlerts.push(name);app.alert.show(name,{level:'error',messages:'ERR_RESOLVE_ERRORS'});},showNoAccessError:function(){if(!this instanceof app.view.View){app.logger.error('This method should be invoked by Function.prototype.call(), passing in as argument'+'an instance of this view.');return;}
app.alert.dismiss('data:sync:error');app.alert.show('server-error',{level:'error',messages:'ERR_HTTP_404_TEXT_LINE1'});this.handleCancel();var route=app.router.buildRoute(this.module);app.router.navigate(route,{trigger:true});}};},toggleButtons:function(enable){if(this.layout.previewEdit){var previewLayout=this.layout.getComponent('preview-header');previewLayout.getField('save_button').setDisabled(!enable);previewLayout.getField('cancel_button').setDisabled(!enable);}},handleSave:function(){if(this.disposed){return;}
this._saveModel();this.layout.trigger('preview:edit:complete');this.unsetContextAction();this.toggleFields(this.editableFields,false);},cancelClicked:function(){this.model.revertAttributes();this.toggleFields(this.editableFields,false);this._dismissAllAlerts();this.clearValidationErrors(this.editableFields);this.unsetContextAction();this.layout.trigger('preview:edit:complete');},_delegateEvents:function(){app.events.on('preview:render',this._renderPreview,this);app.events.on('preview:collection:change',this.updateCollection,this);app.events.on('preview:close',this.closePreview,this);app.events.on('preview:module:update',this.updatePreviewModule,this);if(this.layout){this.layout.on('preview:pagination:fire',this.switchPreview,this);}},delegateButtonEvents:function(){if(this.layout&&this.layout.previewEdit){this.context.on('button:save_button:click',this.saveClicked,this);this.context.on('button:cancel_button:click',this.cancelClicked,this);this.layout.on('preview:edit',this.handleEdit,this);}},updateCollection:function(collection){if(this.collection){this.collection.reset(collection.models);this.showPreviousNextBtnGroup();}},updatePreviewModule:function(module){this.previewModule=module;},filterCollection:function(){this.collection.remove(_.filter(this.collection.models,function(model){return!app.acl.hasAccessToModel('view',model);},this),{silent:true});},_renderHtml:function(){this.showPreviousNextBtnGroup();app.view.View.prototype._renderHtml.call(this);},showPreviousNextBtnGroup:function(){if(!this.model||!this.layout||!this.collection){return;}
var collection=this.collection;if(!collection.size()){this.layout.hideNextPrevious=true;}
var recordIndex=collection.indexOf(collection.get(this.model.id));this.layout.previous=collection.models[recordIndex-1]?collection.models[recordIndex-1]:undefined;this.layout.next=collection.models[recordIndex+1]?collection.models[recordIndex+1]:undefined;this.layout.hideNextPrevious=_.isUndefined(this.layout.previous)&&_.isUndefined(this.layout.next);this.layout.trigger('preview:pagination:update');},_renderPreview:function(model,collection,fetch,previewId){var self=this;if(app.drawer&&!app.drawer.isActive(this.$el)){return;}
if(this.model&&model&&(this.model.get('id')==model.get('id')&&previewId==this.previewId)){app.events.trigger('list:preview:decorate',false);app.events.trigger('preview:close');return;}
if(app.metadata.getModule(model.module).isBwcEnabled){return;}
if(model){var viewName='preview',previewMeta=app.metadata.getView(model.module,'preview'),recordMeta=app.metadata.getView(model.module,'record');if(_.isEmpty(previewMeta)||_.isEmpty(previewMeta.panels)){viewName='record';}
this.meta=this._previewifyMetadata(_.extend({},recordMeta,previewMeta));this.renderPreview(model,collection);fetch&&model.fetch({showAlerts:true,view:viewName});}
this.previewId=previewId;},switchModel:function(model){this.model&&this.model.abortFetchRequest();this.stopListening(this.model);this.model=model;this.listenTo(this.model,'destroy',function(){app.events.trigger('list:preview:decorate',false);app.events.trigger('preview:close');});},renderPreview:function(model,newCollection){if(newCollection){this.collection.reset(newCollection.models);}
if(model){this.switchModel(model);if(this.layout){this.layout.trigger('previewheader:ACLCheck',model);}
if(this.previewModule&&this.previewModule==='Activities'){this.layout.previewEdit=false;this.render();this.layout.hideNextPrevious=true;this.layout.trigger('preview:pagination:update');}else{this.render();}
app.events.trigger('preview:open',this);app.events.trigger('list:preview:decorate',this.model,this);}},_previewifyMetadata:function(meta){this.hiddenPanelExists=false;_.each(meta.panels,function(panel){if(panel.header){panel.header=false;panel.fields=_.filter(panel.fields,function(field){return field.type!='favorite'&&field.type!='follow';});}
if(!this.hiddenPanelExists&&panel.hide){this.hiddenPanelExists=true;}},this);return meta;},switchPreview:function(data,index,id,module){var currID=id||this.model.get('id'),currIndex=index||_.indexOf(this.collection.models,this.collection.get(currID));if(this.switching||this.collection.models.length<2){return;}
this.switching=true;if(data.direction==='left'&&(currID===_.first(this.collection.models).get('id'))||data.direction==='right'&&(currID===_.last(this.collection.models).get('id'))){this.switching=false;return;}else{data.direction==='left'?currIndex-=1:currIndex+=1;app.events.trigger('preview:render',this.collection.models[currIndex],null,true);this.switching=false;}},closePreview:function(){if(_.isUndefined(app.drawer)||app.drawer.isActive(this.$el)){this.switching=false;delete this.model;this.collection.reset();}},bindDataChange:function(){if(this.collection){this.collection.on('reset',this.filterCollection,this);this.collection.on('remove',function(model){if(model&&this.model&&(this.model.get('id')==model.get('id'))){app.events.trigger('list:preview:decorate',false);app.events.trigger('preview:close');}},this);}},handleEdit:function(){this.setEditableFields();this.toggleFields(this.editableFields,true);this.toggleButtons(true);},setEditableFields:function(){var self=this;this.editableFields=_.reject(this.fields,function(field){return field.def.readOnly||field.def.calculated||field.def.previewEdit===false||!app.acl.hasAccessToModel('edit',self.model,field.name);});},hasUnsavedChanges:function(){if(_.isUndefined(this.model)){return false;}
return this._super('hasUnsavedChanges');}})