/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({plugins:['ErrorDecoration'],events:{'click [data-action=submit]':'submit','click [data-action=close]':'close'},initialize:function(options){options.model=app.data.createBean('Feedbacks');var fieldsMeta=_.flatten(_.pluck(options.meta.panels,'fields'));options.model.fields={};_.each(fieldsMeta,function(field){options.model.fields[field.name]=field;});this._super('initialize',[options]);this.context.set('skipFetch',true);this.model.on('error:validation',function(){app.alert.show('send_feedback',{level:'error',messages:app.lang.get('LBL_FEEDBACK_SEND_ERROR',this.module)});},this);this.model.on('validation:success',this.send,this);this.button=$(options.button);this._isOpen=false;var learnMoreUrl='http://www.sugarcrm.com/crm/product_doc.php?'+$.param({edition:app.metadata.getServerInfo().flavor,version:app.metadata.getServerInfo().version,lang:app.lang.getLanguage(),module:this.module,route:'list'});this.aside=new Handlebars.SafeString(app.lang.get('TPL_FEEDBACK_ASIDE',this.module,{learnMoreLink:new Handlebars.SafeString('<a href="'+learnMoreUrl+'" target="_blank">'+Handlebars.Utils.escapeExpression(app.lang.get('LBL_FEEDBACK_ASIDE_CLICK_MORE',this.module))+'</a>'),contactSupportLink:new Handlebars.SafeString('<a href="http://support.sugarcrm.com" target="_blank">'+Handlebars.Utils.escapeExpression(app.lang.get('LBL_FEEDBACK_ASIDE_CONTACT_SUPPORT',this.module))+'</a>')}));},_initPopover:function(button){button.popover({title:app.lang.get('LBL_FEEDBACK',this.module),content:_.bind(function(){return this.$el;},this),html:true,placement:'top',trigger:'manual',template:'<div class="popover feedback"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});},close:function(){this.toggle(false);},toggle:function(show){if(_.isUndefined(show)){this._isOpen=!this._isOpen;}else{this._isOpen=show;}
this.button.popover('destroy');this.render();if(this._isOpen){this._initPopover(this.button);this.button.popover('show');}
this.trigger(this._isOpen?'show':'hide',this,this._isOpen);},_dispose:function(){if(this.button){this.button.popover('destroy');}
this._super('_dispose');},submit:function(){this.model.doValidate();},send:function(){this.model.set({timezone:app.user.getPreference('timezone'),account_type:app.user.get('type'),role:app.user.get('roles').join(', ')||'n/a',feedback_app_path:window.location.href,feedback_user_browser:navigator.userAgent+' ('+navigator.language+')',feedback_user_os:navigator.platform,feedback_sugar_version:_.toArray(_.pick(app.metadata.getServerInfo(),'product_name','version')).join(' '),company:app.config.systemName});var post_url='https://docs.google.com/forms/d/1iIdfeWma_OUUkaP-wSojZW2GelaxMOBgDq05A8PGHY8/formResponse';$.ajax({url:post_url,type:'POST',data:{'entry.98009013':this.model.get('account_type'),'entry.1589366838':this.model.get('timezone'),'entry.762467312':this.model.get('role'),'entry.968140953':this.model.get('feedback_text'),'entry.944905780':this.model.get('feedback_app_path'),'entry.1750203592':this.model.get('feedback_user_browser'),'entry.1115361778':this.model.get('feedback_user_os'),'entry.1700062722':this.model.get('feedback_csat'),'entry.1926759955':this.model.get('feedback_sugar_version'),'entry.398692075':this.model.get('company')},dataType:'script',crossDomain:true,cache:false,context:this,timeout:10000,success:function(){app.alert.show('send_feedback',{level:'success',messages:app.lang.get('LBL_FEEDBACK_SENT',this.module),autoClose:true});this.model.clear();this.toggle(false);},error:function(){app.alert.show('send_feedback',{level:'error',messages:app.lang.get('LBL_FEEDBACK_NOT_SENT',this.module)});}});}})