<?php

 /*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dashletStrings = array ( 
   'CalendarDashlet' => array (
      'LBL_TITLE' => 'Takvimim' ,
      'LBL_DESCRIPTION' => 'Takvim dashlet' ,
      'LBL_CONFIGURE_TITLE' => 'Başlık' ,
      'LBL_CONFIGURE_VIEW' => 'Göster' ,
      'LBL_SAVE_BUTTON_LABEL' => 'Kaydet' ,
      'LBL_VIEW_DAY' => 'Gün' ,
      'LBL_VIEW_WEEK' => 'Hafta' ,
      'LBL_VIEW_MONTH' => 'Ay'   ));

?>
