/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'RecordView',alert:undefined,cancelClicked:function(){var changedAttributes=this.model.changedAttributes(this.model.getSynced());this.model.set(changedAttributes,{revert:true});this._super('cancelClicked');},initialize:function(options){this.plugins=_.union(this.plugins,['LinkedModel','HistoricalSummary','CommittedDeleteWarning']);this.addInitListener();this._super('initialize',[options]);app.utils.hideForecastCommitStageField(this.meta.panels);},addInitListener:function(){if(app.metadata.getModule('Opportunities','config').opps_view_by=='RevenueLineItems'&&app.acl.hasAccess('edit','RevenueLineItems')){this.once('init',function(){var rlis=this.model.getRelatedCollection('revenuelineitems');rlis.once('reset',function(collection){if(collection.length===0&&$('#createRLI').length===0){this.showRLIWarningMessage(this.model.module);}},this);rlis.fetch({relate:true});},this);}},getCalculatedFields:function(){return _.filter(this.model.fields,function(field){return field.calculated;});},setupDuplicateFields:function(prefill){if(app.metadata.getModule('Opportunities','config').opps_view_by==='RevenueLineItems'){var calcFields=this.getCalculatedFields();if(calcFields){_.each(calcFields,function(field){prefill.unset(field.name);},this);}}},showRLIWarningMessage:function(){app.routing.before('route',this.dismissAlert,this);var message=app.lang.get('TPL_RLI_CREATE','Opportunities')+'  <a href="javascript:void(0);" id="createRLI">'+
app.lang.get('TPL_RLI_CREATE_LINK_TEXT','Opportunities')+'</a>';this.alert=app.alert.show('opp-rli-create',{level:'warning',autoClose:false,title:app.lang.get('LBL_ALERT_TITLE_WARNING')+':',messages:message,onLinkClick:_.bind(function(){this.openRLICreate();},this),onClose:_.bind(function(){app.routing.offBefore('route',this.dismissAlert,this);},this)});},dismissAlert:function(){app.alert.dismiss('opp-rli-create');app.routing.offBefore('route',this.dismissAlert,this);},openRLICreate:function(){this.dismissAlert();var model=this.createLinkModel(this.createdModel||this.model,'revenuelineitems');app.drawer.open({layout:'create',context:{create:true,module:model.module,model:model}},_.bind(this.rliCreateClose,this));},rliCreateClose:function(model){if(!model){return;}
var ctx=this.listContext||this.context;ctx.resetLoadFlag();ctx.set('skipFetch',false);ctx.loadData();var rli_ctx=_.find(ctx.children,function(child){return(child.get('module')=='RevenueLineItems');},this);if(!_.isUndefined(rli_ctx)&&_.isFunction(rli_ctx.loadData)){rli_ctx.loadData();}}})