/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'FlexListView',plugins:['SugarLogic','ReorderableColumns','ResizableColumns','ListColumnEllipsis','ErrorDecoration','Editable','MergeDuplicates','Pagination','LinkedModel'],toggledModels:null,rowFields:{},dataViewName:'list',contextEvents:{"list:editall:fire":"toggleEdit","list:editrow:fire":"editClicked","list:deleterow:fire":"warnDelete"},initialize:function(options){var recordListMeta=this._initializeMetadata(options.context);options.meta=this._filterMeta(_.extend({},recordListMeta,options.meta||{}),options);this._super("initialize",[options]);this.events=_.extend({},this.events,{'click [name=inline-cancel]':'resize'});this.on('render',this._setRowFields,this);this.context.set('dataView',this.dataViewName);this.on('list:toggle:column',this.resize,this);this.on('mergeduplicates:complete',this.refreshCollection,this);this.on('field:focus:location',this.setPanelPosition,this);if(this.layout){this.layout.on('list:mergeduplicates:fire',this.mergeDuplicatesClicked,this);this.layout.on('list:filter:toggled',this.filterToggled,this);this.layout.on('list:record:deleted',function(){this.refreshCollection();},this);}
this.toggledModels={};this.context._recordListFields=this.getFieldNames(null,true);this._currentUrl=Backbone.history.getFragment();app.routing.before("route",this.beforeRouteDelete,this,true);$(window).on("beforeunload.delete"+this.cid,_.bind(this.warnDeleteOnRefresh,this));},filterToggled:function(isOpened){this.context.set('filterOpened',isOpened);},getPaginationOptions:function(){var options=this.context.get('filterOpened')?this.getSearchOptions():{};if(this.context.get('limit')){options.limit=this.context.get('limit');}
options=_.extend({},this.context.get('collectionOptions'),options);return options;},getSearchOptions:function(){var collection,options,previousTerms,term='';collection=this.context.get('collection');if(app.cache.has('previousTerms')){previousTerms=app.cache.get('previousTerms');if(previousTerms){term=previousTerms[this.module];}}
options={params:{q:term},fields:collection.fields?collection.fields:this.collection};return options;},_initializeMetadata:function(){return app.metadata.getView(null,'recordlist')||{};},_filterMeta:function(meta,options){var context=options.context,isDeveloper=app.acl.hasAccess("developer",context.get("module")),hasCalcFields=context&&context.get("model")&&!!_.find(context.get("model").fields,function(def){return def&&def.calculated&&def.calculated!="false";});if((!isDeveloper||!hasCalcFields)&&meta.selection&&meta.selection.actions){meta.selection.actions=_.reject(meta.selection.actions,function(action){return action.name=="calc_field_button";});}
return meta;},refreshCollection:function(){this.collection.fetch();},addActions:function(){if(this.actionsAdded)return;this._super("addActions");if(_.isUndefined(this.leftColumns[0])){this.leftColumns.push({'type':'fieldset','label':'','sortable':false,'fields':[]});}
this.addFavorite();var firstLeftColumn=this.leftColumns[0];if(firstLeftColumn&&_.isArray(firstLeftColumn.fields)){firstLeftColumn.fields.push({type:'editablelistbutton',label:'LBL_CANCEL_BUTTON_LABEL',name:'inline-cancel',css_class:'btn-link btn-invisible inline-cancel'});this.leftColumns[0]=firstLeftColumn;}
var firstRightColumn=this.rightColumns[0];if(firstRightColumn&&_.isArray(firstRightColumn.fields)){firstRightColumn.css_class='overflow-visible';firstRightColumn.fields.push({type:'editablelistbutton',label:'LBL_SAVE_BUTTON_LABEL',name:'inline-save',css_class:'btn-primary'});this.rightColumns[0]=firstRightColumn;}
this.actionsAdded=true;},addFavorite:function(){var favoritesEnabled=app.metadata.getModule(this.module,"favoritesEnabled");if(favoritesEnabled!==false&&this.meta.favorite&&this.leftColumns[0]&&_.isArray(this.leftColumns[0].fields)){this.leftColumns[0].fields.push({type:'favorite'});}},_setRowFields:function(){this.rowFields={};_.each(this.fields,function(field){if(field.model.id&&_.isUndefined(field.parent)){this.rowFields[field.model.id]=this.rowFields[field.model.id]||[];this.rowFields[field.model.id].push(field);}},this);},_getLeftBorderPosition:function(){if(!this._leftBorderPosition){var scrollPanel=this.$('.flex-list-view-content');this._leftBorderPosition=scrollPanel.find('thead tr:first th:first').outerWidth();}
return this._leftBorderPosition;},_getRightBorderPosition:function(){if(!this._rightBorderPosition){var scrollPanel=this.$('.flex-list-view-content');this._rightBorderPosition=scrollPanel.find('thead tr:first th:last').position().left;}
return this._rightBorderPosition;},setPanelPosition:function(location){if(app.lang.direction==='rtl'){return;}
var leftBorderPosition=this._getLeftBorderPosition(),rightBorderPosition=this._getRightBorderPosition(),relativeLeft=location.left,relativeRight=location.right;if(relativeRight<=rightBorderPosition&&relativeLeft>=leftBorderPosition){return;}
this.setScrollAtRightBorder(location.right);},setScrollAtLeftBorder:function(left){var scrollPanel=this.$('.flex-list-view-content'),leftBorderPosition=this._getLeftBorderPosition(),scrollLeft=scrollPanel.scrollLeft();left+=scrollLeft-leftBorderPosition;scrollPanel.scrollLeft(left);},setScrollAtRightBorder:function(right){var scrollPanel=this.$('.flex-list-view-content'),rightBorderPosition=this._getRightBorderPosition(),scrollLeft=scrollPanel.scrollLeft();right+=scrollLeft-rightBorderPosition;scrollPanel.scrollLeft(right);},deleteModel:function(){var self=this,model=this._modelToDelete;model.destroy({showAlerts:{'process':true,'success':{messages:self.getDeleteMessages(self._modelToDelete).success}},success:function(){var redirect=self._targetUrl!==self._currentUrl;self._modelToDelete=null;self.collection.remove(model,{silent:redirect});if(redirect){self.unbindBeforeRouteDelete();app.router.navigate(self._targetUrl,{trigger:true});return;}
app.events.trigger("preview:close");if(!self.disposed){self.render();}
self.layout.trigger("list:record:deleted",model);}});},beforeRouteDelete:function(){if(this._modelToDelete){this.warnDelete(this._modelToDelete);return false;}
return true;},getDeleteMessages:function(model){var messages={};var name=Handlebars.Utils.escapeExpression(app.utils.getRecordName(model)).trim();var context=app.lang.getModuleName(model.module).toLowerCase()+' '+name;messages.confirmation=app.utils.formatString(app.lang.get('NTC_DELETE_CONFIRMATION_FORMATTED'),[context]);messages.success=app.utils.formatString(app.lang.get('NTC_DELETE_SUCCESS'),[context]);return messages;},warnDelete:function(model){var self=this;this._modelToDelete=model;self._targetUrl=Backbone.history.getFragment();if(self._targetUrl!==self._currentUrl){app.router.navigate(self._currentUrl,{trigger:false,replace:true});}
app.alert.show('delete_confirmation',{level:'confirmation',messages:self.getDeleteMessages(model).confirmation,onConfirm:_.bind(self.deleteModel,self),onCancel:function(){self._modelToDelete=null;}});},warnDeleteOnRefresh:function(){if(this._modelToDelete){return this.getDeleteMessages(this._modelToDelete).confirmation;}},hasUnsavedChanges:function(){var firstKey=_.first(_.keys(this.rowFields)),formFields=[];_.each(this.rowFields[firstKey],function(field){if(field.name){formFields.push(field.name);}
if(field.def.fields){formFields=_.chain(field.def.fields).pluck('name').compact().union(formFields).value();}},this);return _.some(_.values(this.toggledModels),function(model){var changedAttributes=model.changedAttributes(model.getSyncedAttributes());if(_.isEmpty(changedAttributes)){return false;}
var unsavedFields=_.intersection(_.keys(changedAttributes),formFields);return!_.isEmpty(unsavedFields);},this);},mergeDuplicatesClicked:function(){this.mergeDuplicates(this.context.get('mass_collection'));},editClicked:function(model,field){if(field.def.full_form){this.createRelatedRecord(this.module,this.context.get('link'),model.id);}else{this.toggleRow(model.id,true);this.resize();}},toggleRow:function(modelId,isEdit){if(isEdit){this.toggledModels[modelId]=this.collection.get(modelId);}else{delete this.toggledModels[modelId];}
this.$('tr[name='+this.module+'_'+modelId+']').toggleClass('tr-inline-edit',isEdit);this.toggleFields(this.rowFields[modelId],isEdit);},toggleEdit:function(isEdit){var self=this;this.viewName=isEdit?'edit':'list';_.each(this.rowFields,function(editableFields,modelId){_.defer(function(modelId){self.toggleRow(modelId,isEdit);},modelId);},this);},unbindBeforeRouteDelete:function(){app.routing.offBefore("route",this.beforeRouteDelete,this);$(window).off("beforeunload.delete"+this.cid);},_dispose:function(){this.unbindBeforeRouteDelete();this._super('_dispose');this.rowFields=null;},getFieldNames:function(module,onlyDataFields){var fields=onlyDataFields?[]:this._super('getFieldNames',arguments);if(this.meta.favorite){fields=_.union(fields,['my_favorite']);}
if(this.meta.following){fields=_.union(fields,['following']);}
return fields;},registerShortcuts:function(){var clickButton=function($button){if($button.is(':visible')&&!$button.hasClass('disabled')){$button.click();}};this._super('registerShortcuts');app.shortcuts.register('List:Inline:Edit','e',function(){var self=this;if(this.$('.selected [name=inline-cancel]:visible').length===0){this.$('.selected [data-toggle=dropdown]:visible').click();this.$('.selected [name=edit_button]:visible').click();_.defer(function(){self.$('.selected input:first').focus();});}},this);app.shortcuts.register('List:Delete','d',function(){if(this.$('.selected [name=inline-cancel]:visible').length===0){this.$('.selected [data-toggle=dropdown]:visible').click().blur();this.$('.selected [name=delete_button]:visible').click();}},this);app.shortcuts.register('List:Inline:Cancel',['esc','ctrl+alt+l'],function(event){var $cancelButton=this.$('.selected [name=inline-cancel]'),$focusedInlineEditRow=$(event.target).closest('.tr-inline-edit');if($cancelButton.length>0){clickButton($cancelButton);}else if($focusedInlineEditRow.length>0){clickButton($focusedInlineEditRow.find('[name=inline-cancel]'));}},this,true);app.shortcuts.register('List:Inline:Save',['ctrl+s','ctrl+alt+a'],function(event){var $saveButton=this.$('.selected [name=inline-save]'),$focusedInlineEditRow=$(event.target).closest('.tr-inline-edit');if($saveButton.length>0){clickButton($saveButton);}else if($focusedInlineEditRow.length>0){clickButton($focusedInlineEditRow.find('[name=inline-save]'));}},this,true);app.shortcuts.register('List:Favorite','f a',function(){this.$('.selected .fa-favorite:visible').click();},this);app.shortcuts.register('List:Follow','f o',function(){this.$('.selected [data-toggle=dropdown]:visible').click().blur();this.$('.selected [name=follow_button]:visible').click();},this);app.shortcuts.register('List:Preview','p',function(){clickButton(this.$('.selected [data-event="list:preview:fire"]:visible'));},this);app.shortcuts.register('List:Select','x',function(){var $checkbox=this.$('.selected input[type=checkbox]:first');if($checkbox.is(':visible')&&!$checkbox.hasClass('disabled')){$checkbox.get(0).click();}},this);}})