/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'FlexListView',plugins:['SugarLogic','ReorderableColumns','ResizableColumns','ListColumnEllipsis','ErrorDecoration','Editable','MergeDuplicates','Pagination','MassCollection'],toggledModels:null,rowFields:{},contextEvents:{"list:editall:fire":"toggleEdit","list:editrow:fire":"editClicked","list:deleterow:fire":"warnDelete"},initialize:function(options){var recordListMeta=this._initializeMetadata(options.context);options.meta=this._filterMeta(_.extend({},recordListMeta,options.meta||{}),options);this._super("initialize",[options]);this.events=_.extend({},this.events,{'click [name=inline-cancel]':'resize','keydown':'_setScrollPosition'});this.toggledModels={};this.context._recordListFields=this.getFieldNames(null,true);this._currentUrl=Backbone.history.getFragment();this._bindEvents();},_bindEvents:function(){this.on('render render:rows',this._setRowFields,this);this.on('list:toggle:column',this.resize,this);this.on('mergeduplicates:complete',this.refreshCollection,this);this.on('field:focus:location',this.setPanelPosition,this);if(this.layout){this.layout.on('list:mergeduplicates:fire',this.mergeDuplicatesClicked,this);this.layout.on('list:filter:toggled',this.filterToggled,this);this.layout.on('list:alert:show list:alert:hide',this._refreshReorderableColumns,this);}
app.routing.before('route',this.beforeRouteDelete,this);$(window).on('beforeunload.delete'+this.cid,_.bind(this.warnDeleteOnRefresh,this));},filterToggled:function(isOpened){this.context.set('filterOpened',isOpened);},getPaginationOptions:function(){var options=this.context.get('filterOpened')?this.getSearchOptions():{};return options;},getSearchOptions:function(){var collection,options,previousTerms,term='';collection=this.context.get('collection');if(app.cache.has('previousTerms')){previousTerms=app.cache.get('previousTerms');if(previousTerms){term=previousTerms[this.module];}}
options={params:{q:term},fields:collection.fields?collection.fields:this.collection};return options;},_initializeMetadata:function(){return app.metadata.getView(null,'recordlist')||{};},_filterMeta:function(meta,options){var context=options.context;var isDeveloper=app.acl.hasAccess("developer",context.get("module"));var hasCalcFields=context&&context.get("model")&&!!_.find(context.get("model").fields,function(def){return def&&def.calculated&&def.calculated!="false";});var isTagsParent=options.context.get('parentModule')==='Tags';if((!isDeveloper||!hasCalcFields)&&meta.selection&&meta.selection.actions){meta.selection.actions=_.reject(meta.selection.actions,function(action){return action.name=="calc_field_button";});}
if(isTagsParent&&meta.rowactions&&meta.rowactions.actions){meta.rowactions.actions=_.reject(meta.rowactions.actions,function(row){return row.type==='unlink-action';});}
return meta;},refreshCollection:function(){this.collection.fetch();},addActions:function(){if(this.actionsAdded)return;this._super("addActions");if(_.isUndefined(this.leftColumns[0])){this.leftColumns.push({'type':'fieldset','label':'','sortable':false,'fields':[]});}
this.addFavorite();var firstLeftColumn=this.leftColumns[0];if(firstLeftColumn&&_.isArray(firstLeftColumn.fields)){firstLeftColumn.fields.push({type:'editablelistbutton',label:'LBL_CANCEL_BUTTON_LABEL',name:'inline-cancel',css_class:'btn-link btn-invisible inline-cancel'});this.leftColumns[0]=firstLeftColumn;}
var firstRightColumn=this.rightColumns[0];if(firstRightColumn&&_.isArray(firstRightColumn.fields)){firstRightColumn.css_class='overflow-visible';firstRightColumn.fields.push({type:'editablelistbutton',label:'LBL_SAVE_BUTTON_LABEL',name:'inline-save',css_class:'btn-primary'});this.rightColumns[0]=firstRightColumn;}
this.actionsAdded=true;},addFavorite:function(){var favoritesEnabled=app.metadata.getModule(this.module,"favoritesEnabled");if(favoritesEnabled!==false&&this.meta.favorite&&this.leftColumns[0]&&_.isArray(this.leftColumns[0].fields)){this.leftColumns[0].fields.push({type:'favorite'});}},_setRowFields:function(){this.rowFields={};_.each(this.fields,function(field){if(field.model.id&&_.isUndefined(field.parent)){this.rowFields[field.model.id]=this.rowFields[field.model.id]||[];this.rowFields[field.model.id].push(field);}},this);},_setScrollPosition:function(event){if(event.keyCode===9){var $flexListContent=this.$('.flex-list-view-content');$flexListContent.data('previousScrollLeftValue',$flexListContent.scrollLeft());}},_getBordersPosition:function(){if(!this._bordersPosition){this._bordersPosition={};var thSelector={};var $scrollPanel=this.$('.flex-list-view-content');var rtl=app.lang.direction==='rtl';thSelector.left=rtl?'last':'first';thSelector.right=rtl?'first':'last';this._bordersPosition.left=$scrollPanel.find('thead tr:first th:'+thSelector.left).outerWidth();this._bordersPosition.right=$scrollPanel.find('thead tr:first th:'+thSelector.right).children().position().left;}
return this._bordersPosition;},setPanelPosition:function(location){var bordersPosition=this._getBordersPosition();var fieldLeft=location.left;var fieldRight=location.right;if(fieldRight<=bordersPosition.right&&fieldLeft>=bordersPosition.left){return;}
this._scrollToMakeFieldVisible(bordersPosition.left,bordersPosition.right,location);},_scrollToMakeFieldVisible:function(leftBorderPosition,rightBorderPosition,location){var $scrollPanel=this.$('.flex-list-view-content');var scrollPosition=$scrollPanel.scrollLeft();var fieldLeft=location.left;var fieldRight=location.right;var fieldPadding=location.fieldPadding;var distanceToScroll;if(fieldLeft<leftBorderPosition){distanceToScroll=fieldLeft-leftBorderPosition-fieldPadding;}else if(rightBorderPosition<fieldRight){distanceToScroll=fieldRight-rightBorderPosition+fieldPadding;}else{return;}
if(app.lang.direction==='rtl'&&$.support.rtlScrollType==='reverse'){distanceToScroll=-distanceToScroll;}
$scrollPanel.scrollLeft(scrollPosition+distanceToScroll);},setScrollAtLeftBorder:function(left){var $scrollPanel=this.$('.flex-list-view-content'),leftBorderPosition=this._getBordersPosition().left,scrollLeft=$scrollPanel.scrollLeft();left+=scrollLeft-leftBorderPosition;$scrollPanel.scrollLeft(left);app.logger.warn('"setScrollAtLeftBorder" method is deprecated and will be removed in 7.8');},setScrollAtRightBorder:function(right){var $scrollPanel=this.$('.flex-list-view-content'),rightBorderPosition=this._getBordersPosition().right,scrollLeft=$scrollPanel.scrollLeft();right+=scrollLeft-rightBorderPosition;$scrollPanel.scrollLeft(right);app.logger.warn('"setScrollAtRightBorder" method is deprecated and will be removed in 7.8');},deleteModel:function(){var self=this,model=this._modelToDelete;model.destroy({showAlerts:{'process':true,'success':{messages:self.getDeleteMessages(self._modelToDelete).success}},success:function(){var redirect=self._targetUrl!==self._currentUrl;self._modelToDelete=null;self.collection.remove(model,{silent:redirect});if(redirect){self.unbindBeforeRouteDelete();app.router.navigate(self._targetUrl,{trigger:true});return;}
app.events.trigger("preview:close");if(!self.disposed){self.render();}
self.layout.trigger("list:record:deleted",model);}});},beforeRouteDelete:function(){if(this._modelToDelete){this.warnDelete(this._modelToDelete);return false;}
return true;},getDeleteMessages:function(model){var messages={};var name=Handlebars.Utils.escapeExpression(app.utils.getRecordName(model)).trim();var context=app.lang.getModuleName(model.module).toLowerCase()+' '+name;messages.confirmation=app.utils.formatString(app.lang.get('NTC_DELETE_CONFIRMATION_FORMATTED'),[context]);messages.success=app.utils.formatString(app.lang.get('NTC_DELETE_SUCCESS'),[context]);return messages;},warnDelete:function(model){var self=this;this._modelToDelete=model;self._targetUrl=Backbone.history.getFragment();if(self._targetUrl!==self._currentUrl){app.router.navigate(self._currentUrl,{trigger:false,replace:true});}
app.alert.show('delete_confirmation',{level:'confirmation',messages:self.getDeleteMessages(model).confirmation,onConfirm:_.bind(self.deleteModel,self),onCancel:function(){self._modelToDelete=null;}});},warnDeleteOnRefresh:function(){if(this._modelToDelete){return this.getDeleteMessages(this._modelToDelete).confirmation;}},hasUnsavedChanges:function(){var firstKey=_.first(_.keys(this.rowFields)),formFields=[];_.each(this.rowFields[firstKey],function(field){if(field.name){formFields.push(field.name);}
if(field.def.fields){formFields=_.chain(field.def.fields).pluck('name').compact().union(formFields).value();}},this);return _.some(_.values(this.toggledModels),function(model){var changedAttributes=model.changedAttributes(model.getSynced());if(_.isEmpty(changedAttributes)){return false;}
var unsavedFields=_.intersection(_.keys(changedAttributes),formFields);return!_.isEmpty(unsavedFields);},this);},mergeDuplicatesClicked:function(){this.mergeDuplicates(this.context.get('mass_collection'));},editClicked:function(model,field){if(field.def.full_form){var parentModel=this.context.parent.get('model');var link=this.context.get('link');app.bwc.createRelatedRecord(this.module,parentModel,link,model.id);}else{this.toggleRow(model.id,true);this.resize();}
if(!_.isEqual(model.attributes,model._syncedAttributes)){model.setSyncedAttributes(model.attributes);}},toggleRow:function(modelId,isEdit){if(isEdit){this.toggledModels[modelId]=this.collection.get(modelId);}else{delete this.toggledModels[modelId];}
this.$('tr[name='+this.module+'_'+modelId+']').toggleClass('tr-inline-edit',isEdit);this.toggleFields(this.rowFields[modelId],isEdit);},unbindBeforeRouteDelete:function(){app.routing.offBefore("route",this.beforeRouteDelete,this);$(window).off("beforeunload.delete"+this.cid);},_dispose:function(){this.unbindBeforeRouteDelete();this._super('_dispose');this.rowFields=null;},getFieldNames:function(module,onlyDataFields){var fields=onlyDataFields?[]:this._super('getFieldNames',arguments);if(this.meta.favorite){fields=_.union(fields,['my_favorite']);}
if(this.meta.following){fields=_.union(fields,['following']);}
return fields;},registerShortcuts:function(){var clickButton=function($button){if($button.is(':visible')&&!$button.hasClass('disabled')){$button.click();}};this._super('registerShortcuts');app.shortcuts.register('List:Inline:Edit','e',function(){var self=this;if(this.$('.selected [name=inline-cancel]:visible').length===0){this.$('.selected [data-toggle=dropdown]:visible').click();this.$('.selected [name=edit_button]:visible').click();_.defer(function(){self.$('.selected input:first').focus();});}},this);app.shortcuts.register('List:Delete','d',function(){if(this.$('.selected [name=inline-cancel]:visible').length===0){this.$('.selected [data-toggle=dropdown]:visible').click().blur();this.$('.selected [name=delete_button]:visible').click();}},this);app.shortcuts.register('List:Inline:Cancel',['esc','ctrl+alt+l'],function(event){var $cancelButton=this.$('.selected [name=inline-cancel]'),$focusedInlineEditRow=$(event.target).closest('.tr-inline-edit');if($cancelButton.length>0){clickButton($cancelButton);}else if($focusedInlineEditRow.length>0){clickButton($focusedInlineEditRow.find('[name=inline-cancel]'));}},this,true);app.shortcuts.register('List:Inline:Save',['ctrl+s','ctrl+alt+a'],function(event){var $saveButton=this.$('.selected [name=inline-save]'),$focusedInlineEditRow=$(event.target).closest('.tr-inline-edit');if($saveButton.length>0){clickButton($saveButton);}else if($focusedInlineEditRow.length>0){clickButton($focusedInlineEditRow.find('[name=inline-save]'));}},this,true);app.shortcuts.register('List:Favorite','f a',function(){this.$('.selected .fa-favorite:visible').click();},this);app.shortcuts.register('List:Follow','f o',function(){this.$('.selected [data-toggle=dropdown]:visible').click().blur();this.$('.selected [name=follow_button]:visible').click();},this);app.shortcuts.register('List:Preview','p',function(){clickButton(this.$('.selected [data-event="list:preview:fire"]:visible'));},this);app.shortcuts.register('List:Select','x',function(){var $checkbox=this.$('.selected input[type=checkbox]:first');if($checkbox.is(':visible')&&!$checkbox.hasClass('disabled')){$checkbox.get(0).click();}},this);},resize:function(){this._super('resize');this._bordersPosition=null;},_refreshReorderableColumns:function(){$(window).resize();}})