/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({initialize:function(options){this._super('initialize',[options]);this.fields=[];var inlineTag=this.def.inline?'-inline':'';this.def.css_class=(this.def.css_class?this.def.css_class+' fieldset':'fieldset')+inlineTag;if(this.def.equal_spacing&&this.def.inline){this.def.css_class+=' fieldset-equal';}},_getFallbackTemplate:function(viewName){if(_.contains(this.fallbackActions,viewName)){return viewName;}
if(app.template.get('f.'+this.type+'.'+this.view.fallbackFieldTemplate)){return this.view.fallbackFieldTemplate;}
return'detail';},_loadTemplate:function(){this._super('_loadTemplate');if((this.view.name==='record'||this.view.name==='create'||this.view.name==='create-actions'||this.view.name==='create-nodupecheck')&&this.type==='fieldset'&&!_.contains(this.fallbackActions,this.action)){this.template=app.template.getField('fieldset','record-detail',this.model.module);}},showNoData:function(){if(!this.def.readonly){return false;}
return!_.some(this.fields,function(field){return field.name&&field.model.has(field.name);});},_render:function(){var fields=this._getChildFields();_.each(fields,function(field){field.placeholder=field.getPlaceholder();},this);this.focusIndex=0;this._super('_render');this._renderFields(fields);return this;},_renderFields:function(fields){var fieldElems={};this.$('span[sfuuid]').each(function(){var $this=$(this);var sfId=$this.attr('sfuuid');fieldElems[sfId]=$this;});_.each(fields,function(field){field.setElement(fieldElems[field.sfId]);field.render();},this);},_getChildFieldsMeta:function(){return app.utils.deepCopy(this.def.fields);},_getChildFields:function(){var metaFields=this._getChildFieldsMeta();if(_.isEmpty(this.fields)&&metaFields){_.each(metaFields,function(fieldDef){var field=app.view.createField({def:fieldDef,view:this.view,viewName:this.options.viewName,model:this.model});this.fields.push(field);field.parent=this;},this);}
return this.fields;},clearErrorDecoration:function(){_.each(this.fields,function(field){field.clearErrorDecoration();});this._super('clearErrorDecoration');},focus:function(){if(this.focusIndex<0||!this.focusIndex){this.focusIndex=0;}
if(this.focusIndex>=this.fields.length){this.focusIndex=-1;return false;}else{if(this.fields[this.focusIndex]&&this.fields[this.focusIndex].isDisabled()){this.focusIndex++;return this.focus();}
if(_.isFunction(this.fields[this.focusIndex].focus)&&this.fields[this.focusIndex].focus()){}else{var field=this.fields[this.focusIndex];var $el=field.$(field.fieldTag+':first');$el.focus().val($el.val());this.focusIndex++;}
return true;}},setDisabled:function(disable){disable=_.isUndefined(disable)?true:disable;this._super('setDisabled',[disable]);_.each(this.fields,function(field){field.setDisabled(disable);},this);},setViewName:function(view){this._super('setViewName',[view]);_.each(this.fields,function(field){field.setViewName(view);},this);},setMode:function(name){this.focusIndex=0;_.each(this.fields,function(field){var oldAction=field._previousAction||field.action;field._removeViewClass(oldAction);if(field.isDisabled()){field._previousAction=name;}else{field.action=name;}
field.setViewName(name);});this._super('setMode',[name]);},bindDomChange:function(){},bindDataChange:function(){},unbindDom:function(){},_dispose:function(){_.each(this.fields,function(field){field.parent=null;field.dispose();});this.fields=null;app.view.Field.prototype._dispose.call(this);}})