/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'FieldsetField',showNoData:false,repeatCountMin:1,initialize:function(options){this._super('initialize',[options]);this.model.addValidationTask('repeat_count_or_until_required_validator_'+this.cid,_.bind(this._doValidateRepeatCountOrUntilRequired,this));},bindDataChange:function(){this._super('bindDataChange');this.model.on('change:repeat_type',this.repeatTypeChanged,this);this.model.on('change:repeat_count',this.repeatCountChanged,this);this.model.on('change:repeat_until',this.repeatUntilChanged,this);},_loadTemplate:function(){var originalType=this.type;this.type='fieldset';this._super('_loadTemplate');this.type=originalType;},_render:function(){var repeatType=this.model.get('repeat_type');this._super('_render');switch(repeatType){case'Daily':case'Weekly':case'Monthly':case'Yearly':this.show();break;default:this.hide();break;}
this.prepareView();},prepareView:function(){var repeatType=this.model.get('repeat_type'),repeatUntil=this.model.get('repeat_until');if(repeatType==='Weekly'){this._showField('repeat_dow');}else{this._hideField('repeat_dow');}
if(this.action==='edit'){this._showField('repeat_count');this._showField('repeat_until');this._getFieldRecordCellByType('label').show();}else{if(repeatUntil&&(repeatUntil.length>0)){this._hideField('repeat_count');this._showField('repeat_until');}else{this._showField('repeat_count');this._hideField('repeat_until');}
this._getFieldRecordCellByType('label').hide();}},repeatTypeChanged:function(){var force=!this._isPopulated(this.model.get('repeat_type'));_.each(this.fields,function(field){if(force||!this._isPopulated(this.model.get(field.name))){this.model.set(field.name,field.def['default']);}},this);this.render();},repeatCountChanged:function(){if(this._isPopulated(this.model.get('repeat_count'))){this.model.set('repeat_until','');}},repeatUntilChanged:function(){if(this._isPopulated(this.model.get('repeat_until'))){this.model.set('repeat_count','');}},_showField:function(fieldName){this._getFieldRecordCellByName(fieldName).show();},_hideField:function(fieldName){this._getFieldRecordCellByName(fieldName).hide();},_getFieldRecordCellByName:function(fieldName){var selector='.fieldset-field[data-name="'+fieldName+'"]';return this.$(selector);},_getFieldRecordCellByType:function(fieldType){var selector='.fieldset-field[data-type="'+fieldType+'"]';return this.$(selector);},_isPopulated:function(value){return!_.isUndefined(value)&&!_.isNull(value)&&value!=='';},_doValidateRepeatCountOrUntilRequired:function(fields,errors,callback){var repeatCount,repeatCountIsPopulated,repeatUntilIsPopulated;repeatCount=this.model.get('repeat_count');repeatCountIsPopulated=this._isPopulated(repeatCount);repeatUntilIsPopulated=this._isPopulated(this.model.get('repeat_until'));if(this._isPopulated(this.model.get('repeat_type'))){if(!repeatUntilIsPopulated&&!repeatCountIsPopulated){errors.repeat_count={required:true};}else if(!repeatUntilIsPopulated&&repeatCountIsPopulated&&repeatCount<this.repeatCountMin){errors.repeat_count={minValue:this.repeatCountMin};}}
callback(null,fields,errors);},_dispose:function(){this.model.removeValidationTask('repeat_count_or_until_required_validator_'+this.cid);this._super('_dispose');}})