/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({fieldSelector:'.htmleditable',_htmleditor:null,_isDirty:false,_saveOnSetContent:true,_render:function(){this.destroyTinyMCEEditor();app.view.Field.prototype._render.call(this);this._getHtmlEditableField().attr('name',this.name);if(this._isEditView()){this._renderEdit(this.options.def.tinyConfig||null);}else{this._renderView();}},bindDataChange:function(){this.model.on('change:'+this.name,function(model,value){if(this._isEditView()){this._saveOnSetContent=false;this.setEditorContent(value);}else{this.setViewContent(value)}},this);},setViewContent:function(value){var editable=this._getHtmlEditableField();if(editable&&!_.isUndefined(editable.get(0))){if(!_.isEmpty(editable.get(0).contentDocument)&&editable.contents().find('body').length>0){editable.contents().find('body').html(value);}}},_renderEdit:function(options){var self=this;this.initTinyMCEEditor(options);this._getHtmlEditableField().on('change',function(){self.model.set(self.name,self._getHtmlEditableField().val());});},_renderView:function(){this.setViewContent(this.value);},_isEditView:function(){return(this._getHtmlEditableField().prop('tagName')==='TEXTAREA');},getTinyMCEConfig:function(){return{script_url:'include/javascript/tiny_mce/tiny_mce.js',theme:"advanced",skin:"sugar7",plugins:"style,table,advhr,advimage,advlink,iespell,inlinepopups,media,searchreplace,print,contextmenu,paste,noneditable,visualchars,nonbreaking,xhtmlxtras",entity_encoding:"raw",theme_advanced_buttons1:"code,|,bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,fontsizeselect,|,insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,iespell,media,advhr,|,print,|",theme_advanced_buttons2:"cut,copy,paste,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,|,forecolor,backcolor,tablecontrols,|,",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left",theme_advanced_statusbar_location:"none",theme_advanced_resizing:true,schema:"html5",template_external_list_url:"lists/template_list.js",external_link_list_url:"lists/link_list.js",external_image_list_url:"lists/image_list.js",media_external_list_url:"lists/media_list.js",theme_advanced_path:false,theme_advanced_source_editor_width:500,theme_advanced_source_editor_height:400,inlinepopups_skin:"sugar7modal",relative_urls:false,remove_script_host:false};},initTinyMCEEditor:function(optConfig){var self=this;if(_.isEmpty(this._htmleditor)){var config=optConfig||this.getTinyMCEConfig();var __superSetup__=config.setup;config.setup=function(editor){if(_.isFunction(__superSetup__)){__superSetup__.call(this,editor);}
self._htmleditor=editor;self._htmleditor.onInit.add(function(ed){self.setEditorContent(self.getFormattedValue());$(ed.getWin()).blur(function(e){self._saveEditor();});});self._htmleditor.onDeactivate.add(function(ed){self._saveEditor();});self._htmleditor.onSetContent.add(function(ed){if(self._saveOnSetContent){self._saveEditor(true);}
self._saveOnSetContent=true;});self._htmleditor.onChange.add(function(ed,l){self._isDirty=true;});editor.addButton('mybutton',{title:'Fields Selector',class:'mce_selectfield',onclick:function(){self._showVariablesBook();}});editor.addButton('sugarlinkbutton',{title:app.lang.get('LBL_SUGAR_LINK_SELECTOR','pmse_Emails_Templates'),class:'mce_selectrecordlink',onclick:function(){self._showLinksDrawer();}});};config.oninit=function(inst){self.context.trigger('tinymce:oninit',inst);};$('.htmleditable').tinymce(config);}},destroyTinyMCEEditor:function(){if(!_.isNull(this._htmleditor)){this._saveEditor(true);this._htmleditor.remove();this._htmleditor.destroy();this._htmleditor=null;}},_saveEditor:function(force){var save=force|this._isDirty;if(save){this.model.set(this.name,this.getEditorContent(),{silent:true});this._isDirty=false;}},_getHtmlEditableField:function(){return this.$el.find(this.fieldSelector);},setEditorContent:function(value){if(_.isEmpty(value)){value="";}
if(this._isEditView()&&this._htmleditor&&this._htmleditor.dom){this._htmleditor.setContent(value);}},getEditorContent:function(){return this._htmleditor.getContent({format:'raw'});},_dispose:function(){this.destroyTinyMCEEditor();app.view.Field.prototype._dispose.call(this);},_showVariablesBook:function(){var addVariables=_.bind(function(variables){if(variables&&variables.length>0){this.model.set(this.name,this.buildVariablesString(variables));}},this);app.drawer.open({layout:"compose-varbook",context:{module:"pmse_Emails_Templates",mixed:true}},function(variables){addVariables(variables);});},buildVariablesString:function(recipients){var result='',newExpression='',currentValue,i,aux,aux2;_.each(recipients.models,function(model){newExpression+='{::'+App.lang.getModuleName(model.attributes.rhs_module,{plural:true})+'::'+model.attributes.id+'::}'});var bm=this._htmleditor.selection.getBookmark();this._htmleditor.selection.moveToBookmark(bm);this._htmleditor.selection.setContent(newExpression);return currentValue=this._htmleditor.getContent();},_showLinksDrawer:function(){var self=this;var baseModule=this.model.get('base_module');app.drawer.open({layout:"compose-sugarlinks",context:{module:"pmse_Emails_Templates",mixed:true,skipFetch:true,baseModule:baseModule}},function(field){if(_.isUndefined(field)){return;}
var link='{::href_link::'+App.lang.getModuleName(baseModule,{plural:true});if(baseModule!==field.get('value')){link+='::'+field.get('value');}
link+='::name::}';self._htmleditor.selection.setContent(link);self.model.set(self.name,self._htmleditor.getContent())});}})