/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({events:{'click .zoom-control':'zoomChart','click .toggle-control':'toggleChart'},plugins:['Dashlet','Tooltip','Chart'],nodetemplate:null,reporteesEndpoint:'',zoomExtents:null,nodeSize:null,jsTree:null,slider:null,sliderZoomIn:null,sliderZoomOut:null,initialize:function(options){var self=this;this._super('initialize',[options]);this.nodetemplate=app.template.getView(this.name+'.orgchartnode');this.reporteesEndpoint=app.api.buildURL('Forecasts','orgtree/'+app.user.get('id'),null,{'level':2});this.zoomExtents={'min':0.25,'max':1.75};this.nodeSize={'width':124,'height':56};this.chart=nv.models.tree().duration(300).nodeSize(this.nodeSize).nodeRenderer(function(d){return self.nodetemplate(d.metadata);}).zoomExtents(self.zoomExtents).zoomCallback(function(scale){self.moveSlider(scale);}).horizontal(false).getId(function(d){return d.metadata.id;});},_buildUserUrl:function(id){return'#'+app.bwc.buildRoute('Employees',id);},renderChart:function(){var self=this;if(!this.isChartReady()){return;}
if(!this.slider){this.slider=this.$('.btn-slider .noUiSlider');this.sliderZoomIn=this.$('.btn-slider i[data-control="zoom-in"]');this.sliderZoomOut=this.$('.btn-slider i[data-control="zoom-out"]');this.slider.noUiSlider('init',{start:100,knobs:1,scale:[this.zoomExtents.min*100,this.zoomExtents.max*100],connect:false,step:25,change:function(moveType){var values,scale;if(!self.chart_loaded){return;}
if(moveType==='slide'){values=self.slider.noUiSlider('value');scale=self.chart.zoomLevel(values[0]/ 100);}else{scale=self.chart.zoomScale();}
self.sliderZoomIn.toggleClass('disabled',(scale===self.zoomExtents.max));self.sliderZoomOut.toggleClass('disabled',(scale===self.zoomExtents.min));}});}
this.moveSlider();if(this.jsTree){this.jsTree.jstree('destroy');}
this.jsTree=this.$('div[data-control="org-jstree"]').jstree({'json_data':{'data':this.chartCollection},'plugins':['json_data','ui','types'],'core':{'animation':0},'ui':{'initially_select':['jstree_node_'+app.user.get('user_name')]}}).on('loaded.jstree',function(e){self.$('div[data-control="org-jstree"]').addClass('jstree-sugar');self.$('div[data-control="org-jstree"] > ul').addClass('list');self.$('div[data-control="org-jstree"] > ul > li > a').addClass('jstree-clicked');}).on('click.jstree',function(e){e.stopPropagation();e.preventDefault();}).on('select_node.jstree',function(event,data){var jsData=data.inst.get_json();self.chart.filter(jQuery.data(data.rslt.obj[0],'id'));self.forceRepaint();self.moveSlider();self.$('div[data-control="org-jstree-dropdown"] .jstree-label').text(data.inst.get_text());data.inst.toggle_node(data.rslt.obj);});app.accessibility.run(this.jsTree,'click');d3.select('svg#'+this.cid).datum(this.chartCollection[0]).transition().duration(500).call(this.chart);this.chart.reset();this.$('img').error(function(){$(this).attr('src','include/images/user.svg');});this.forceRepaint();this.$('.nv-expcoll').on('click',function(e){self.forceRepaint();self.moveSlider();});this.chart_loaded=_.isFunction(this.chart.resize);this.displayNoData(!this.chart_loaded);},forceRepaint:function(){this.$('.rep-avatar').on('load',function(){$(this).removeClass('loaded').addClass('loaded');});this.$('img').error(function(){$(this).attr('src','include/images/user.svg');});},moveSlider:function(scale){var s=scale||1;if(this.slider){this.slider.noUiSlider('move',{to:s*100});}},hasChartData:function(){return!_.isEmpty(this.chartCollection);},chartResize:function(){this.moveSlider();this.chart.resize();},_postProcessTree:function(data){var root=[],self=this;if(_.isArray(data)&&data.length==2){root.push(data[0]);root[0].children.push(data[1]);}else{root.push(data);}
if(_.isEmpty(root[0].metadata.id)){return null;}
_.each(root,function(entry){var adopt=[];if(!entry.data){return;}
entry.metadata.url=self._buildUserUrl(entry.metadata.id);if(!entry.metadata.picture||entry.metadata.picture===''){entry.metadata.img='include/images/user.svg';}else{entry.metadata.img=app.api.buildFileURL({module:'Employees',id:entry.metadata.id,field:'picture'});}
if(!entry.children){return;}
_.each(entry.children,function(childEntry){var newChild;if(entry.metadata.id!==childEntry.metadata.id){newChild=self._postProcessTree(childEntry);if(!_.isEmpty(newChild)){adopt.push(newChild[0]);}}},this);entry.children=adopt;},this);return root;},zoomChart:function(e){var button,step,scale;if(!this.chart_loaded){return;}
button=$(e.target).data('control');step=0.25*(button==='zoom-in'?1:-1);scale=this.chart.zoomStep(step);this.moveSlider(scale);},toggleChart:function(e){var button;if(!this.chart_loaded){return;}
button=$(e.currentTarget).hasClass('btn')?$(e.currentTarget):$(e.currentTarget).parent('.btn');switch(button.data('control')){case'orientation':this.chart.orientation();button.find('i').toggleClass('fa-arrow-right fa-arrow-down');break;case'show-all-nodes':this.chart.showall();this.forceRepaint();break;case'zoom-to-fit':this.chart.resize();break;default:}
this.moveSlider();},loadData:function(options){var self=this;app.api.call('get',this.reporteesEndpoint,null,{success:function(data){self.chartCollection=self._postProcessTree(data);if(!self.disposed){self.renderChart();}},complete:options?options.complete:null});},_dispose:function(){if(this.jsTree){this.jsTree.jstree('destroy');}
if(this.slider){this.slider.off('move');}
this._super('_dispose');}})