/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({className:'list-view',plugins:['Pagination'],events:{'click [class*="orderBy"]':'setOrderBy'},defaultLayoutEvents:{"list:search:fire":"fireSearch","list:filter:toggled":"filterToggled","list:alert:show":"showAlert","list:alert:hide":"hideAlert","list:sort:fire":"sort"},dataViewName:'list',defaultContextEvents:{},_previewed:null,_leftActions:[],_rowActions:[],_fields:{},initialize:function(options){var listViewMeta=app.metadata.getView(options.module,'list')||{};options.meta=_.extend({},listViewMeta,options.meta||{});options.meta.type=options.meta.type||'list';options.meta.action='list';options=this.parseFieldMetadata(options);app.view.View.prototype.initialize.call(this,options);this.context.set('dataView',this.dataViewName);this.attachEvents();this.orderByLastStateKey=app.user.lastState.key('order-by',this);this.orderBy=this._initOrderBy();if(this.collection){this.collection.orderBy=this.orderBy;}
this.limit=this.context.has('limit')?this.context.get('limit'):null;this.metaFields=this.meta.panels?_.first(this.meta.panels).fields:[];this.registerShortcuts();},_initOrderBy:function(){var lastStateOrderBy=app.user.lastState.get(this.orderByLastStateKey)||{},lastOrderedFieldMeta=this.getFieldMeta(lastStateOrderBy.field);if(_.isEmpty(lastOrderedFieldMeta)||!app.utils.isSortable(this.module,lastOrderedFieldMeta)){lastStateOrderBy={};}
return _.extend({field:'',direction:'desc'},this.meta.orderBy,lastStateOrderBy);},_render:function(){app.view.View.prototype._render.call(this);if(!app.acl.hasAccessToModel(this.action,this.model)){this._noAccessTemplate=this._noAccessTemplate||app.template.get("list.noaccess");this.$el.html(this._noAccessTemplate());}},parseFieldMetadata:function(options){_.each(options.meta.panels,function(panel,panelIdx){_.each(panel.fields,function(field,fieldIdx){var fieldFromMeta=options.meta.panels[panelIdx].fields[fieldIdx];if(!_.isUndefined(field.align)){if(_.contains(['left','center','right'],field.align)){fieldFromMeta.align='t'+field.align;}else{delete fieldFromMeta.align;}}
if(!_.isUndefined(field.width)){var percent=field.width.toString().match(/^(\d{0,3})\%$/);if(!percent&&!_.isEmpty(field.width+'')){var width=parseInt(field.width,10);if(!_.isNaN(width)&&_.isNumber(width)){var styles='max-width:'+width+'px;min-width:'+width+'px';fieldFromMeta.styles=styles;fieldFromMeta.expectedWidth=width;}else{fieldFromMeta.widthClass='cell-'+field.width;fieldFromMeta.expectedWidth=field.width;}}}},this);},this);return options;},attachEvents:function(){this.layoutEventsMap=_.extend(this.defaultLayoutEvents,this.layoutEvents);this.contextEventsMap=_.extend(this.defaultContextEvents,this.contextEvents);if(this.layout){_.each(this.layoutEventsMap,function(callback,event){this.layout.on(event,this[callback],this);},this);}
if(this.context){_.each(this.contextEventsMap,function(callback,event){this.context.on(event,this[callback],this);},this);}},sort:function(){app.events.trigger("preview:close");},showAlert:function(message){this.$("[data-target=alert]").html(message);this.$("[data-target=alert-container]").removeClass("hide");},hideAlert:function(){this.$("[data-target=alert-container]").addClass("hide");this.$("[data-target=alert]").empty();},filterToggled:function(isOpened){this.filterOpened=isOpened;},fireSearch:function(term){term=term||"";var options={limit:this.limit||null,query:term};this.context.get("collection").resetPagination();this.context.resetLoadFlag(false);this.context.set('skipFetch',false);this.context.loadData(options);},setOrderBy:function(event){if($(event.currentTarget).find('ui-draggable-dragging').length){return;}
var collection,options,eventTarget,orderBy;var self=this;collection=self.collection;eventTarget=self.$(event.currentTarget);orderBy=eventTarget.data('orderby');if(!orderBy){orderBy=eventTarget.data('fieldname');}
if(orderBy===self.orderBy.field){self.orderBy.direction=self.orderBy.direction==='desc'?'asc':'desc';}else{self.orderBy.field=orderBy;self.orderBy.direction='desc';}
collection.orderBy=self.orderBy;collection.resetPagination();options=self.getSortOptions(collection);if(this.triggerBefore('list:orderby',options)){self._setOrderBy(options);}},_setOrderBy:function(options){if(this.orderByLastStateKey){app.user.lastState.set(this.orderByLastStateKey,this.orderBy);}
this.context.resetLoadFlag(false);this.context.set('skipFetch',false);this.context.loadData(options);},getSortOptions:function(collection){var self=this,options={};options=self.filterOpened?self.getSearchOptions():{};options.showAlerts=true;options.limit=self.limit||null;options.success=function(collection,response,options){self.layout.trigger("list:sort:fire",collection,self);};if(collection.offset){options.limit=collection.offset;options.offset=0;}
return options;},getSearchOptions:function(){var collection,options,previousTerms,term='';collection=this.context.get('collection');if(app.cache.has('previousTerms')){previousTerms=app.cache.get('previousTerms');if(previousTerms){term=previousTerms[this.module];}}
options={params:{},fields:collection.fields?collection.fields:this.collection};if(term){options.params.q=term;}
if(this.context.get('link')){options.relate=true;}
return options;},bindDataChange:function(){if(this.collection){this.collection.on("reset",this.render,this);}},_dispose:function(){this._fields=null;app.view.View.prototype._dispose.call(this);},selectRow:function(down){var $rows=this.$('.dataTable tbody tr'),$selected,$next;if($rows.hasClass('selected')){$selected=$rows.filter('.selected');$next=down?$selected.next():$selected.prev();if($next.length>0){$selected.removeClass('selected');$next.addClass('selected');this.makeRowVisible($next);}}else{$rows.first().addClass('selected');this.makeRowVisible();}},makeRowVisible:function($selected){var $mainpane=this.$el.closest('.main-pane'),mainpaneHeight,selectedHeight,selectedTopPosition,selectedOffsetParent;if(_.isUndefined($selected)){$mainpane.scrollTop(0);return;}
mainpaneHeight=$mainpane.height();selectedHeight=$selected.height();selectedOffsetParent=$selected.offsetParent();selectedTopPosition=$selected.position().top+selectedOffsetParent.position().top;if((selectedTopPosition+selectedHeight)>mainpaneHeight){$mainpane.scrollTop($mainpane.scrollTop()+mainpaneHeight/2);}
if(selectedTopPosition<0){$mainpane.scrollTop($mainpane.scrollTop()-mainpaneHeight/2);}},scrollHorizontally:function(right){var $scrollableDiv=this.$('.flex-list-view-content'),scrollEnabled=this.$el.hasClass('scroll-width'),nextScrollPosition,increment=60;if(scrollEnabled){if(right){nextScrollPosition=$scrollableDiv.scrollLeft()+increment;}else{nextScrollPosition=$scrollableDiv.scrollLeft()-increment;}
$scrollableDiv.scrollLeft(nextScrollPosition);}},registerShortcuts:function(){app.shortcuts.register('List:Select:Down','j',function(){this.selectRow(true);},this);app.shortcuts.register('List:Select:Up','k',function(){this.selectRow(false);},this);app.shortcuts.register('List:Scroll:Left','h',function(){this.scrollHorizontally(false);},this);app.shortcuts.register('List:Scroll:Right','l',function(){this.scrollHorizontally(true);},this);app.shortcuts.register('List:Select:Open','o',function(){if(this.$('.selected [data-type=name] a:visible').length>0){this.$('.selected [data-type=name] a:visible').get(0).click();}else if(this.$('.selected [data-type=fullname] a:visible').length>0){this.$('.selected [data-type=fullname] a:visible').get(0).click();}},this);}})