/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({className:'row-fluid',dashboardLayouts:{'record':'record-dashboard','records':'list-dashboard','search':'search-dashboard'},events:{'click [data-action=create]':'createClicked'},error:{handleNotFoundError:function(error){var currentRoute=Backbone.history.getFragment();if(currentRoute.substr(0,5)==='Home/'){app.router.redirect('#Home');return false;}},handleValidationError:function(error){return false;}},dashboardVisibleState:'open',initialize:function(options){var context=options.context,module=context.parent&&context.parent.get('module')||context.get('module');if(options.meta&&options.meta.method&&options.meta.method==='record'&&!context.get('modelId')){context.set('create',true);}
var hasDashboardModels;if(context.parent&&context.parent.get('search')){var contextBro=context.parent.getChildContext({module:'Home'});hasDashboardModels=contextBro.get('collection')&&contextBro.get('collection').length;if(hasDashboardModels){context.set({model:contextBro.get('collection').at(contextBro.get('currentDashboardIndex')-1),collection:this._getNewDashboardObject('collection',context),skipFetch:true});}}
if(!hasDashboardModels){var model=this._getNewDashboardObject('model',context);if(context.get('modelId')){model.set('id',context.get('modelId'),{silent:true});}
context.set({model:model,collection:this._getNewDashboardObject('collection',context)});}
this._super('initialize',[options]);this._bindButtonEvents();this.model.on('setMode',function(mode){if(mode==='edit'||mode==='create'){this.$('.dashboard').addClass('edit');}else{this.$('.dashboard').removeClass('edit');}},this);app.events.on('app:help:show',function(){this.openHelpDashboard(true);},this);app.events.on('app:help:hide',function(){this.closeHelpDashboard(true);},this);var defaultLayout=this.closestComponent('sidebar');if(defaultLayout){this.listenTo(defaultLayout,'sidebar:state:changed',function(state){this.dashboardVisibleState=state;if(state==='open'&&this.isHelpDashboard(true)){app.events.trigger('app:help:shown');}else{app.events.trigger('app:help:hidden');}},this);try{this.dashboardVisibleState=defaultLayout.isSidePaneVisible()?'open':'close';}catch(error){}}
this.model.on('sync',function(){if(this.dashboardVisibleState==='open'&&this.isHelpDashboard(true)){if(this.module==='Home'){var list=this.getComponent('list'),headerpane=(!_.isUndefined(list))?list.getComponent('dashboard-headerpane'):undefined;if(headerpane){var help_headerpane_meta=app.metadata.getView(this.module,'help-dashboard-headerpane');help_headerpane_meta.last_state=headerpane.meta.last_state;headerpane.meta=help_headerpane_meta;headerpane.render();}}}},this);if(module==='Home'&&context.has('modelId')){var lastVisitedStateKey=this.getLastStateKey();app.user.lastState.set(lastVisitedStateKey,context.get('modelId'));}},_bindButtonEvents:function(){this.context.on('button:save_button:click',this.handleSave,this);},initComponents:function(components,context,module){this._super('initComponents',[components,context,module]);if(this.isSearchContext()){this.model.trigger('change:metadata');}},isSearchContext:function(){return this.context.parent&&this.context.parent.get('search');},openHelpDashboard:function(fromEvent){if(!fromEvent){app.logger.warn('View.Layouts.Base.DashboardLayout#openHelpDashboard is deprecated since 7.7. Will be removed in 7.9. Use the event "app:help:show" instead.');}
if(this.dashboardVisibleState==='close'){var defaultLayout=this.closestComponent('sidebar');if(defaultLayout){defaultLayout.toggleSidePane(true);}}
if(!this.isHelpDashboard(fromEvent)){if(this.isSearchContext()){var contextBro=this.getContextBro(this.context.get('module'));contextBro.set('currentDashboardIndex',1);this.showHelpDashboard(contextBro.get('collection'),fromEvent);return;}else{this.collection.fetch({silent:true,success:_.bind(function(collection){this.showHelpDashboard.apply(this,[collection,fromEvent]);},this)});}}},closeHelpDashboard:function(fromEvent){if(!fromEvent){app.logger.warn('View.Layouts.Base.DashboardLayout#closeHelpDashboard is deprecated since 7.7. Will be removed in 7.9. Use the event "app:help:hide" instead.');}
if(this.isHelpDashboard(fromEvent)){if(this.isSearchContext()){var contextBro=this.getContextBro(this.context.get('module'));contextBro.set('currentDashboardIndex',2);this.hideHelpDashboard(contextBro.get('collection'),fromEvent);return;}
this.collection.fetch({silent:true,success:_.bind(function(collection){this.hideHelpDashboard.apply(this,[collection,fromEvent]);},this)});}},showHelpDashboard:function(collection,fromEvent){if(!fromEvent){app.logger.warn('View.Layouts.Base.DashboardLayout#showHelpDashboard is deprecated since 7.7. Will be removed in 7.9. Use the event "app:help:show" instead to open the help dashboard.');}
var dashboard=_.find(collection.models,function(model){return(model.get('dashboard_type')==='help-dashboard');});this._navigate(dashboard);app.events.trigger('app:help:shown');},hideHelpDashboard:function(collection,fromEvent){if(!fromEvent){app.logger.warn('View.Layouts.Base.DashboardLayout#hideHelpDashboard is deprecated since 7.7. Will be removed in 7.9. Use the event "app:help:hide" instead to close the help dashboard.');}
var dashboard=_.find(collection.models,function(model){return(model.get('dashboard_type')!='help-dashboard');});app.user.lastState.set(this.getLastStateKey(),'');this._navigate(dashboard);},isHelpDashboard:function(fromEvent){if(!fromEvent){app.logger.warn('View.Layouts.Base.DashboardLayout#isHelpDashboard is deprecated since 7.7. Will be removed in 7.9.');}
return(this.model.get('dashboard_type')==='help-dashboard');},getContextBro:function(module){return this.context.parent.getChildContext({module:module});},loadData:function(options,setFields){if(this.isSearchContext()){if(this.model.has('metadata')){return;}
this._loadSearchDashboards();this.context.set('skipFetch',true);this.context.set('currentDashboardIndex',2);this.navigateLayout(null,'search-dashboard');return;}
if(this.context.parent&&!this.context.parent.isDataFetched()){var parent=this.context.parent.get('modelId')?this.context.parent.get('model'):this.context.parent.get('collection');if(parent){parent.once('sync',function(){this._super('loadData',[options,setFields]);},this);}}else{this._super('loadData',[options,setFields]);}},_loadSearchDashboards:function(){var dashboardsMeta=this._getInitialDashboardMetadata();_.each(dashboardsMeta,function(dashMeta,index){var model=this._getNewDashboardObject('model',this.context);model.set('id',++index);model.set(dashMeta);this.collection.add(model);},this);},createClicked:function(evt){if(this.model.dashboardModule==='Home'){var route=app.router.buildRoute(this.module,null,'create');app.router.navigate(route,{trigger:true});}else{this.navigateLayout('create');}},_placeComponent:function(component){var dashboardEl=this.$('[data-dashboard]'),css=this.context.get('create')?' edit':'';if(dashboardEl.length===0){dashboardEl=$('<div></div>').attr({'class':'cols row-fluid'});this.$el.append($('<div></div>').addClass('dashboard'+css).attr({'data-dashboard':'true'}).append(dashboardEl));}else{dashboardEl=dashboardEl.children('.row-fluid');}
dashboardEl.append(component.el);},bindDataChange:function(){if(this.isSearchContext()){return;}
var modelId=this.context.get('modelId');if(!(modelId&&this.context.get('create'))&&this.collection){this.collection.on('reset',this.setDefaultDashboard,this);}},setDefaultDashboard:function(){if(this.disposed){return;}
var lastVisitedStateKey=this.getLastStateKey(),lastViewed=app.user.lastState.get(lastVisitedStateKey),hasHelpOnly=(this.collection.models.length==1&&_.first(this.collection.models).get('dashboard_type')==='help-dashboard'),helpLastShown=(hasHelpOnly&&lastViewed===_.first(this.collection.models).get('id'));if(hasHelpOnly&&!helpLastShown){this._renderEmptyTemplate();}else if(this.collection.models.length>0){var currentModule=this.context.get('module'),model;if(currentModule!=='Home'){model=_.first(this.collection.models);}else{model=this.collection.find(function(dash){return dash.get('dashboard_type')==='dashboard';});}
if(lastViewed){var lastVisitedModel=this.collection.get(lastViewed);if(!_.isEmpty(lastVisitedModel)){app.user.lastState.set(lastVisitedStateKey,'');model=lastVisitedModel;}}
if(currentModule=='Home'&&_.isString(lastViewed)&&lastViewed.indexOf('bwc_dashboard')!==-1){app.router.navigate(lastViewed,{trigger:true});}else{this._navigate(model);}}else{var _initDashboard=this._getInitialDashboardMetadata();if(_initDashboard&&!_.isEmpty(_initDashboard.metadata)){_.each(_initDashboard.metadata['components'],function(component,component_key){_.each(component['rows'],function(row,row_key){_initDashboard.metadata['components'][component_key]['rows'][row_key]=_.filter(row,function(cell){var module=(cell.context&&cell.context.module)?cell.context.module:this.module;return(!app.acl.hasAccess('access',module));});},this);_initDashboard.metadata['components'][component_key]['rows']=_.filter(_initDashboard.metadata['components'][component_key]['rows'],function(row){return(row.length>0);});},this);}
_.each(_initDashboard,function(dash){var model=this._getNewDashboardObject('model',this.context);model.set(dash);if(this.context.get('modelId')){model.set('id',this.context.get('modelId'),{silent:true});}
if(!_.isUndefined(model.get('metadata'))){model.save({},this._getDashboardModelSaveParams());this.collection.add(model);}},this);}},_getInitialDashboardMetadata:function(){var layoutName=this.dashboardLayouts[this.context.parent&&this.context.parent.get('layout')||'record'],initDash=app.metadata.getLayout(this.model.dashboardModule,layoutName)||{};if(_.has(initDash,'metadata')){initDash.dashboard_type=initDash.dashboard_type||'dashboard';}
return this.addHelpDashboardMetadata(initDash,true);},addHelpDashboardMetadata:function(_initDashboard,suppressWarning){if(!suppressWarning){app.logger.warn('View.Layouts.Base.DashboardLayout#addHelpDashboardMetadata is deprecated since 7.7. Will be removed in 7.9.');}
var _helpDB=app.metadata.getLayout(this.model.dashboardModule,'help-dashboard');if(_.has(_initDashboard,'metadata')){_initDashboard=[_helpDB,_initDashboard];}else{_initDashboard=[_helpDB];}
return _initDashboard;},getLastStateKey:function(){if(this._lastStateKey){return this._lastStateKey;}
var model=this.context.get('model'),view=model.get('view_name'),module=model.dashboardModule,key=module+'.'+view;this._lastStateKey=app.user.lastState.key(key,this);return this._lastStateKey;},_navigate:function(dashboard){if(this.disposed){return;}
var hasParentContext=(this.context&&this.context.parent),hasModelId=(dashboard&&dashboard.has('id')),actualModule=(hasParentContext)?this.context.parent.get('module'):this.module,isHomeModule=(actualModule==='Home');if(hasParentContext&&hasModelId){this._navigateLayout(dashboard.get('id'),dashboard.get('dashboard_type'));}else if(hasParentContext&&!hasModelId){this._navigateLayout('list');}else if(!hasParentContext&&hasModelId&&isHomeModule){app.navigate(this.context,dashboard);}else if(isHomeModule){var route=app.router.buildRoute(this.module);app.router.navigate(route,{trigger:true});}},_navigateLayout:function(dashboard,type){var onConfirm=_.bind(function(){this.navigateLayout(dashboard,type);},this),headerpane=this.getComponent('dashboard-headerpane');if(headerpane&&headerpane.changed){return headerpane.warnUnsavedChanges(onConfirm,undefined,_.bind(function(){this.collection.reset([],{silent:true});},this));}
onConfirm();},navigateLayout:function(id,type){var layout=this.layout;var lastVisitedStateKey=this.getLastStateKey();var type=!_.isUndefined(type)?type:'dashboard';var headerPaneView='dashboard-headerpane';if(this.isSearchContext()&&type==='help-dashboard'){headerPaneView='search-help-dashboard-headerpane';}else if(app.metadata.getView('Home',type+'-headerpane')){headerPaneView=type+'-headerpane';}
this.dispose();if(type==='help-dashboard'){app.events.trigger('app:help:shown');}else{app.events.trigger('app:help:hidden');}
if(!_.contains(['create','list'],id)){app.user.lastState.set(lastVisitedStateKey,id);}
var ctxVars={dashboard_type:'dashboard'};if(id==='create'){ctxVars.create=true;}else if(id!=='list'){ctxVars.modelId=id;}
layout.initComponents([{layout:{type:'dashboard',components:(id==='list')?[]:[{view:headerPaneView},{layout:'dashlet-main'}],last_state:{id:'last-visit'}},context:_.extend({module:'Home',forceNew:true},ctxVars)}]);layout.removeComponent(0);layout.loadData({},false);layout.render();},unbindData:function(){var model,collection;if(this.collection){this.collection.off('reset',this.setDefaultDashboard,this);}
if(this.context.parent){model=this.context.parent.get('model');collection=this.context.parent.get('collection');if(model){model.off('sync',null,this);}
if(collection){collection.off('sync',null,this);}}
this._super('unbindData');},_getNewDashboardObject:function(modelOrCollection,context){var obj,ctx=context&&context.parent||context,module=ctx.get('module')||context.get('module'),layoutName=ctx.get('layout')||'',sync=function(method,model,options){options=app.data.parseOptionsForSync(method,model,options);if(options&&options.params){options.params.max_num=-1;}
var callbacks=app.data.getSyncCallbacks(method,model,options),path=(this.dashboardModule==='Home'||model.id)?this.apiModule:this.apiModule+'/'+this.dashboardModule;if(method==='read'){options.params.view_name=layoutName;}
app.data.trigger('data:sync:start',method,model,options);model.trigger('data:sync:start',method,options);app.api.records(method,path,model.attributes,options.params,callbacks);};if(module==='Home'){layoutName='';}
switch(modelOrCollection){case'model':obj=this._getNewDashboardModel(module,layoutName,sync);break;case'collection':obj=this._getNewDashboardCollection(module,layoutName,sync);break;}
return obj;},_getNewDashboardModel:function(module,layoutName,syncFn,getNew){getNew=(_.isUndefined(getNew))?true:getNew;var Dashboard=app.Bean.extend({sync:syncFn,apiModule:'Dashboards',module:'Home',dashboardModule:module,maxColumns:(module==='Home')?3:1,minColumnSpanSize:(module==='Home')?4:12,defaults:{view_name:layoutName}});return(getNew)?new Dashboard():Dashboard;},_getNewDashboardCollection:function(module,layoutName,syncFn,getNew){getNew=(_.isUndefined(getNew))?true:getNew;var Dashboard=this._getNewDashboardModel(module,layoutName,syncFn,false),DashboardCollection=app.BeanCollection.extend({sync:syncFn,apiModule:'Dashboards',module:'Home',dashboardModule:module,model:Dashboard});return(getNew)?new DashboardCollection():DashboardCollection;},_getDashboardModelSaveParams:function(){var params={silent:true,showAlerts:false};params.error=_.bind(this._renderEmptyTemplate,this);params.success=_.bind(function(model){if(!this.disposed){if(model.get('dashboard_module')!=='Home'){if(model.get('dashboard_type')==='help-dashboard'){this._navigate(model);}}else{if(model.get('dashboard_type')==='dashboard'){this._navigate(model);}}}},this);return params;},_renderEmptyTemplate:function(){var tplName=this.type||this.name,template=app.template.getLayout(tplName+'.dashboard-empty');this.$el.html(template(this));},_dispose:function(){app.events.trigger('app:help:hidden');var defaultLayout=this.closestComponent('sidebar');if(defaultLayout){this.stopListening(defaultLayout);}
this.dashboardLayouts=null;this._super('_dispose');},handleSave:function(){this.model.save({},{showAlerts:true,fieldsToValidate:{'name':{required:true},'metadata':{required:true}},success:_.bind(function(){this.model.unset('updated');if(this.context.get('create')){if(this.context.parent){this.getContextBro('Home').get('collection').add(this.model);this.navigateLayout(this.model.id);}else{app.navigate(this.context,this.model);}}else{this.context.trigger('record:set:state','view');}},this),error:function(){app.alert.show('error_while_save',{level:'error',title:app.lang.get('ERR_INTERNAL_ERR_MSG'),messages:['ERR_HTTP_500_TEXT_LINE1','ERR_HTTP_500_TEXT_LINE2']});}});}})