/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({extendsFrom:'ListView',className:'flex-list-view',_previewed:null,initialize:function(options){this.plugins=_.union(this.plugins,['Tooltip']);this._super('initialize',[options]);this.leftColumns=[];this.rightColumns=[];this.addActions();this.template=app.template.getView('flex-list');this.events=_.clone(this.events);this._allListViewsFieldListKey=app.user.lastState.buildKey('field-list','list-views',this.module);this._thisListViewFieldListKey=app.user.lastState.key('visible-fields',this);if(this.meta.sticky_resizable_columns){this._thisListViewFieldSizesKey=app.user.lastState.key('width-fields',this);}
this._fields=this.parseFields();this.addPreviewEvents();this.resize=_.bind(_.debounce(this.resize,200),this);this.bindResize();var rightColumnsEvents={};if(this.rightColumns.length){rightColumnsEvents={'hidden.bs.dropdown .flex-list-view .actions':'resetDropdownDelegate','shown.bs.dropdown .flex-list-view .actions':'delegateDropdown'};}
this.events=_.extend(rightColumnsEvents,this.events,{'click [data-widths=reset]':'resetColumnWidths','click [data-columns-order=reset]':'resetColumnOrder'});this.on('list:reorder:columns',this.reorderCatalog,this);this.on('list:toggle:column',this.saveCurrentState,this);this.on('list:save:laststate',this.saveCurrentState,this);this.on('list:column:resize:save',this.saveCurrentWidths,this);this.on('list:scrollLock',this.scrollLock,this);},resetDropdownDelegate:function(e){this.$el.removeClass('no-touch-scrolling');var $b=this.$(e.currentTarget).first();$b.parent().closest('.list').removeClass('open');$b.off('resetDropdownDelegate.right-actions');},delegateDropdown:function(e){var $buttonGroup=this.$(e.currentTarget).first(),windowHeight=$(window).height()-65;var needsDropupClass=function($b){var menuHeight=$b.height()+$b.children('ul').first().height();return(windowHeight<$b.offset().top+menuHeight);};this.$el.addClass('no-touch-scrolling');$buttonGroup.parent().closest('.list').addClass('open');$buttonGroup.toggleClass('dropup',needsDropupClass($buttonGroup));$buttonGroup.on('resetDropdownDelegate.right-actions',this.resetDropdownDelegate);$buttonGroup.parents('.main-pane').on('scroll.right-actions',_.bind(_.debounce(function(){$buttonGroup.toggleClass('dropup',needsDropupClass($buttonGroup));},30),this));},addPreviewEvents:function(){this.context.on("list:preview:fire",function(model){app.events.trigger("preview:render",model,this.collection,true);},this);app.events.on("list:preview:decorate",this.decorateRow,this);if(this.layout){this.layout.on("list:sort:fire",function(){app.events.trigger("preview:close");},this);this.layout.on("list:paginate:success",function(){app.events.trigger("preview:collection:change",this.collection);if(this._previewed){this.decorateRow(this._previewed);}},this);}},parseFields:function(){var fields=_.flatten(_.pluck(this.meta.panels,'fields'));this._defaultFieldOrder=_.pluck(fields,'name');var catalog=this._createCatalog(fields);this._thisListViewFieldList=this._getFieldsLastState();if(this._thisListViewFieldList){catalog=this._toggleFields(catalog,this._thisListViewFieldList,false);catalog=this.reorderCatalog(catalog,this._thisListViewFieldList.position,false);}
return catalog;},_getFieldsLastState:function(){if(!this._thisListViewFieldListKey){return;}
var data=app.user.lastState.get(this._thisListViewFieldListKey);if(_.isUndefined(data)){return;}
if(!_.isArray(data)||_.isEmpty(data)){app.logger.error('The format of "'+this._thisListViewFieldListKey+'" is unexpected, skipping.');return;}
if(_.isString(data[0])){return this._convertFromOldFormat(data);}
return this._decodeCacheData(data);},_createCatalog:function(fields){var catalog={};catalog._byId={};catalog.visible=[];catalog.all=[];_.each(fields,function(fieldMeta,i){catalog._byId[fieldMeta.name]=this._patchField(fieldMeta,i);},this);catalog.all=_.toArray(catalog._byId);catalog.visible=_.where(catalog.all,{selected:true});return catalog;},_patchField:function(fieldMeta,index){var isVisible=(fieldMeta['default']!==false);return _.extend({selected:isVisible,position:index+1},fieldMeta);},_toggleFields:function(catalog,fields,saveLastState){if(_.isEmpty(fields)||(_.isEmpty(fields.visible)&&_.isEmpty(fields.hidden))){return catalog;}
saveLastState=_.isUndefined(saveLastState)?true:saveLastState;_.each(fields.visible,function(fieldName){var f=catalog._byId[fieldName];if(f){f.selected=true;}},this);_.each(fields.hidden,function(fieldName){var f=catalog._byId[fieldName];if(f){f.selected=false;}},this);catalog.all=_.sortBy(_.toArray(catalog._byId),function(f){return f.position;});catalog.visible=_.where(catalog.all,{selected:true});if(saveLastState){this.trigger('list:save:laststate');}
return catalog;},reorderCatalog:function(catalog,order,saveLastState){saveLastState=_.isUndefined(saveLastState)?true:saveLastState;order=_.union(order,_.pluck(catalog.all,'name'));_.each(order,function(fieldName,i){var f=catalog._byId[fieldName];if(f){f.position=++i;}});catalog.all=_.sortBy(_.toArray(catalog._byId),function(f){return f.position;});catalog.visible=_.where(catalog.all,{selected:true});if(saveLastState){this.trigger('list:save:laststate');}
return catalog;},_decodeCacheData:function(encodedData){var decodedData={visible:[],hidden:[],position:[]};var fieldList=this._appendFieldsToAllListViewsFieldList();_.each(encodedData,function(fieldArray,i){if(!_.isArray(fieldArray)){return;}
var name=fieldList[i];if(fieldArray[0]){decodedData.visible.push(name);}else{decodedData.hidden.push(name);}
decodedData.position[fieldArray[1]]=name;});decodedData.position=_.difference(decodedData.position,[undefined]);return decodedData;},_encodeCacheData:function(decodedData){var encodedData=[];var fieldList=this._appendFieldsToAllListViewsFieldList();_.each(fieldList,function(fieldName){var value=0;if(_.contains(decodedData.position,fieldName)){value=[_.contains(decodedData.visible,fieldName)?1:0,_.indexOf(decodedData.position,fieldName)+1];}
encodedData.push(value);});return encodedData;},_encodeCacheWidthData:function(decodedData){var encodedData=[];var fieldList=this._appendFieldsToAllListViewsFieldList();var visibleIndex=0;_.each(fieldList,function(fieldName){var value=0;if(_.contains(decodedData.visible,fieldName)){value=decodedData.widths[visibleIndex++];}
encodedData.push(value);});return encodedData;},_decodeCacheWidthData:function(encodedData){var decodedData={'visible':[],'widths':[]};var fieldList=this._appendFieldsToAllListViewsFieldList();_.each(_.pluck(this._fields.visible,'name'),function(fieldName){var index=_.indexOf(fieldList,fieldName);var width=encodedData[index]||0;decodedData.visible.push(fieldName);decodedData.widths.push(width);});return decodedData;},_appendFieldsToAllListViewsFieldList:function(){this._allListViewsFieldList=app.user.lastState.get(this._allListViewsFieldListKey)||[];var obj={};_.each(this._allListViewsFieldList,function(fieldName){obj[fieldName]=fieldName;});_.each(this.meta.panels,function(panel){_.each(panel.fields,function(fieldMeta,i){obj[fieldMeta.name]=fieldMeta.name;},this);},this);this._allListViewsFieldList=_.keys(obj);app.user.lastState.set(this._allListViewsFieldListKey,this._allListViewsFieldList);return this._allListViewsFieldList;},_convertFromOldFormat:function(visibleFieldList){var thisViewFieldList=_.reduce(_.map(this.meta.panels,function(panel){return _.pluck(panel.fields,'name');}),function(memo,field){return memo.concat(field);},[]);var decoded={visible:[],hidden:[],position:[]};_.each(thisViewFieldList,function(fieldName,i){if(_.contains(visibleFieldList,fieldName)){decoded.visible.push(fieldName);}else{decoded.hidden.push(fieldName);}
decoded.position.push(fieldName);});app.user.lastState.set(this._thisListViewFieldListKey,this._encodeCacheData(decoded));return decoded;},saveCurrentState:function(){if(!this._thisListViewFieldListKey){return;}
var allFields=_.pluck(this._fields.all,'name'),visibleFields=_.pluck(this._fields.visible,'name');var decoded={visible:visibleFields,hidden:_.difference(allFields,visibleFields),position:allFields};app.user.lastState.set(this._thisListViewFieldListKey,this._encodeCacheData(decoded));this._thisListViewFieldList=this._getFieldsLastState();},addActions:function(){var meta=this.meta;if(_.isObject(meta.selection)){this.isSearchAndSelectAction=meta.selection.isSearchAndSelectAction;switch(meta.selection.type){case'single':this.addSingleSelectionAction();break;case'multi':this.addMultiSelectionAction();break;default:break;}}
if(meta&&_.isObject(meta.rowactions)){this.addRowActions();}},addSingleSelectionAction:function(){var _generateMeta=function(name,label){return{'type':'selection','name':name,'sortable':false,'label':label||''};};var def=this.meta.selection;this.leftColumns.push(_generateMeta(def.name||this.module+'_select',def.label));},addMultiSelectionAction:function(){var _generateMeta=function(buttons,disableSelectAllAlert){return{'type':'fieldset','fields':[{'type':'actionmenu','buttons':buttons||[],'disable_select_all_alert':!!disableSelectAllAlert}],'value':false,'sortable':false};};var buttons=this.meta.selection.actions;var disableSelectAllAlert=!!this.meta.selection.disable_select_all_alert;this.leftColumns.push(_generateMeta(buttons,disableSelectAllAlert));},addRowActions:function(){var _generateMeta=function(label,css_class,buttons){return{'type':'fieldset','fields':[{'type':'rowactions','label':label||'','css_class':css_class,'buttons':buttons||[]}],'value':false,'sortable':false};};var def=this.meta.rowactions;this.rightColumns.push(_generateMeta(def.label,def.css_class,def.actions));},decorateRow:function(model){if(_.isUndefined(app.drawer)||app.drawer.isActive(this.$el)){this._previewed=model;this.$("tr.highlighted").removeClass("highlighted current above below");if(model){var rowName=model.module+"_"+model.id;var curr=this.$("tr[name='"+rowName+"']");curr.addClass("current highlighted");curr.prev("tr").addClass("highlighted above");curr.next("tr").addClass("highlighted below");}}},_renderHtml:function(){this.colSpan=this._fields.visible.length||0;if(this.leftColumns.length){this.colSpan++;}
if(this.rightColumns.length){this.colSpan++;}
if(this.colSpan<2){this.colSpan=null;}
this._super('_renderHtml');if(this.leftColumns.length){this.$el.addClass('left-actions');}
if(this.rightColumns.length){this.$el.addClass('right-actions');}
var displayWidthSetting=this._thisListViewFieldSizes||!_.isUndefined(app.user.lastState.get(this._thisListViewFieldSizesKey));var displayOrderSetting=false;if(this._thisListViewFieldList){var customOrder=_.union(this._thisListViewFieldList.position,this._defaultFieldOrder);displayOrderSetting=!_.isEqual(customOrder,this._defaultFieldOrder);}
this._toggleSettings('widths',displayWidthSetting);this._toggleSettings('order',displayOrderSetting);this.resize();},_render:function(){this._super('_render');if(this.closestComponent('sidebar')&&!(app.drawer.count())){this._setHelperScrollBar();}},_setHelperScrollBar:function(){this.$helper=this.$('[data-scroll-spy]');if(this.$helper.length===0){return;}
this.$spy=this.$('.'+this.$helper.data('scrollSpy'));this.$helper.find('div').width(this.$spy.get(0).scrollWidth);this._updateHelperWidth();this.listenTo(this.closestComponent('sidebar'),'sidebar:toggle',_.bind(this._updateHelperWidth,this));this.$helper.on('scroll.'+this.cid,_.bind(function(){this.$spy.scrollLeft(this.$helper.scrollLeft());},this));this.$spy.on('scroll.'+this.cid,_.bind(function(){this.$helper.scrollLeft(this.$spy.scrollLeft());},this));$('#content').on('scroll.'+this.cid,_.bind(function(){this._toggleScrollHelper();},this));$('.main-pane').on('scroll.'+this.cid,_.bind(function(){this._toggleScrollHelper();},this));},_toggleScrollHelper:function(){if(this.$spy.get(0).scrollWidth<=this.$spy.width()||this.$('tbody').offset().top+this.$helper.height()>$('footer').offset().top){this.$helper.toggle(false);return;}
this.$helper.toggle(!(this.$('.scrollbar-landmark').offset().top<$('footer').offset().top));if(this.$helper.css('display')!=='none'){this.$helper.scrollLeft(this.$spy.scrollLeft());}},_updateHelperWidth:function(){if(this.$helper.length===0){return;}
this.$helper.toggleClass('dash-collapsed',!$('.side.sidebar-content').is(':visible'));},saveCurrentWidths:function(columns){this.resize();if(!this._thisListViewFieldListKey){return;}
var visibleFields=_.pluck(this._fields.visible,'name');var decoded={visible:visibleFields,widths:columns};var encoded=this._encodeCacheWidthData(decoded);this._toggleSettings('widths',true);this._thisListViewFieldSizes=encoded;if(this._thisListViewFieldSizesKey){app.user.lastState.set(this._thisListViewFieldSizesKey,encoded);}},resetColumnWidths:function(){this._thisListViewFieldSizes=null;if(this._thisListViewFieldSizesKey){app.user.lastState.remove(this._thisListViewFieldSizesKey);}
if(!this.disposed){this.render();this._toggleSettings('widths',false);}},resetColumnOrder:function(){var fields=_.flatten(_.pluck(this.meta.panels,'fields'));this._fields=this._createCatalog(fields);this.saveCurrentState();if(this.disposed){return;}
this.render();},_toggleSettings:function(category,show){this.$('li[data-settings-li='+category+']').toggle(show);},getCacheWidths:function(){var encodedData=this._thisListViewFieldSizes||app.user.lastState.get(this._thisListViewFieldSizesKey);if(!encodedData){return;}
return this._decodeCacheWidthData(encodedData).widths;},unbind:function(){$('#content, .main-pane').off('scroll.'+this.cid);$(this).parents('.main-pane').off('scroll.right-actions');this.$('.flex-list-view .actions').trigger('resetDropdownDelegate.right-actions');$(window).off('resize.flexlist-'+this.cid);if(this.$helper){this.$helper.off('scroll.'+this.cid);}
if(this.$spy){this.$spy.off('scroll.'+this.cid);}
this._super('unbind');},bindResize:function(){$(window).on("resize.flexlist-"+this.cid,_.bind(this.resize,this));},scrollLock:function(lock){var $content=this.$('.flex-list-view-content');if(lock){$content.css({'overflow-y':'visible','overflow-x':'hidden'});}else{$content.removeAttr('style');}},resize:function(){if(this.disposed){return;}
var $content=this.$('.flex-list-view-content');if(!$content.length){return;}
var toggle=$content.get(0).scrollWidth>$content.width()+1;this.$el.toggleClass('scroll-width',toggle);if(this.$helper&&this.$helper.length>0){this.$helper.find('div').width(this.$spy.get(0).scrollWidth);this._toggleScrollHelper();}}})