/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({plugins:['Dashlet','Tooltip','Chart'],tooltiptemplate:null,params:null,isManager:false,forecastBy:null,likelyField:null,initialize:function(options){this.isManager=app.user.get('is_manager');this._initPlugins();var config=app.metadata.getModule('Forecasts','config');this.forecastBy=config&&config.forecast_by||'Opportunities';options.meta.label=app.lang.get(options.meta.label,this.forecastBy);this._super('initialize',[options]);var fields=['id','name','account_name','base_rate','currency_id','assigned_user_name','date_closed','probability','account_id','sales_stage','commit_stage'];var orderBy='';if(this.forecastBy==='Opportunities'){fields.push('amount');orderBy='amount:desc';this.likelyField='amount';}else{fields.push('likely_case');orderBy='likely_case:desc';this.likelyField='likely_case';}
this.params={'fields':fields.join(','),'max_num':10,'order_by':orderBy};this.tooltiptemplate=app.template.getView(this.name+'.tooltiptemplate');},initDashlet:function(view){var self=this;if(this.settings.get('filter_duration')==0){this.settings.set({'filter_duration':'current'},{'silent':true});}
this.setDateRange();if(!this.isManager&&this.meta.config){this.meta.panels=_.chain(this.meta.panels).filter(function(panel){panel.fields=_.without(panel.fields,_.findWhere(panel.fields,{name:'visibility'}));return panel;}).value();}
this.chart=nv.models.bubbleChart().x(function(d){return d3.time.format('%Y-%m-%d').parse(d.x);}).y(function(d){return d.y;}).margin({top:0}).tooltipContent(function(key,x,y,e,graph){e.point.close_date=d3.time.format('%x')(d3.time.format('%Y-%m-%d').parse(e.point.x));e.point.amount=e.point.currency_symbol+d3.format(',.2d')(e.point.base_amount);return self.tooltiptemplate(e.point).replace(/(\r\n|\n|\r)/gm,'');}).showTitle(false).tooltips(true).showLegend(true).direction(app.lang.direction).bubbleClick(function(e){self.chart.dispatch.tooltipHide(e);app.router.navigate(app.router.buildRoute(self.forecastBy,e.point.id),{trigger:true});}).colorData('class',{step:2}).groupBy(function(d){return(self.isManager&&self.getVisibility()==='user')?d.sales_stage_short:d.assigned_user_name;}).filterBy(function(d){return d.probability;}).strings({legend:{close:app.lang.get('LBL_CHART_LEGEND_CLOSE'),open:app.lang.get('LBL_CHART_LEGEND_OPEN')},noData:app.lang.get('LBL_CHART_NO_DATA')});this.on('data-changed',function(){this.renderChart();},this);this.settings.on('change:filter_duration',this.changeFilter,this);this.layout.on('render',function(){if(!this.disposed&&!this.settings.get('config')){this.layout.setTitle(app.lang.get(this.meta.label,this.forecastBy));}},this);},_initPlugins:function(){if(this.isManager){this.plugins=_.union(this.plugins,['ToggleVisibility']);}
return this;},renderChart:function(){if(!this.isChartReady()){return;}
this.$('svg#'+this.cid).children().remove();d3.select('svg#'+this.cid).datum(this.chartCollection).transition().duration(500).call(this.chart);this.chart_loaded=_.isFunction(this.chart.render);this.displayNoData(!this.chart_loaded);},chartResize:function(){this.chart.render();},evaluateResult:function(data){this.total=data.records.length;var statusOptions='sales_stage_dom',fieldMeta=app.metadata.getModule(this.forecastBy,'fields');if(fieldMeta){statusOptions=fieldMeta.sales_stage.options||statusOptions;}
this.chartCollection={data:data.records.map(function(d){var sales_stage=app.lang.getAppListStrings(statusOptions)[d.sales_stage]||d.sales_stage;if(_.isNull(d.probability)||d.probability===''){d.probability=0;}
if(_.isNull(d[this.likelyField])||d[this.likelyField]===''){d[this.likelyField]=0;}
return{id:d.id,x:d.date_closed,y:Math.round(parseInt(d[this.likelyField],10)/ parseFloat(d.base_rate)),shape:'circle',account_name:d.account_name,assigned_user_name:d.assigned_user_name,sales_stage:sales_stage,sales_stage_short:sales_stage,probability:parseInt(d.probability,10),base_amount:parseInt(d[this.likelyField],10),currency_symbol:app.currency.getCurrencySymbol(d.currency_id)};},this),properties:{title:app.lang.get('LBL_DASHLET_TOP10_SALES_OPPORTUNITIES_NAME'),value:data.records.length}};},loadData:function(options){var self=this,_filter=[{'date_closed':{'$gte':self.dateRange.begin}},{'date_closed':{'$lte':self.dateRange.end}}];if(!this.isManager||this.getVisibility()==='user'){_filter.push({'$owner':''});}
var _local=_.extend({'filter':_filter},this.params);var url=app.api.buildURL(this.forecastBy,null,null,_local,this.params);app.api.call('read',url,null,{success:function(data){self.evaluateResult(data);if(!self.disposed){self.trigger('data-changed');}},error:_.bind(function(){this.displayNoData(true);},this),complete:options?options.complete:null});},setDateRange:function(){var now=new Date(),mapping={'current':0,'next':3,'year':12},duration=mapping[this.settings.get('filter_duration')],startMonth=Math.floor(now.getMonth()/ 3)*3,startDate=new Date(now.getFullYear(),(duration===12?0:startMonth+duration),1),endDate=new Date(now.getFullYear(),(duration===12?12:startDate.getMonth()+3),0);this.dateRange={'begin':app.date.format(startDate,'Y-m-d'),'end':app.date.format(endDate,'Y-m-d')};},changeFilter:function(){this.setDateRange();this.loadData();},_dispose:function(){this.off('data-changed');this.settings.off('change:filter_duration');this._super('_dispose');}})