/*
     * Your installation or use of this SugarCRM file is subject to the applicable
     * terms available at
     * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
     * If you do not agree to all of the applicable terms or do not have the
     * authority to bind the entity as an authorized representative, then do not
     * install or use this SugarCRM file.
     *
     * Copyright (C) SugarCRM Inc. All rights reserved.
     */
({className:'table-cell quicksearch-selected-tags',events:{'click .tag-remove':'removeTagClicked','click .tag-name':'highlightTagClicked'},initialize:function(options){this._super('initialize',[options]);this.selectedTags=this.layout.selectedTags||[];this.activeIndex=null;this.layout.on('quicksearch:tag:add',this.addTag,this);this.layout.on('quicksearch:tags:remove',this.removeAllTags,this);this.on('navigate:focus:receive',function(next){if(next){this.activeIndex=0;}else{this.activeIndex=this.selectedTags.length-1;}
this._highlightActive();this.attachKeydownEvent();},this);this.on('navigate:focus:lost',function(){this.activeIndex=null;this.$('.tag-wrapper').removeClass('highlight');this.disposeKeydownEvent();},this);app.events.on('app:sync:complete',function(){this.layout.off('route:search',this.populateTagsFromContext);this.layout.on('route:search',this.populateTagsFromContext,this);},this);this.context.on('tagsearch:fire:new',this.populateTagsFromContext,this);},populateTagsFromContext:function(){var tagNames=this.context.get('tagParams');if(!tagNames||!tagNames.length){this.selectedTags.splice(0,this.selectedTags.length);this.render();this.context.set('tags',[]);this.context.trigger('search:fire:new');return;}
var tags=app.data.createBeanCollection('Tags');var self=this;var tagNamesLowerCase=_.map(tagNames,function(tagName){return tagName.toLowerCase();});tags.filterDef={'filter':[{'name_lower':{'$in':tagNamesLowerCase}}]};tags.fetch({limit:100,success:function(collection){self.selectedTags.splice(0,self.selectedTags.length);_.each(collection.models,function(tag){self.selectedTags.push({id:tag.get('id'),name:tag.get('name')});});self.render();self.context.set('tags',self.selectedTags);self.layout.trigger('quicksearch:button:toggle',false);self.context.trigger('search:fire:new');},error:function(e){app.alert.show('collections_error',{level:'error',messages:'LBL_TAG_FETCH_ERROR'});}});},isFocusable:function(){return this.selectedTags&&this.selectedTags.length;},attachKeydownEvent:function(){$(document).on('keydown.'+this.cid,_.bind(this.keydownHandler,this));},disposeKeydownEvent:function(){$(document).off('keydown.'+this.cid);},keydownHandler:function(e){switch(e.keyCode){case 37:this.moveLeft();break;case 39:this.moveRight();break;case 8:case 46:this.handleBackspace();e.stopPropagation();e.preventDefault();break;default:this.layout.trigger('navigate:to:component','quicksearch-bar');break;}},handleBackspace:function(){this.removeTag(false);if(this.selectedTags.length){if(this.activeIndex>0){this.activeIndex--;}
this._highlightActive();}else{this.moveRight();}},addTag:function(tag){if(tag&&tag.name){if(!_.find(this.selectedTags,function(tagToCheck){return tagToCheck.name===tag.name;})){this.selectedTags.push(tag);this.render();this.layout.trigger('quicksearch:fire:search',true);}}},removeTag:function($tagParam){if(!$tagParam&&_.isNull(this.activeIndex)){return;}
var $tag=$tagParam||this.$('.tag-wrapper:eq('+this.activeIndex+')');var index=_.indexOf(_.pluck(this.selectedTags,'name'),$tag.attr('tag-name'));this.selectedTags.splice(index,1);$tag.remove();this.layout.trigger('quicksearch:fire:search',true);},removeTagClicked:function(e){e.preventDefault();e.stopPropagation();var $tag=this.$(e.target).parent();this.removeTag($tag);this.$('.tag-wrapper').removeClass('highlight');this.layout.trigger('navigate:to:component','quicksearch-bar');},removeAllTags:function(){this.selectedTags.splice(0,this.selectedTags.length);this.activeIndex=null;this.$('.tag-wrapper').remove();},highlightTagClicked:function(e){this.requestFocus();this.$('.tag-wrapper').removeClass('highlight');var $tag=this.$(e.target).parent();$tag.addClass('highlight');this.activeIndex=_.indexOf(_.pluck(this.selectedTags,'name'),$tag.attr('tag-name'));},_highlightActive:function(){this.$('.tag-wrapper').removeClass('highlight');this.$('.tag-wrapper:eq('+this.activeIndex+')').addClass('highlight');},requestFocus:function(){this.layout.trigger('navigate:to:component',this.name);},moveRight:function(){if(this.activeIndex<this.selectedTags.length-1){this.activeIndex++;this._highlightActive();}else{this._handleBoundary(true);}},moveLeft:function(){if(this.activeIndex>0){this.activeIndex--;this._highlightActive();}else{this._handleBoundary(false);}},_handleBoundary:function(next){var event='navigate:next:component';if(!next){event='navigate:previous:component';}
if(this.layout.triggerBefore(event)){this.clearActive();this.layout.trigger(event);}},clearActive:function(){this.activeIndex=null;this.$('.tag-wrapper').removeClass('highlight');this.disposeKeydownEvent();},unbind:function(){this.disposeKeydownEvent();this._super('unbind');}})